### PR TITLE
Added logs filter/hide check.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#559](https://paste.centos.org/view/d98dc9e5 )
  * :question: upstream-istio-pipeline [#[431]](https://paste.centos.org/view/21088a25 )
  * :heavy_check_mark: build-kiali [#[2296]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[270]](Log omitted)
  * :heavy_check_mark: install-istio [#[939]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8397, 8398, 8399]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5744, 5745, 5746]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4156, 4157]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1252]](https://paste.centos.org/view/c5fbdf08 )
  * :question: run-kiali-ui-tests [#[21153, 21154, 21155, 21156, 21157, 21158, 21159, 21160, 21161, 21162, 21163, 21164, 21165, 21166, 21167, 21168, 21169]](https://paste.centos.org/view/902c191a )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#561](https://paste.centos.org/view/0a709370 )
  * :red_circle: upstream-istio-pipeline [#[435]](https://paste.centos.org/view/b4f9e679 )
  * :heavy_check_mark: build-kiali [#[2305]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[276]](Log omitted)
  * :red_circle: install-istio [#[949]](https://paste.centos.org/view/9b7b046b )
  * :heavy_check_mark: clean-environment [#[8425]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#563](https://paste.centos.org/view/2350487b )
  * :question: upstream-istio-pipeline [#[437]](https://paste.centos.org/view/b1957299 )
  * :heavy_check_mark: build-kiali [#[2308]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[278]](Log omitted)
  * :heavy_check_mark: install-istio [#[952]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8436, 8437, 8438]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5779, 5780, 5781]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4179, 4180]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1261]](https://paste.centos.org/view/9768ed10 )
  * :red_circle: run-kiali-ui-tests [#[21312, 21313, 21314, 21315, 21316, 21317, 21318, 21319, 21320, 21321, 21322, 21323, 21307, 21308, 21309, 21310, 21311]](https://paste.centos.org/view/c340640c https://paste.centos.org/view/43955ee7 )

**Comment by hhovsepy** [comment]
manual run pass

**Pull request merged**
