### PR TITLE
Added test for Request Timeouts in wizards.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#636](https://paste.centos.org/view/3ae08081 )
  * :question: upstream-istio-pipeline [#[710]](https://paste.centos.org/view/f2cc147a )
  * :heavy_check_mark: build-kiali [#[3131]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[782]](Log omitted)
  * :heavy_check_mark: install-istio [#[1571]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11673, 11674, 11675]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7992, 7990, 7991]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5586, 5587]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1713]](https://paste.centos.org/view/ddad3b4c )
  * :question: run-kiali-ui-tests [#[29024, 29025, 29026, 29027, 29028, 29029, 29030, 29031, 29032, 29033, 29034, 29035, 29036, 29037, 29021, 29022, 29023]](https://paste.centos.org/view/995e9d8d https://paste.centos.org/view/8c971198 https://paste.centos.org/view/3536bc7b https://paste.centos.org/view/1a35bb06 https://paste.centos.org/view/714c6505 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#637](https://paste.centos.org/view/11eb5b0d )
  * :question: upstream-istio-pipeline [#[711]](https://paste.centos.org/view/ce3741c1 )
  * :heavy_check_mark: build-kiali [#[3132]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[783]](Log omitted)
  * :heavy_check_mark: install-istio [#[1572]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11676, 11677, 11678]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7993, 7994, 7995]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5588, 5589]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1714]](https://paste.centos.org/view/c746ef69 )
  * :question: run-kiali-ui-tests [#[29039, 29040, 29041, 29042, 29043, 29044, 29045, 29046, 29047, 29048, 29049, 29050, 29051, 29052, 29053, 29054, 29055]](https://paste.centos.org/view/0c88c0cb https://paste.centos.org/view/2f7687b3 https://paste.centos.org/view/a5947ea9 https://paste.centos.org/view/2da8b15e https://paste.centos.org/view/3149ecf6 https://paste.centos.org/view/ce33755f )

**Comment by hhovsepy** [comment]
manual rerun pass

**Pull request merged**
