### PR TITLE
Added more checks for service validations

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#483](https://paste.centos.org/view/f5017c26 )
  * :question: upstream-pipeline [#[634]](https://paste.centos.org/view/76dab22d )
  * :heavy_check_mark: build-kiali [#[1025]](Log omitted)
  * :heavy_check_mark: install-maistra [#[1499]](Log omitted)
  * :heavy_check_mark: clean-environment [#[3648, 3649, 3650, 3647]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2171, 2172, 2173]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[1824, 1825]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1011]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[531]](https://paste.centos.org/view/289c001e )
  * :question: run-kiali-ui-tests [#[8940, 8941, 8942, 8943, 8944, 8945, 8946, 8947, 8948, 8949, 8950, 8951, 8952, 8953, 8954, 8955, 8956]](https://paste.centos.org/view/1e0fbe4f https://paste.centos.org/view/9641abd4 https://paste.centos.org/view/33b13a4c https://paste.centos.org/view/c4a41dfa )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#484](https://paste.centos.org/view/ee5786b5 )
  * :red_circle: upstream-pipeline [#[635]](https://paste.centos.org/view/f9ceb6bc )
  * :heavy_check_mark: build-kiali [#[1026]](Log omitted)
  * :red_circle: install-maistra [#[1501]](https://paste.centos.org/view/123bf9ec )
  * :heavy_check_mark: clean-environment [#[3674]](Log omitted)

**Pull request merged**
