### PR TITLE
Reading endpoints from OC API and comparing with Service UI.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#665](https://paste.centos.org/view/a460f5de )
  * :question: upstream-istio-pipeline [#[812]](https://paste.centos.org/view/5d50e069 )
  * :heavy_check_mark: build-kiali [#[3481]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1001]](Log omitted)
  * :heavy_check_mark: install-istio [#[1785]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13584, 13585, 13581, 13583]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9601, 9603, 9604, 9605]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7026, 7027, 7028]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1930]](https://paste.centos.org/view/a6621e0b )
  * :question: run-kiali-ui-tests [#[32896, 32897, 32898, 32899, 32900, 32901, 32902, 32903, 32904, 32905, 32906, 32907, 32908, 32892, 32893, 32894, 32895]](https://paste.centos.org/view/d294bc68 https://paste.centos.org/view/d2d18e97 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#666](https://paste.centos.org/view/8fcf6e33 )
  * :question: upstream-istio-pipeline [#[813]](https://paste.centos.org/view/9aecabb7 )
  * :heavy_check_mark: build-kiali [#[3482]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1002]](Log omitted)
  * :heavy_check_mark: install-istio [#[1786]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13586, 13587, 13588, 13589]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9610, 9611, 9612, 9613]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7033, 7034, 7035]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1931]](https://paste.centos.org/view/3a3abd42 )
  * :question: run-kiali-ui-tests [#[32909, 32910, 32911, 32912, 32913, 32914, 32915, 32916, 32917, 32918, 32919, 32920, 32921, 32922, 32923, 32924, 32926]](https://paste.centos.org/view/2a3f77f9 https://paste.centos.org/view/2a06ad34 )

**Pull request merged**
