### PR TITLE
KIALI-1200 is fixed now, Added test for AppWorkload sidecar check.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#298](https://paste.fedoraproject.org/paste/zapGXKU4NkvZxUwOaRj~~A)
  * :question: Istio-and-Kiali-on-Openshift [#[2902]](https://paste.fedoraproject.org/paste/ppVyFqV9GeNqRMZJJaUHyw)
  * :heavy_check_mark: Istio-Upstream [#[1573]](https://paste.fedoraproject.org/paste/AuQM1uLhc4Nbm8zMjpB~vg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5761, 5762, 5764, 5766]](https://paste.fedoraproject.org/paste/jvCYKy8gcezdhuhd03neWQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3402, 3403]](https://paste.fedoraproject.org/paste/zhYCX64LxxIqJJXRq~Gn4A)
  * :heavy_check_mark: install-bookinfo [#[2725, 2726]](https://paste.fedoraproject.org/paste/hJGQ8hFmu7~mMM6aK47HYQ)
  * :question: python-ui-tests-parallel [#[556]](https://paste.fedoraproject.org/paste/uBNvrksZ40P0O20eYD652w)
  * :question: run-python3-ui-tests [#[2656, 2657, 2658, 2659, 2671, 2650, 2651, 2652, 2653, 2654, 2655]](https://paste.fedoraproject.org/paste/sB49lzxKo0rqjl1gnkZcNA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#301](https://paste.fedoraproject.org/paste/WdqEKkDkpP9s8Lhm0htk5Q)
  * :question: Istio-and-Kiali-on-Openshift [#[2905]](https://paste.fedoraproject.org/paste/IdZBNCDngNCO4e8uhlkWcg)
  * :heavy_check_mark: Istio-Upstream [#[1576]](https://paste.fedoraproject.org/paste/~-oHST2MQU-uuYbQ6v4TWQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5772, 5773, 5774, 5775]](https://paste.fedoraproject.org/paste/r9g1Wm9g8aVY~S-~NpCnGA)
  * :heavy_check_mark: Kiali-on-Openshift [#[3408, 3407]](https://paste.fedoraproject.org/paste/sWMLoayTqdECyyjGe3dlBw)
  * :heavy_check_mark: install-bookinfo [#[2731, 2732]](https://paste.fedoraproject.org/paste/Grg3cwvq2I3zMRRsR4CVDw)
  * :question: python-ui-tests-parallel [#[559]](https://paste.fedoraproject.org/paste/88DcTdWt8HItOuSCCiwF3Q)
  * :question: run-python3-ui-tests [#[2688, 2689, 2690, 2691, 2692, 2693, 2683, 2684, 2685, 2686, 2687]](https://paste.fedoraproject.org/paste/TDBd94HRFhbTLTBaXoPDVQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#302](https://paste.fedoraproject.org/paste/ud5n8~WCKU67HluH193Wmg)
  * :question: Istio-and-Kiali-on-Openshift [#[2913]](https://paste.fedoraproject.org/paste/iM9pGUfRACgb7tQBlGy2LQ)
  * :heavy_check_mark: Istio-Upstream [#[1584]](https://paste.fedoraproject.org/paste/tL5WO8zpYgBT5EqWghcr8Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5803, 5804, 5805, 5806]](https://paste.fedoraproject.org/paste/Ab9AJLufFEiARrkJyv6CzQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3425, 3426]](https://paste.fedoraproject.org/paste/gBLo6G3ER1RzqtYDYDTzwQ)
  * :heavy_check_mark: install-bookinfo [#[2747, 2748]](https://paste.fedoraproject.org/paste/RgLd~NPy5sSeqQT9WAB0-g)
  * :question: python-ui-tests-parallel [#[561]](https://paste.fedoraproject.org/paste/HjeQzQAz5V3blGdxDtp4nA)
  * :question: run-python3-ui-tests [#[2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715]](https://paste.fedoraproject.org/paste/KjyFZOuI2z3dL9UtmgMbFQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#303](https://paste.fedoraproject.org/paste/m0u2PtKPbte9zcRZD-J6VQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2914]](https://paste.fedoraproject.org/paste/DwliERDv3byg8TCK6RRhFQ)
  * :heavy_check_mark: Istio-Upstream [#[1585]](https://paste.fedoraproject.org/paste/Y-GDCzQiHTJ9~NHO74C49A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5808, 5809, 5810, 5807]](https://paste.fedoraproject.org/paste/dGlN~sZXFcoUsaaKPuL4lg)
  * :heavy_check_mark: Kiali-on-Openshift [#[3427, 3428]](https://paste.fedoraproject.org/paste/TuJZezKwQUZLo4K~ioxj4Q)
  * :heavy_check_mark: install-bookinfo [#[2749, 2750]](https://paste.fedoraproject.org/paste/4u8IiMteTPjy1iZkg1jsYQ)
  * :heavy_check_mark: python-ui-tests-parallel [#[562]](https://paste.fedoraproject.org/paste/nc4zvNuycPD~QEF~vQ8oog)
  * :heavy_check_mark: run-python3-ui-tests [#[2720, 2721, 2722, 2723, 2724, 2725, 2726, 2716, 2717, 2718, 2719]](https://paste.fedoraproject.org/paste/YG83lPS6A5kO4OkFx7w85A)

**Pull request merged**
