### PR TITLE
Added support of newly added Istio objects.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#481](https://paste.centos.org/view/73105f28 )
  * :question: upstream-pipeline [#[622]](https://paste.centos.org/view/e7a14b73 )
  * :heavy_check_mark: build-kiali [#[1001]](Log omitted)
  * :heavy_check_mark: install-maistra [#[1477]](Log omitted)
  * :heavy_check_mark: clean-environment [#[3585, 3587, 3588, 3583]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2128, 2124, 2127]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[1787, 1789]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[991]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[519]](https://paste.centos.org/view/023ca25b )
  * :question: run-kiali-ui-tests [#[8736, 8737, 8738, 8739, 8740, 8741, 8742, 8743, 8744, 8745, 8746, 8747, 8748, 8749, 8750, 8751, 8752]](https://paste.centos.org/view/9f48150c https://paste.centos.org/view/5475de15 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#489](https://paste.centos.org/view/e9fd021d )
  * :question: upstream-istio-pipeline [#[51]](https://paste.centos.org/view/98fab0de )
  * :heavy_check_mark: build-kiali [#[1125]](Log omitted)
  * :heavy_check_mark: install-istio [#[63]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4075, 4076, 4077, 4078]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2498, 2499, 2500]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2044, 2045]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1139]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[578]](https://paste.centos.org/view/c6a0d0be )
  * :red_circle: run-kiali-ui-tests [#[9739, 9740, 9741, 9742, 9743, 9744, 9745, 9746, 9747, 9748, 9749, 9750, 9751, 9752, 9753, 9754, 9755]](https://paste.centos.org/view/771aeb3f https://paste.centos.org/view/075965a1 https://paste.centos.org/view/a5b81f70 https://paste.centos.org/view/846f7b61 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#498](https://paste.centos.org/view/7519dffc )
  * :question: upstream-istio-pipeline [#[91]](https://paste.centos.org/view/709682cb )
  * :heavy_check_mark: build-kiali [#[1286]](Log omitted)
  * :heavy_check_mark: install-istio [#[135]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4641, 4650, 4651, 4652]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2904, 2901, 2902]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2286, 2287]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1283]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[655]](https://paste.centos.org/view/18030f61 )
  * :question: run-kiali-ui-tests [#[11040, 11041, 11042, 11043, 11044, 11045, 11046, 11047, 11048, 11032, 11033, 11034, 11035, 11036, 11037, 11038, 11039]](https://paste.centos.org/view/657ae8ea https://paste.centos.org/view/d13d9f7c )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#499](https://paste.centos.org/view/393ae03a )
  * :red_circle: upstream-istio-pipeline [#[97]](https://paste.centos.org/view/0acca03d )
  * :heavy_check_mark: build-kiali [#[1298]](Log omitted)
  * :red_circle: install-istio [#[146]](https://paste.centos.org/view/a327907f )

**Comment by hhovsepy** [comment]
PRT is broken, manual run of tests are failing because of other reasons.

**Pull request merged**
