### PR TITLE
login page support, added hard-coded credentials

### PR DESCRIPTION
**Pull request by jkandasa**
* log-in page added
* hard-coded credentials
* Another PR will be created to fetch credentials from yaml file

### CODE REVIEW

**Comment by hhovsepy** [comment]
is this a temporary solution with hardcoded credentials? because we have credentials in env.yaml

**Comment by hhovsepy** [comment]
ok

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: python-ui-test-pr [#54](https://paste.fedoraproject.org/paste/ZUOqpJtuW~c26BVvcxz-lA)
  * :red_circle: run-python-ui-tests [#353](https://paste.fedoraproject.org/paste/fH2n5PIxshU9BNVG3XzqJw)
--------------

**Comment by jkandasa** [comment]
@hhovsepy Yes, this is a temporary solution(only the hardcoded section) I have to add code to get credentials from env.yaml later.

**Comment by hhovsepy** [comment]
LGTM, thanks

**Comment by jkandasa** [comment]
@hhovsepy there is a failure, it is a test failure, not stable. I will fix that with another PR.

**Pull request merged**
