### PR TITLE
Added Routing Wizard tests to cover a basic scenarios.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#318](https://paste.fedoraproject.org/paste/mHTdQEZYmw52GPykEDCmhQ)
  * :question: Istio-and-Kiali-on-Openshift [#[3094]](https://paste.fedoraproject.org/paste/QwSBQUYQirjJh1BEgBUMTg)
  * :heavy_check_mark: Istio-Upstream [#[1761]](https://paste.fedoraproject.org/paste/0op7KIOdVxgGZYFQvshU0g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6353, 6354, 6355, 6356]](https://paste.fedoraproject.org/paste/LmW-YxRIgcCNTtuR72I4dA)
  * :heavy_check_mark: Kiali-on-Openshift [#[3768, 3767]](https://paste.fedoraproject.org/paste/1eh-KqSJFR5IaV525sNpkw)
  * :heavy_check_mark: install-bookinfo [#[2925, 2926]](https://paste.fedoraproject.org/paste/X2FYF-eRkSoxFEF9iMLjCA)
  * :red_circle: python-ui-tests-parallel [#[594]](https://paste.fedoraproject.org/paste/awp-i9b4GiJoaCDKX~uTFA)
  * :red_circle: run-python3-ui-tests [#[3072, 3073, 3074, 3075, 3076, 3077, 3078, 3068, 3069, 3070, 3071]](https://paste.fedoraproject.org/paste/fy4K-R3MeAgqXQwl8ay9mw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#319](https://paste.fedoraproject.org/paste/Ev4-Pgc34t~URrzLyoPzAg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[3095]](https://paste.fedoraproject.org/paste/P9rz-Jq-flJG3X2HEpfYkg)
  * :heavy_check_mark: Istio-Upstream [#[1762]](https://paste.fedoraproject.org/paste/aBXZmTKbOF6S96MW7t-0uA)
  * :red_circle: Kiali-Istio-Checker [#[6360, 6358, 6359]](https://paste.fedoraproject.org/paste/C14rPN3AdVCTWdSBaClMAw)
  * :red_circle: Kiali-on-Openshift [#[3771, 3772]](https://paste.fedoraproject.org/paste/jPjFSpiRbMnlSro~1~V8yw)
  * :red_circle: install-bookinfo [#[2928, 2927]](https://paste.fedoraproject.org/paste/JqxCcrml2FqTTjbjT~6~UQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#320](https://paste.fedoraproject.org/paste/fV6Zc12p9vnXjneNsZRz7A)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[3099]](https://paste.fedoraproject.org/paste/WmcvHwjrMlBB3L8cMdgzMA)
  * :heavy_check_mark: Istio-Upstream [#[1766]](https://paste.fedoraproject.org/paste/HoS2HtLCjeng2t0UVPsnOg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6370, 6371, 6372, 6373]](https://paste.fedoraproject.org/paste/1UMhh-t5uqStqqK9xF3lvw)
  * :heavy_check_mark: Kiali-on-Openshift [#[3779, 3780]](https://paste.fedoraproject.org/paste/kfLJTOSPQAOGaWYMlgxARw)
  * :heavy_check_mark: install-bookinfo [#[2932, 2933]](https://paste.fedoraproject.org/paste/I4c4z~TZIUSxbbAyHpA1-Q)
  * :heavy_check_mark: python-ui-tests-parallel [#[595]](https://paste.fedoraproject.org/paste/eFvWrK4hAQXp~7uyZSOQfQ)
  * :heavy_check_mark: run-python3-ui-tests [#[3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089]](https://paste.fedoraproject.org/paste/tfqDHQzidsY22zyaxyccLw)

**Pull request merged**
