### PR TITLE
Overview REST results filtered.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#687](https://paste.centos.org/view/9f65a28d )
  * :question: upstream-istio-pipeline [#[917]](https://paste.centos.org/view/8e2265dd )
  * :heavy_check_mark: build-kiali [#[3729]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1162]](Log omitted)
  * :heavy_check_mark: install-istio [#[1956]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14899, 14900, 14901, 14902]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10731, 10732, 10733, 10734]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8016, 8014, 8015]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2099]](https://paste.centos.org/view/2f3f798e )
  * :question: run-kiali-ui-tests [#[35907, 35908, 35909, 35910, 35911, 35912, 35913, 35914, 35915, 35916, 35917, 35918, 35919, 35920, 35921, 35922, 35923]](https://paste.centos.org/view/5fa44580 https://paste.centos.org/view/05230e6c https://paste.centos.org/view/5d60c3a6 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#690](https://paste.centos.org/view/7117c498 )
  * :question: upstream-istio-pipeline [#[931]](https://paste.centos.org/view/7066eab5 )
  * :heavy_check_mark: build-kiali [#[3749]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1175]](Log omitted)
  * :heavy_check_mark: install-istio [#[1972]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14996, 14997, 14998, 14999]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10818, 10819, 10820, 10821]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8096, 8097, 8098]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2115]](https://paste.centos.org/view/268da916 )
  * :question: run-kiali-ui-tests [#[36192, 36193, 36194, 36195, 36196, 36180, 36181, 36182, 36183, 36184, 36185, 36186, 36187, 36188, 36189, 36190, 36191]](https://paste.centos.org/view/ec9f0e31 https://paste.centos.org/view/71528b88 https://paste.centos.org/view/c0a50046 https://paste.centos.org/view/a60c82ad )

**Pull request merged**
