### PR TITLE
Workload filter tests to assert_all_items

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#691](https://paste.centos.org/view/9eee777b )
  * :question: upstream-istio-pipeline [#[933]](https://paste.centos.org/view/f70919eb )
  * :heavy_check_mark: build-kiali [#[3752]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1178]](Log omitted)
  * :heavy_check_mark: install-istio [#[1976]](Log omitted)
  * :heavy_check_mark: clean-environment [#[15008, 15009, 15006, 15007]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10826, 10827, 10828, 10829]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8104, 8105, 8103]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2116]](https://paste.centos.org/view/1307227b )
  * :question: run-kiali-ui-tests [#[36197, 36198, 36199, 36200, 36201, 36202, 36203, 36204, 36205, 36206, 36207, 36208, 36209, 36210, 36211, 36212, 36213]](https://paste.centos.org/view/720961bc https://paste.centos.org/view/4021ae8d https://paste.centos.org/view/c8875421 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#692](https://paste.centos.org/view/62b8acc1 )
  * :question: upstream-istio-pipeline [#[935]](https://paste.centos.org/view/84b6f7ab )
  * :heavy_check_mark: build-kiali [#[3754]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1179]](Log omitted)
  * :heavy_check_mark: install-istio [#[1980]](Log omitted)
  * :heavy_check_mark: clean-environment [#[15016, 15017, 15018, 15019]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10840, 10841, 10838, 10839]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8112, 8113, 8111]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2118]](https://paste.centos.org/view/29649a91 )
  * :question: run-kiali-ui-tests [#[36232, 36233, 36234, 36235, 36236, 36237, 36238, 36239, 36240, 36241, 36242, 36243, 36244, 36245, 36246, 36247, 36248]](https://paste.centos.org/view/76bf7d41 https://paste.centos.org/view/945fda9e https://paste.centos.org/view/c717fdbb )

**Pull request merged**
