### PR TITLE
Added more MTLS cases fro port lavel mTLS

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#693](https://paste.centos.org/view/c90e3c51 )
  * :red_circle: upstream-istio-pipeline [#[945]](https://paste.centos.org/view/e824c373 )
  * :heavy_check_mark: build-kiali [#[3763]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1184]](Log omitted)
  * :red_circle: install-istio [#[1996]](https://paste.centos.org/view/99454500 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#694](https://paste.centos.org/view/5d5e1f83 )
  * :question: upstream-istio-pipeline [#[946]](https://paste.centos.org/view/3d30d71e )
  * :heavy_check_mark: build-kiali [#[3764]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1185]](Log omitted)
  * :heavy_check_mark: install-istio [#[1997]](Log omitted)
  * :heavy_check_mark: clean-environment [#[15066, 15067, 15068, 15069]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10888, 10889, 10890, 10891]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8161, 8162, 8163]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2125]](https://paste.centos.org/view/198c3a71 )
  * :question: run-kiali-ui-tests [#[36352, 36353, 36354, 36355, 36356, 36357, 36358, 36359, 36360, 36361, 36362, 36363, 36364, 36365, 36366, 36367, 36351]](https://paste.centos.org/view/4a7ea4bc https://paste.centos.org/view/231ff1ab https://paste.centos.org/view/eeef4603 https://paste.centos.org/view/5bd2019f )

**Pull request merged**
