### PR TITLE
Added Workload page istio_config clicking.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#657](https://paste.centos.org/view/99f5b42b )
  * :question: upstream-istio-pipeline [#[784]](https://paste.centos.org/view/f78ad7d1 )
  * :heavy_check_mark: build-kiali [#[3400]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[955]](Log omitted)
  * :heavy_check_mark: install-istio [#[1733]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13024, 13022, 13023]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9108, 9109, 9110]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6565, 6566]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1881]](https://paste.centos.org/view/1a2e20d0 )
  * :question: run-kiali-ui-tests [#[32000, 32001, 32002, 32003, 32004, 32005, 32006, 32007, 32008, 32009, 32010, 31994, 31995, 31996, 31997, 31998, 31999]](https://paste.centos.org/view/25b224f2 https://paste.centos.org/view/53a0b67e )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
