### PR TITLE
Added more tests for mTLS checking

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#289](https://paste.fedoraproject.org/paste/wvsRqzl4hIpI5vZFmsmedg)
  * :question: Istio-and-Kiali-on-Openshift [#[2861]](https://paste.fedoraproject.org/paste/Yvo0JHWlP38J-PQJdBt0Lw)
  * :heavy_check_mark: Kiali-on-Openshift [#[3296, 3295]](https://paste.fedoraproject.org/paste/kuCtzcHWwG2x5tPEV1BvGA)
  * :heavy_check_mark: Istio-Upstream [#[1532]](https://paste.fedoraproject.org/paste/VsSnGe1J6KPFkvfNgfUvSQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5572, 5573, 5574, 5575]](https://paste.fedoraproject.org/paste/xEJOGnFkv-Pd8fq6mcDK~w)
  * :heavy_check_mark: install-bookinfo [#[2665, 2666]](https://paste.fedoraproject.org/paste/F1yIVf2Xvpa2JzGjoajX9Q)
  * :question: python-ui-tests-parallel [#[538]](https://paste.fedoraproject.org/paste/K1fYUWKr9I5mciAdvqO0FA)
  * :question: run-python3-ui-tests [#[2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462]](https://paste.fedoraproject.org/paste/-HqsuNsmicEXflLvuZ6cNg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#290](https://paste.fedoraproject.org/paste/v3OVr-XQzqG7N0c6Uj1Ufw)
  * :question: Istio-and-Kiali-on-Openshift [#[2868]](https://paste.fedoraproject.org/paste/81rAn6etTZOCcV33etQung)
  * :heavy_check_mark: Istio-Upstream [#[1539]](https://paste.fedoraproject.org/paste/D3tOWMipP6ivbnkoPAd43A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5601, 5603, 5604, 5605]](https://paste.fedoraproject.org/paste/oy1~5JmY9ALLqzEIjgPOuw)
  * :heavy_check_mark: Kiali-on-Openshift [#[3315, 3316]](https://paste.fedoraproject.org/paste/u4l3P14So7Xuk-Xlfhw6PQ)
  * :heavy_check_mark: install-bookinfo [#[2674, 2675]](https://paste.fedoraproject.org/paste/-xE9zGcdTn0xLmZo9ofIwQ)
  * :question: python-ui-tests-parallel [#[541]](https://paste.fedoraproject.org/paste/IVYk0mWCJB7WoReddbBb~w)
  * :question: run-python3-ui-tests [#[2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495]](https://paste.fedoraproject.org/paste/mBk8exkXpaYS-Xvh99f-Rw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#291](https://paste.fedoraproject.org/paste/r6PhCOVDZkOBNvcJAdZDJg)
  * :question: Istio-and-Kiali-on-Openshift [#[2869]](https://paste.fedoraproject.org/paste/I2TWumj~-gi9vaqPSrb1CA)
  * :heavy_check_mark: Istio-Upstream [#[1540]](https://paste.fedoraproject.org/paste/NlFurKG5dI7dfjjI6NCG7g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5608, 5610, 5611, 5607]](https://paste.fedoraproject.org/paste/Uqq2BcRnSy7kRCMR0uvT5Q)
  * :heavy_check_mark: Kiali-on-Openshift [#[3320, 3318]](https://paste.fedoraproject.org/paste/cQ6KAWc-u~nP0FhbZoZHtQ)
  * :heavy_check_mark: install-bookinfo [#[2676, 2677]](https://paste.fedoraproject.org/paste/hSX-GYNJd9zmfFNo3LcbLA)
  * :question: python-ui-tests-parallel [#[542]](https://paste.fedoraproject.org/paste/E98UTueO3sYbb7o6Huu71g)
  * :question: run-python3-ui-tests [#[2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506]](https://paste.fedoraproject.org/paste/VAe-AuayunkiDCuUShlS7Q)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#294](https://paste.fedoraproject.org/paste/Nv51iqh--xtixtcMZosOOg)
  * :question: Istio-and-Kiali-on-Openshift [#[2895]](https://paste.fedoraproject.org/paste/Y5J0Trm1Aw-hnlxcgcjmKA)
  * :heavy_check_mark: Istio-Upstream [#[1565]](https://paste.fedoraproject.org/paste/YVyvKop~fpZPsEMCSn9NhA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5728, 5722, 5730, 5725]](https://paste.fedoraproject.org/paste/EmoAY4XHebvOPzhA2-GWhQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3386, 3383]](https://paste.fedoraproject.org/paste/CaM0AMHuRjrFFZyZx6XlgQ)
  * :heavy_check_mark: install-bookinfo [#[2712, 2713]](https://paste.fedoraproject.org/paste/R4GY2Km3fu1UZt3IbpawQA)
  * :question: python-ui-tests-parallel [#[551]](https://paste.fedoraproject.org/paste/t3fZiMbvSyGX6semUt3WVA)
  * :question: run-python3-ui-tests [#[2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2605]](https://paste.fedoraproject.org/paste/HpwmNm0jVQhYNjuG8FgAYw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#296](https://paste.fedoraproject.org/paste/9rfjeOz~cdN8lLzbFrNxGQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2896]](https://paste.fedoraproject.org/paste/1vySmsi65qtzLzf5fqlsUg)
  * :heavy_check_mark: Istio-Upstream [#[1567]](https://paste.fedoraproject.org/paste/ODQCiVwx~-H7-V22CTdUCg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5731, 5732, 5733, 5734]](https://paste.fedoraproject.org/paste/tt35MgLvp-T2lo3oyXqjuQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3387, 3388]](https://paste.fedoraproject.org/paste/~UXjl8aCft2aHTexRQLMQg)
  * :heavy_check_mark: install-bookinfo [#[2714, 2715]](https://paste.fedoraproject.org/paste/MhjoE58eqHTojwGJ4TFwjA)
  * :heavy_check_mark: python-ui-tests-parallel [#[552]](https://paste.fedoraproject.org/paste/YiDTySmQYBJIVZ1Rc-RYvQ)
  * :heavy_check_mark: run-python3-ui-tests [#[2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616]](https://paste.fedoraproject.org/paste/TQFPKmcUNr-aivfe0W0qtA)

**Pull request merged**
