### PR TITLE
Added missing error and warning message check tests

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#504](https://paste.centos.org/view/db2c530a )
  * :question: upstream-istio-pipeline [#[121]](https://paste.centos.org/view/fc79b43e )
  * :heavy_check_mark: build-kiali [#[1406]](Log omitted)
  * :heavy_check_mark: install-istio [#[193]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5072, 5073, 5069, 5071]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3218, 3220, 3221]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2494, 2495]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1402]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[726]](https://paste.centos.org/view/46d9e4d4 )
  * :question: run-kiali-ui-tests [#[12256, 12240, 12241, 12242, 12243, 12244, 12245, 12246, 12247, 12248, 12249, 12250, 12251, 12252, 12253, 12254, 12255]](https://paste.centos.org/view/f656219b )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#505](https://paste.centos.org/view/bc4a3d56 )
  * :red_circle: upstream-istio-pipeline [#[123]](https://paste.centos.org/view/8a23bd84 )
  * :heavy_check_mark: build-kiali [#[1414]](Log omitted)
  * :heavy_check_mark: install-istio [#[196]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5091, 5092, 5094, 5095]](Log omitted)
  * :red_circle: istio-kiali-mesh-checker [#[3237, 3238, 3239]](https://paste.centos.org/view/f1e9551a )
  * :red_circle: install-bookinfo [#[2505, 2506]](https://paste.centos.org/view/f9f05aa0 )
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1409]](Log omitted)

**Pull request merged**
