### PR TITLE
Namespace selector is changed.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#331](https://paste.fedoraproject.org/paste/S~0m1jG88KXzlbzv1yxazQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[3159]](https://paste.fedoraproject.org/paste/KxWHAO9wp6iEKT-6OluTjw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#332](https://paste.fedoraproject.org/paste/yH9WvxbZpuyB-26B3dkesw)
  * :question: Istio-and-Kiali-on-Openshift [#[3160]](https://paste.fedoraproject.org/paste/MicgdIQ6wNfdMxB1BKKXLA)
  * :heavy_check_mark: Istio-Upstream [#[1826]](https://paste.fedoraproject.org/paste/7eED499XhHdVlegOxjbvCw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6602, 6603, 6604, 6598]](https://paste.fedoraproject.org/paste/0k842Tk3sO-QAmAV12V2fQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3922, 3925]](https://paste.fedoraproject.org/paste/yRwirymxmh3bCPrIlktO3Q)
  * :heavy_check_mark: install-bookinfo [#[3016, 3015]](https://paste.fedoraproject.org/paste/cNzCo6n340ODwFfyd3Qruw)
  * :question: python-ui-tests-parallel [#[618]](https://paste.fedoraproject.org/paste/TMcXZtCoStqZWtUf-1HRpQ)
  * :question: run-python3-ui-tests [#[3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344]](https://paste.fedoraproject.org/paste/EKfas~HoXU1J8E4veRHBeA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#333](https://paste.fedoraproject.org/paste/BavFkvVe4Nb9lwNSzDNQXQ)
  * :question: Istio-and-Kiali-on-Openshift [#[3188]](https://paste.fedoraproject.org/paste/Et0YheEwm826Tr8ky73HCg)
  * :heavy_check_mark: Istio-Upstream [#[1854]](https://paste.fedoraproject.org/paste/m1omMy7DFl1tduWScmSwUA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6697, 6698, 6699, 6700]](https://paste.fedoraproject.org/paste/Dmf4iSNyU9JRJZyaL0Itng)
  * :heavy_check_mark: Kiali-on-Openshift [#[3986, 3987]](https://paste.fedoraproject.org/paste/b9Ge~XaDbxc1MVtBVL2U0Q)
  * :heavy_check_mark: install-bookinfo [#[3048, 3049]](https://paste.fedoraproject.org/paste/4AbEubOiXegr3eCEGIPRWw)
  * :question: python-ui-tests-parallel [#[624]](https://paste.fedoraproject.org/paste/GhlHkCVznRfksx9LBeyZFA)
  * :question: run-python3-ui-tests [#[3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410]](https://paste.fedoraproject.org/paste/lKQj-Jxsd3o~7NcsNhM33Q)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#334](https://paste.fedoraproject.org/paste/9BYp82IxWlqAUkPqNM6jsg)
  * :question: Istio-and-Kiali-on-Openshift [#[3202]](https://paste.fedoraproject.org/paste/xcoVFhbHlv6yZjNobj3Yaw)
  * :heavy_check_mark: Istio-Upstream [#[1866]](https://paste.fedoraproject.org/paste/Z4aQwfECqdTYMLDQOkRPOg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6740, 6741, 6742, 6743]](https://paste.fedoraproject.org/paste/9fHTCQ5x9pznZganBhwpuA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4016, 4014]](https://paste.fedoraproject.org/paste/5vZ1CL1-Q8D2BlBCvHF4oQ)
  * :heavy_check_mark: install-bookinfo [#[3062, 3063]](https://paste.fedoraproject.org/paste/TIVXBb60lm5xyRD41wCGwA)
  * :question: python-ui-tests-parallel [#[626]](https://paste.fedoraproject.org/paste/ChMgAkmyRjWPHnZeBAmxMw)
  * :question: run-python3-ui-tests [#[3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3422, 3423]](https://paste.fedoraproject.org/paste/QoBcRPjUYs3jDqaZPgvG9w)

**Comment by hhovsepy** [comment]
It seems there is some REST call issue.
Otherwise PF4 works for Namespace selector:

https://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8443/job/python-ui-tests-parallel/626/testReport/

**Pull request merged**
