### PR TITLE
Added support of 4 new Istio Objects

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#77](https://paste.fedoraproject.org/paste/QPVllAE1skPxWjY2YSEASA)
  * :red_circle: run-python-ui-tests [#443](https://paste.fedoraproject.org/paste/3L7EGoHoR-jMtOTdAhcS3w)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#78](https://paste.fedoraproject.org/paste/tKQsFjbbJGDyahJwiryMJg)
  * :red_circle: run-python-ui-tests [#444](https://paste.fedoraproject.org/paste/cADuNk~W4YmmA-5rRVaA2A)

**Comment by hhovsepy** [comment]
failures are not related to tests, merging

**Pull request merged**
