### PR TITLE
Added checks for Gateway link in VS.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#438](https://paste.fedoraproject.org/paste/PFijmSrTU~~1SsTNA4NJaQ)
  * :question: upstream-pipeline [#[404]](https://paste.fedoraproject.org/paste/exSwEGxRSPS86rFuUiY25Q)
  * :heavy_check_mark: build-kiali [#[660]](https://paste.fedoraproject.org/paste/KH69nMDewlY4Zaa4HkdXGg)
  * :heavy_check_mark: install-maistra [#[1180]](https://paste.fedoraproject.org/paste/NVyxpKLKAU6pF3Y2tm6mGA)
  * :heavy_check_mark: clean-environment [#[2608, 2609, 2610, 2611]](https://paste.fedoraproject.org/paste/QddqneSJ5I2Gdt6fvjSDmw)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1384, 1385, 1386]](https://paste.fedoraproject.org/paste/PjsN6c7p-6ylT218GG2tlA)
  * :heavy_check_mark: install-bookinfo [#[1315, 1316]](https://paste.fedoraproject.org/paste/lnHElXQtnAKT4~TTlasjJQ)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[720]](https://paste.fedoraproject.org/paste/b6ACWQwPScPQNzT6aPGV~w)
  * :question: run-kiali-ui-tests-parallel [#[315]](https://paste.fedoraproject.org/paste/nAtch8Vj9qdu6xm0d5cfQA)
  * :question: run-kiali-ui-tests [#[5257, 5258, 5259, 5260, 5261, 5262, 5263, 5264, 5265, 5266, 5267, 5268, 5269, 5270, 5271, 5272, 5273]](https://paste.fedoraproject.org/paste/nYXnqsA7JeJkNPfP75trSA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
test_virtual_service is passing

**Pull request merged**
