### PR TITLE
Added filter by 2 names tests for all items.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#528](https://paste.centos.org/view/e6d15db7 )
 :red_circle: PRT Failed, Please Contact QE

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#529](https://paste.centos.org/view/2095119e )
  * :question: upstream-pipeline [#[984]](https://paste.centos.org/view/5738315a )
  * :heavy_check_mark: build-kiali [#[1845]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[10]](Log omitted)
  * :heavy_check_mark: install-maistra [#[1944]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7032, 7029, 7030, 7031]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4656, 4654, 4655]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3440, 3439]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1960]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[987]](https://paste.centos.org/view/8fea20eb )
  * :question: run-kiali-ui-tests [#[16652, 16653, 16654, 16655, 16656, 16657, 16658, 16659, 16660, 16661, 16662, 16663, 16664, 16665, 16666, 16667, 16668]](https://paste.centos.org/view/6a330cd8 )

**Pull request merged**
