### PR TITLE
Fixed failing Source Workloads numbers

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#189](https://paste.fedoraproject.org/paste/jiBjhy1b62-2bWJ-4OtBLg)
  * :question: Istio-and-Kiali-on-Openshift [#[2130]](https://paste.fedoraproject.org/paste/ccFLX2IpKn-zUFF8wrFE4Q)
  * :heavy_check_mark: Istio-Upstream [#[876]](https://paste.fedoraproject.org/paste/8haqsqeuD4pZfwE29UQ0Uw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2780, 2782]](https://paste.fedoraproject.org/paste/3mwsdc7Ey2yT0vAfeFLXeg)
  * :heavy_check_mark: install-bookinfo [#[1548, 1549]](https://paste.fedoraproject.org/paste/Gn8u1lnJeAq0JeoNDVD6Cw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1477]](https://paste.fedoraproject.org/paste/GLvkxwlcd2aYVCvVTMNuPg)
  * :question: python-ui-tests-parallel [#[247]](https://paste.fedoraproject.org/paste/kYGqwdXxk-LFTtbEJIxOxg)
  * :question: run-python-ui-tests [#[3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375]](https://paste.fedoraproject.org/paste/9NTyt6vjv1~i7bX2aQfEtQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#190](https://paste.fedoraproject.org/paste/3KVKvNidhe-X0cj3fM5NxQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2131]](https://paste.fedoraproject.org/paste/sL6PeCgy8KjQB9ktPqRUHw)
  * :heavy_check_mark: Istio-Upstream [#[877]](https://paste.fedoraproject.org/paste/7WGjmTVCtPPC824eF9Dkiw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2784, 2783]](https://paste.fedoraproject.org/paste/SvaA7LUANdXHKVWEMz6lVw)
  * :heavy_check_mark: install-bookinfo [#[1550, 1551]](https://paste.fedoraproject.org/paste/Iex03UjzWQYGIlPokisAiA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1478]](https://paste.fedoraproject.org/paste/CdWHA4VYjcSPYrBVUdBIyw)
  * :red_circle: python-ui-tests-parallel [#[248]](https://paste.fedoraproject.org/paste/iiFNG2bVDIWOX~BJCLofZA)
  * :red_circle: run-python-ui-tests [#[3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386]](https://paste.fedoraproject.org/paste/CXQsNqlmrRKQ8A7uNrdQoQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Pull request merged**
