### PR TITLE
Traffic tab content automation for App, Workloads and Services.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#425](https://paste.fedoraproject.org/paste/2uhweccc5SRJ~QNO5bSw6Q)
  * :red_circle: upstream-pipeline [#[331]](https://paste.fedoraproject.org/paste/FlzvuVcqrQzpT43mS28crA)
  * :red_circle: install-maistra [#[1081]](https://paste.fedoraproject.org/paste/7D6HWUzIs6FRcMhwbgrt3w)
  * :heavy_check_mark: clean-environment [#[2293]](https://paste.fedoraproject.org/paste/AX39Tkozz7g-sA2J5H9U-A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#426](https://paste.fedoraproject.org/paste/vbSz4em6xBpKSU1peaTNCw)
  * :question: upstream-pipeline [#[332]](https://paste.fedoraproject.org/paste/yLeMhk~EdP-qOjwb9BL9ZA)
  * :heavy_check_mark: install-maistra [#[1082]](https://paste.fedoraproject.org/paste/ytsch2kuvi1ahqqtu5whag)
  * :heavy_check_mark: clean-environment [#[2296, 2297, 2294, 2295]](https://paste.fedoraproject.org/paste/kkYP5ktEsOJB4azhkAVoFQ)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1144, 1145, 1146]](https://paste.fedoraproject.org/paste/p--ZWxyLJR7BS4Wcg2Kv1Q)
  * :heavy_check_mark: install-bookinfo [#[1160, 1161]](https://paste.fedoraproject.org/paste/Th0ebb~iQRS16-IlGd3-Sg)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[633]](https://paste.fedoraproject.org/paste/zCPXqTDsbT2yuKmgiBr3OQ)
  * :question: run-kiali-ui-tests-parallel [#[257]](https://paste.fedoraproject.org/paste/mODbHPVNrsAGEYf9Z8nCWA)
  * :question: run-kiali-ui-tests [#[4288, 4289, 4290, 4291, 4292, 4293, 4277, 4278, 4279, 4280, 4281, 4282, 4283, 4284, 4285, 4286, 4287]](https://paste.fedoraproject.org/paste/EwPakxJ9nyE5bfGDf1V2mA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#429](https://paste.fedoraproject.org/paste/YrKCNA1gPtzRyAGJ7l2VvA)
  * :question: upstream-pipeline [#[349]](https://paste.fedoraproject.org/paste/m5n5tnw8ct9PXmI5U019jg)
  * :heavy_check_mark: install-maistra [#[1100]](https://paste.fedoraproject.org/paste/TikU8t4ycr5uX94uVAJ-qg)
  * :heavy_check_mark: clean-environment [#[2362, 2363, 2364, 2365]](https://paste.fedoraproject.org/paste/5KzrnVoVIFkh~eeBokvT-A)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1196, 1197, 1198]](https://paste.fedoraproject.org/paste/tuipWEQCJpxajG6KU4gX2Q)
  * :heavy_check_mark: install-bookinfo [#[1194, 1195]](https://paste.fedoraproject.org/paste/iIse52BLiVee-aZR1jaPCw)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[649]](https://paste.fedoraproject.org/paste/t9z2glelBBfXKPbIE4KYag)
  * :question: run-kiali-ui-tests-parallel [#[271]](https://paste.fedoraproject.org/paste/1SeOIprNrcJNUxFy4XFXIg)
  * :question: run-kiali-ui-tests [#[4514, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4523, 4525, 4526, 4527, 4528, 4529, 4530, 4531]](https://paste.fedoraproject.org/paste/CuBgFnLDygIgETolKBwx7g)

**Comment by hhovsepy** [comment]
Failures are not related to added checks.

**Pull request merged**
