### PR TITLE
Added validtion for Workload Istio Config tab.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#619](https://paste.centos.org/view/40b67d06 )
  * :question: upstream-istio-pipeline [#[656]](https://paste.centos.org/view/7039276d )
  * :heavy_check_mark: build-kiali [#[2845]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[611]](Log omitted)
  * :heavy_check_mark: install-istio [#[1386]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10483, 10484, 10485]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7137, 7138, 7139]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5046, 5047]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1550]](https://paste.centos.org/view/bd214198 )
  * :question: run-kiali-ui-tests [#[26240, 26241, 26242, 26243, 26244, 26245, 26246, 26230, 26231, 26232, 26233, 26234, 26235, 26236, 26237, 26238, 26239]](https://paste.centos.org/view/62300ba8 https://paste.centos.org/view/fb19c64d https://paste.centos.org/view/aaaf561d https://paste.centos.org/view/457c64a6 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#620](https://paste.centos.org/view/0a74ac9b )
  * :question: upstream-istio-pipeline [#[657]](https://paste.centos.org/view/02e8c665 )
  * :heavy_check_mark: build-kiali [#[2848]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[612]](Log omitted)
  * :heavy_check_mark: install-istio [#[1389]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10497, 10498, 10499]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7145, 7146, 7147]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5051, 5052]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1552]](https://paste.centos.org/view/f2bb6d50 )
  * :red_circle: run-kiali-ui-tests [#[26247, 26248, 26249, 26250, 26251, 26252, 26253, 26254, 26255, 26256, 26257, 26258, 26259, 26260, 26261, 26262, 26263]](https://paste.centos.org/view/adbb54a8 https://paste.centos.org/view/667c2209 )

**Pull request merged**
