### PR TITLE
Fixed failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#335](https://paste.fedoraproject.org/paste/Sc~u28MncQeM4WYIxuezKw)
  * :question: Istio-and-Kiali-on-Openshift [#[3211]](https://paste.fedoraproject.org/paste/DxZC6uuJgxLiblJZJ9ufiA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4037, 4038]](https://paste.fedoraproject.org/paste/088Y4D9b21IIim8GLI7Raw)
  * :heavy_check_mark: Istio-Upstream [#[1875]](https://paste.fedoraproject.org/paste/OFekmLPO0QU~CXNngSSQlA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6777, 6778, 6779, 6780]](https://paste.fedoraproject.org/paste/S8MkYCmM7CFTlAQCfNmXZw)
  * :heavy_check_mark: install-bookinfo [#[3075, 3076]](https://paste.fedoraproject.org/paste/iMIuOXJyJ5tH-Yc1lXeZaQ)
  * :question: python-ui-tests-parallel [#[629]](https://paste.fedoraproject.org/paste/B68ur0NRS8Z3dtO5rY1rBw)
  * :question: run-python3-ui-tests [#[3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3455]](https://paste.fedoraproject.org/paste/9gZrP9urqsvZQCZCoa7EUA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#336](https://paste.fedoraproject.org/paste/v1F1eZCkV9RAjxgal9nx3Q)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#337](https://paste.fedoraproject.org/paste/1IQ2YilHrfAqPjBYPIdksQ)
  * :question: Istio-and-Kiali-on-Openshift [#[3213]](https://paste.fedoraproject.org/paste/61RGp9p2wtZxBc4KtexIqA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4042, 4043]](https://paste.fedoraproject.org/paste/StuZ15KoILCo3-xJfksXBg)
  * :heavy_check_mark: Istio-Upstream [#[1877]](https://paste.fedoraproject.org/paste/LUFoKGw2WYmbTvQZ09jl6w)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6784, 6785, 6786, 6787]](https://paste.fedoraproject.org/paste/6ssMef6gJ0l-VcN3a7lMAw)
  * :heavy_check_mark: install-bookinfo [#[3080, 3079]](https://paste.fedoraproject.org/paste/tnRUdRPULqbqi8BuMM2zag)
  * :question: python-ui-tests-parallel [#[630]](https://paste.fedoraproject.org/paste/1Ur4E1l85BVykXro2Zq2fQ)
  * :question: run-python3-ui-tests [#[3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476]](https://paste.fedoraproject.org/paste/VnuqWmp0UnN965LaC-WgJQ)

**Comment by hhovsepy** [comment]
Failing tests are due to:
https://issues.jboss.org/browse/KIALI-2767
https://issues.jboss.org/browse/KIALI-2762

**Pull request merged**
