### PR TITLE
Added more checks for Advanced Options in routing wizard.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#380](https://paste.fedoraproject.org/paste/HPhVxGb622CifcUP1pF3IA)
  * :question: Istio-and-Kiali-on-Openshift [#[182]](https://paste.fedoraproject.org/paste/dvJ92~U~z0HMtPWq4-5low)
  * :heavy_check_mark: Istio-Upstream [#[2131]](https://paste.fedoraproject.org/paste/GuVb-AdpWNGfIsxeNyoGBA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7704, 7703]](https://paste.fedoraproject.org/paste/pslttzqfRF6T3Yx5pbX-DQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[564, 565]](https://paste.fedoraproject.org/paste/l7irRf9iLxiRQjkgxxW4pQ)
  * :heavy_check_mark: old-bookinfo [#[3338]](https://paste.fedoraproject.org/paste/TlZvYJO7S~RQuBdA~6dPQA)
  * :question: python-ui-tests-parallel [#[748]](https://paste.fedoraproject.org/paste/7kNkF~yj0913IwAv2rF2kw)
  * :question: run-python3-ui-tests [#[4787, 4788, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797]](https://paste.fedoraproject.org/paste/8GSZ5INea7o~sEXFXfGI0w)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#381](https://paste.fedoraproject.org/paste/YlCYWGI7zUhyRnet5Yuncg)
  * :question: Istio-and-Kiali-on-Openshift [#[184]](https://paste.fedoraproject.org/paste/hV4y0pxzm2ouW3A1~fRntQ)
  * :heavy_check_mark: Istio-Upstream [#[2133]](https://paste.fedoraproject.org/paste/9THNlJH3vIA2zWx4LlE1-g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7708, 7709]](https://paste.fedoraproject.org/paste/OXvj~p8nUl-EC30k3XphpA)
  * :heavy_check_mark: Kiali-on-Openshift [#[569, 570]](https://paste.fedoraproject.org/paste/W967JKxV9n3PqQ6-zfzOnA)
  * :heavy_check_mark: old-bookinfo [#[3340]](https://paste.fedoraproject.org/paste/jZWr9N0Waixa8G4nR4uM~w)
  * :question: python-ui-tests-parallel [#[750]](https://paste.fedoraproject.org/paste/ArcI8ySm8xdaNo~piP2y9g)
  * :question: run-python3-ui-tests [#[4809, 4810, 4811, 4812, 4813, 4814, 4815, 4816, 4817, 4818, 4819]](https://paste.fedoraproject.org/paste/MRZEE14s6ypMjc4v4GHBuw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#382](https://paste.fedoraproject.org/paste/oSeIt-W2J~VA~cOyzu~Lcw)
  * :question: Istio-and-Kiali-on-Openshift [#[185]](https://paste.fedoraproject.org/paste/GYBcrx0L35C821O0zdMJgA)
  * :heavy_check_mark: Istio-Upstream [#[2134]](https://paste.fedoraproject.org/paste/Sh7WShuYsPSOsiz9~rceSA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7712, 7713]](https://paste.fedoraproject.org/paste/hzlxeVu3ky3d16SQeuhvWA)
  * :heavy_check_mark: Kiali-on-Openshift [#[574, 575]](https://paste.fedoraproject.org/paste/RhT65D9GrdDTFzXCxmupmw)
  * :heavy_check_mark: old-bookinfo [#[3341]](https://paste.fedoraproject.org/paste/RrEN9GoKbF1pbo0c0gKYUQ)
  * :question: python-ui-tests-parallel [#[751]](https://paste.fedoraproject.org/paste/NugA4AcZVgLuB8CnG9q~4g)
  * :question: run-python3-ui-tests [#[4820, 4821, 4822, 4823, 4824, 4825, 4826, 4827, 4828, 4829, 4830]](https://paste.fedoraproject.org/paste/ipgEmu4xJzxdF0O3o8UnXg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#384](https://paste.fedoraproject.org/paste/tzqHp-GwS3lOCYv1OxRr8g)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[188]](https://paste.fedoraproject.org/paste/rxVRdT4cnSIxocRyTBIQmw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#385](https://paste.fedoraproject.org/paste/G2zl1J~MGbt6xHt1X~xrXw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[189]](https://paste.fedoraproject.org/paste/PLDiPwwF-Xf5Hyra7~7mdw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#386](https://paste.fedoraproject.org/paste/OVoff2Z6wqU5W47GBhEeRw)
  * :question: Istio-and-Kiali-on-Openshift [#[190]](https://paste.fedoraproject.org/paste/eLyDFLDQSE-IuVNchdfGsA)
  * :heavy_check_mark: Istio-Upstream [#[2137]](https://paste.fedoraproject.org/paste/0iTUZYG-Ri0hRdtGCypCSQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7721, 7722]](https://paste.fedoraproject.org/paste/BiMH2Z~Y2pyY79IJKCxHJw)
  * :heavy_check_mark: Kiali-on-Openshift [#[582, 583]](https://paste.fedoraproject.org/paste/POlu6r40IwtsdBW200e3wQ)
  * :heavy_check_mark: install-bookinfo [#[160, 161]](https://paste.fedoraproject.org/paste/ZyWo5UD4itH9iUzcJe1XCA)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[43]](https://paste.fedoraproject.org/paste/d8rs4Zyy8DaFtRF6NM7Z7Q)
  * :heavy_check_mark: clean-environment [#[192, 193, 194]](https://paste.fedoraproject.org/paste/PBVlg3j4Y4Vk3ehvu2Mu9A)
  * :question: python-ui-tests-parallel [#[754]](https://paste.fedoraproject.org/paste/Uz1qKgXVpY~Tn-A4joRIuQ)
  * :black_circle: run-python3-ui-tests [#[4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860, 4861, 4862, 4863]](https://paste.fedoraproject.org/paste/S8QSB4cqy6atC1y95Hkbuw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#387](https://paste.fedoraproject.org/paste/3lHYrDh2emSdklRt0f4DJw)
  * :question: Istio-and-Kiali-on-Openshift [#[191]](https://paste.fedoraproject.org/paste/jfuUGxbeKsi0q8EYKf1YNg)
  * :heavy_check_mark: Istio-Upstream [#[2138]](https://paste.fedoraproject.org/paste/F9fZsiphG3eRwjaTwgNdxA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7724, 7725]](https://paste.fedoraproject.org/paste/gARCCaYB3ek3ITEQvaRwfQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[585, 586]](https://paste.fedoraproject.org/paste/dIEdCSt93vFkcHgyTiVurg)
  * :heavy_check_mark: install-bookinfo [#[162, 163]](https://paste.fedoraproject.org/paste/qLnfVWNMHXPTDgPVz0RJhw)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[44]](https://paste.fedoraproject.org/paste/wUUNAxc4bG1Us9oa-Rr8Pg)
  * :heavy_check_mark: clean-environment [#[195, 196, 197]](https://paste.fedoraproject.org/paste/P05-8m111LaiO1h8waVWPA)
  * :question: python-ui-tests-parallel [#[755]](https://paste.fedoraproject.org/paste/wMxbNdSGqv-0ti9LavceAw)
  * :question: run-python3-ui-tests [#[4864, 4865, 4866, 4867, 4868, 4869, 4870, 4871, 4872, 4873, 4874]](https://paste.fedoraproject.org/paste/oletQyDj53VqyRDl~zVcEg)

**Comment by hhovsepy** [comment]
wizard tests are passing

**Pull request merged**
