### PR TITLE
Added validation tests for Sidecars

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#515](https://paste.centos.org/view/e9d3266d )
  * :red_circle: upstream-istio-pipeline [#[188]](https://paste.centos.org/view/5689c37a )
  * :heavy_check_mark: build-kiali [#[1566]](Log omitted)
  * :heavy_check_mark: install-istio [#[356]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5880, 5881, 5878, 5879]](Log omitted)
  * :red_circle: istio-kiali-mesh-checker [#[3795, 3796, 3797]](https://paste.centos.org/view/ceadbafd )
  * :red_circle: install-bookinfo [#[2856, 2857]](https://paste.centos.org/view/8587752c )
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1617]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#516](https://paste.centos.org/view/44034f5a )
  * :question: upstream-istio-pipeline [#[189]](https://paste.centos.org/view/ee85dbb9 )
  * :heavy_check_mark: build-kiali [#[1568]](Log omitted)
  * :heavy_check_mark: install-istio [#[359]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5890, 5883, 5886, 5887]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3800, 3801, 3802]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2859, 2861]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1619]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[806]](https://paste.centos.org/view/c33fd322 )
  * :question: run-kiali-ui-tests [#[13600, 13601, 13602, 13603, 13604, 13605, 13606, 13607, 13608, 13609, 13610, 13611, 13612, 13613, 13614, 13615, 13616]](https://paste.centos.org/view/e9a97921 )

**Pull request merged**
