### PR TITLE
Workload adjustements

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#145](https://paste.fedoraproject.org/paste/oy58~tzL-BOylYvyVvDbCQ)
  * :question: python-ui-tests-parallel [#[106]](https://paste.fedoraproject.org/paste/rnA~zzz1RdsSmKv4ZZNUgQ)
  * :question: run-python-ui-tests [#[1824, 1825, 1826, 1827, 1817, 1818, 1819, 1820, 1821, 1822, 1823]](https://paste.fedoraproject.org/paste/6HeK5lCsrP8NLAqL0YyBQg)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#146](https://paste.fedoraproject.org/paste/BaK-0PxRQVaK0KyxnN6f6A)
  * :question: python-ui-tests-parallel [#[111]](https://paste.fedoraproject.org/paste/aZk6TcHxjWiegJW6x~ZPww)
  * :question: run-python-ui-tests [#[1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882]](https://paste.fedoraproject.org/paste/LH47AyK3GJs-ysvqVGpESA)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#147](https://paste.fedoraproject.org/paste/7P9jC9lX4GAp2vzbO2cWVg)
  * :question: python-ui-tests-parallel [#[118]](https://paste.fedoraproject.org/paste/8wiYfgy3~KEydj3wz7sEsw)
  * :question: run-python-ui-tests [#[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1949, 1950, 1951]](https://paste.fedoraproject.org/paste/fYZ317aOf6g1nu0d3y8HRA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#149](https://paste.fedoraproject.org/paste/QQzStaOghOxN62bRTTGLtw)
  * :question: python-ui-tests-parallel [#[121]](https://paste.fedoraproject.org/paste/3DeoTNlg92dJRH1ubBfj7w)
  * :question: run-python-ui-tests [#[1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1983]](https://paste.fedoraproject.org/paste/DBb-LVz7ccxT0KE6LcJBwg)

**Comment by hhovsepy** [comment]
failed tests are not workload related

**Pull request merged**
