### PR TITLE
Applications and Workloads Labels comparison in tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#589](https://paste.centos.org/view/ec27ac67 )
  * :question: upstream-istio-pipeline [#[528]](https://paste.centos.org/view/ed452673 )
  * :heavy_check_mark: build-kiali [#[2515]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[423]](Log omitted)
  * :heavy_check_mark: install-istio [#[1091]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9114, 9115, 9116]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6328, 6329, 6327]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4530, 4531]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1366]](https://paste.centos.org/view/283bb176 )
  * :question: run-kiali-ui-tests [#[23074, 23075, 23076, 23077, 23078, 23079, 23080, 23081, 23082, 23083, 23084, 23085, 23086, 23087, 23088, 23089, 23090]](https://paste.centos.org/view/6a6766d1 https://paste.centos.org/view/62f08855 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#590](https://paste.centos.org/view/161de770 )
  * :question: upstream-istio-pipeline [#[529]](https://paste.centos.org/view/d5741d23 )
  * :heavy_check_mark: build-kiali [#[2516]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[424]](Log omitted)
  * :heavy_check_mark: install-istio [#[1093]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9125, 9126, 9127]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6336, 6334, 6335]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4536, 4537]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1367]](https://paste.centos.org/view/612ed715 )
  * :red_circle: run-kiali-ui-tests [#[23104, 23105, 23106, 23107, 23091, 23092, 23093, 23094, 23095, 23096, 23097, 23098, 23099, 23100, 23101, 23102, 23103]](https://paste.centos.org/view/224936f8 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#591](https://paste.centos.org/view/fc74ca60 )
  * :question: upstream-istio-pipeline [#[532]](https://paste.centos.org/view/153e141e )
  * :heavy_check_mark: build-kiali [#[2523]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[428]](Log omitted)
  * :heavy_check_mark: install-istio [#[1099]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9152, 9150, 9151]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6353, 6354, 6355]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4550, 4551]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1371]](https://paste.centos.org/view/872cb781 )
  * :question: run-kiali-ui-tests [#[23168, 23169, 23170, 23171, 23172, 23173, 23175, 23152, 23153, 23154, 23155, 23156, 23157, 23158, 23159, 23160, 23161]](https://paste.centos.org/view/fa95596e )

**Comment by hhovsepy** [comment]
Failing tests are logged issues.

**Pull request merged**
