### PR TITLE
Added more options in wizzards. Request Timeouts.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#649](https://paste.centos.org/view/075e3591 )
  * :red_circle: upstream-istio-pipeline [#[749]](https://paste.centos.org/view/fd5a2bff )
  * :heavy_check_mark: build-kiali [#[3269]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[874]](Log omitted)
  * :red_circle: install-istio [#[1648]](https://paste.centos.org/view/c806b5fd )
  * :heavy_check_mark: clean-environment [#[12324]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
