### PR TITLE
Added circuit braker check wizard

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#641](https://paste.centos.org/view/81fc7eb1 )
  * :question: upstream-istio-pipeline [#[726]](https://paste.centos.org/view/7ce9496b )
  * :heavy_check_mark: build-kiali [#[3190]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[819]](Log omitted)
  * :heavy_check_mark: install-istio [#[1601]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11907, 11910, 11911]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8164, 8166, 8167]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5734, 5735]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1751]](https://paste.centos.org/view/43dac69b )
  * :question: run-kiali-ui-tests [#[29670, 29671, 29672, 29673, 29674, 29675, 29676, 29677, 29678, 29679, 29680, 29681, 29682, 29683, 29684, 29685, 29686]](https://paste.centos.org/view/f105f3a6 https://paste.centos.org/view/bb734609 https://paste.centos.org/view/47714bba https://paste.centos.org/view/f9aecea5 https://paste.centos.org/view/df54ea8c )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#644](https://paste.centos.org/view/cd46c379 )
  * :question: upstream-istio-pipeline [#[734]](https://paste.centos.org/view/1c2f31d5 )
  * :heavy_check_mark: build-kiali [#[3210]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[836]](Log omitted)
  * :heavy_check_mark: install-istio [#[1615]](Log omitted)
  * :heavy_check_mark: clean-environment [#[12012, 12013, 12014]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8256, 8257, 8258]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5792, 5793]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1768]](https://paste.centos.org/view/724d034a )
  * :question: run-kiali-ui-tests [#[29934, 29935, 29936, 29937, 29938, 29939, 29940, 29941, 29942, 29943, 29945, 29946, 29947, 29948, 29949, 29950, 29951]](https://paste.centos.org/view/ee30cb08 https://paste.centos.org/view/659ee101 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#645](https://paste.centos.org/view/c77c3d0d )
  * :question: upstream-istio-pipeline [#[735]](https://paste.centos.org/view/3dfc18a0 )
  * :heavy_check_mark: build-kiali [#[3212]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[837]](Log omitted)
  * :heavy_check_mark: install-istio [#[1616]](Log omitted)
  * :heavy_check_mark: clean-environment [#[12016, 12017, 12015]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8259, 8260, 8261]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5794, 5795]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1769]](https://paste.centos.org/view/19cdbdee )
  * :red_circle: run-kiali-ui-tests [#[29952, 29953, 29954, 29955, 29956, 29957, 29958, 29959, 29960, 29961, 29962, 29963, 29964, 29965, 29966, 29967, 29968]](https://paste.centos.org/view/347716eb )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#646](https://paste.centos.org/view/0c935d2a )
  * :question: upstream-istio-pipeline [#[744]](https://paste.centos.org/view/599c352d )
  * :heavy_check_mark: build-kiali [#[3255]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[863]](Log omitted)
  * :heavy_check_mark: install-istio [#[1632]](Log omitted)
  * :heavy_check_mark: clean-environment [#[12200, 12201, 12199]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8403, 8404, 8405]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5937, 5938]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1799]](https://paste.centos.org/view/e57c792e )
  * :question: run-kiali-ui-tests [#[30466, 30467, 30468, 30469, 30470, 30471, 30472, 30473, 30474, 30475, 30476, 30477, 30478, 30479, 30480, 30481, 30482]](https://paste.centos.org/view/d71a6963 https://paste.centos.org/view/175a3d2f )

**Pull request merged**
