### PR TITLE
Added new tests for Service Details and List.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#90](https://paste.fedoraproject.org/paste/p6DlppQTQN-biY5uFARK0w)
  * :red_circle: run-python-ui-tests [#514](https://paste.fedoraproject.org/paste/ZqlNZorEAi09tobT6IpWmQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#91](https://paste.fedoraproject.org/paste/mJ2sVU5ctMtX7zOvhMo6Kw)
  * :red_circle: run-python-ui-tests [#515](https://paste.fedoraproject.org/paste/UW3QB7qoJ1QZvJ64UMlCRA)

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#92](https://paste.fedoraproject.org/paste/x~fVNRzLgNN6r3NH7t8tvQ)
  * :heavy_check_mark: run-python-ui-tests [#516](https://paste.fedoraproject.org/paste/2SgehlhLxAqCC3cgWPGjiA)

**Pull request merged**
