### PR TITLE
Fixing failing tests

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#358](https://paste.fedoraproject.org/paste/MbAxzqANhgVYRp9ESNLNcg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[72]](https://paste.fedoraproject.org/paste/9GCmLvM81nSkW5VP9rcAIg)
  * :heavy_check_mark: Istio-Upstream [#[2021]](https://paste.fedoraproject.org/paste/wY~jHjYwps1wPl6rAZFb6A)
  * :red_circle: Kiali-Istio-Checker [#[7386, 7387, 7388]](https://paste.fedoraproject.org/paste/tlAHswjXPyuHkaiZbIg2GA)
  * :heavy_check_mark: Kiali-on-Openshift [#[249, 250]](https://paste.fedoraproject.org/paste/nvtag2JmXmeVQmbWiVCq5w)
  * :red_circle: old-bookinfo [#[3234]](https://paste.fedoraproject.org/paste/sNhUXTOFznX-lNbHrZ0wig)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#359](https://paste.fedoraproject.org/paste/~YHal7eb7o6enpIsRee3XA)
  * :question: Istio-and-Kiali-on-Openshift [#[75]](https://paste.fedoraproject.org/paste/jYAcZpP~mu-k0wCp3ZsNeg)
  * :heavy_check_mark: Istio-Upstream [#[2024]](https://paste.fedoraproject.org/paste/ByWp9e9qf5pUBljK~-Brqw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7400, 7399]](https://paste.fedoraproject.org/paste/6I51t7UPx5la3hyNez28eg)
  * :heavy_check_mark: Kiali-on-Openshift [#[261, 262]](https://paste.fedoraproject.org/paste/i0x7HiJIh-ansbaoREvyDA)
  * :heavy_check_mark: old-bookinfo [#[3237]](https://paste.fedoraproject.org/paste/U1TYgnFn7AzaQpNqCb8deg)
  * :question: python-ui-tests-parallel [#[687]](https://paste.fedoraproject.org/paste/nnV8PHDlwonNdAUcdVzHzQ)
  * :question: run-python3-ui-tests [#[4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117]](https://paste.fedoraproject.org/paste/8l1VUNl72WpSH5Zr5pB-Qw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#360](https://paste.fedoraproject.org/paste/0-dE3p5GZubbMVh4vrkBjg)
  * :question: Istio-and-Kiali-on-Openshift [#[76]](https://paste.fedoraproject.org/paste/nMseUOs4vngE3d0j49pm1Q)
  * :heavy_check_mark: Istio-Upstream [#[2025]](https://paste.fedoraproject.org/paste/YP4GJxe3bI1~ABHdn-aoxQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7402, 7403]](https://paste.fedoraproject.org/paste/VuyMzPbZmlo1FBdB~kP2OA)
  * :heavy_check_mark: Kiali-on-Openshift [#[264, 265]](https://paste.fedoraproject.org/paste/l17dK8~GPutuE-FqZm9H2w)
  * :heavy_check_mark: old-bookinfo [#[3238]](https://paste.fedoraproject.org/paste/ep6z7jaT87iP1Mz3GTMD-g)
  * :question: python-ui-tests-parallel [#[688]](https://paste.fedoraproject.org/paste/GOlosmx1~TptO9PJhkpg2w)
  * :question: run-python3-ui-tests [#[4128, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127]](https://paste.fedoraproject.org/paste/FjAkLm1VD3tP-Nb1EAQaaQ)

**Comment by hhovsepy** [comment]
Failing tests are random, or recorded: https://issues.jboss.org/browse/KIALI-2917

**Pull request merged**
