### PR TITLE
Added support for Applications page. Some refactorings.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#111](https://paste.fedoraproject.org/paste/i3JlQh~A5JhDLkmCcu0Hig)
  * :question: python-ui-tests-parallel [#[38]](https://paste.fedoraproject.org/paste/fIJG-ISEOHm8e819faukJA)
  * :question: run-python-ui-tests [#[1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078]](https://paste.fedoraproject.org/paste/kLyZDCSfWGCI5j~2mJY2hg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#112](https://paste.fedoraproject.org/paste/AI3H14GSM40j9H9rtz6jjw)
  * :question: python-ui-tests-parallel [#[39]](https://paste.fedoraproject.org/paste/AsNyLAvdzbOepP1hqwAe6g)
  * :question: run-python-ui-tests [#[1088, 1089, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087]](https://paste.fedoraproject.org/paste/YM1J2pz2XNaM1V~FmDwMaw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#115](https://paste.fedoraproject.org/paste/5V70dYobF5nURswR-PjJ-g)
  * :question: python-ui-tests-parallel [#[43]](https://paste.fedoraproject.org/paste/KGMC1sCfj65Y2JTawPvV~g)
  * :question: run-python-ui-tests [#[1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133]](https://paste.fedoraproject.org/paste/hMGaMfcX9bCNShn5poJntw)

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#116](https://paste.fedoraproject.org/paste/daPxd23ZntCKf9Il9h0uJw)
  * :red_circle: python-ui-tests-parallel [#[50]](https://paste.fedoraproject.org/paste/s4mgWMkFaOaT2c2JnCJBxQ)
  * :red_circle: run-python-ui-tests [#[1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210]](https://paste.fedoraproject.org/paste/ikPQ8acTpm4EK53~HNeNuQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#117](https://paste.fedoraproject.org/paste/Y9PrupAM5zw7jfnz~7F5cw)
  * :question: python-ui-tests-parallel [#[51]](https://paste.fedoraproject.org/paste/SWBdXboP6yfffQYIUkidLg)
  * :question: run-python-ui-tests [#[1216, 1217, 1218, 1219, 1220, 1221, 1211, 1212, 1213, 1214, 1215]](https://paste.fedoraproject.org/paste/WoWsTuDjpOr9bLGC7e6Fmw)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#118](https://paste.fedoraproject.org/paste/FQJaDOSmVVfRvze0aqqjjA)
  * :question: python-ui-tests-parallel [#[52]](https://paste.fedoraproject.org/paste/msgeYZieCAW5fJbrAK~6Bg)
  * :question: run-python-ui-tests [#[1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232]](https://paste.fedoraproject.org/paste/LuYT0wjE5GFwzkMl7L1O9w)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#119](https://paste.fedoraproject.org/paste/swuKUp65g-uFlT4P2g02xg)
  * :question: python-ui-tests-parallel [#[53]](https://paste.fedoraproject.org/paste/xw3rktXvczPd6ouxBzMwEA)
  * :question: run-python-ui-tests [#[1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243]](https://paste.fedoraproject.org/paste/9VcQ6BQDV6b5YRSf~sG3sA)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#120](https://paste.fedoraproject.org/paste/RRqQH8WRnLHqwUbJ9GkGzA)
  * :question: python-ui-tests-parallel [#[54]](https://paste.fedoraproject.org/paste/S7-NqlfmMRFtgUBLa4Lakw)
  * :question: run-python-ui-tests [#[1248, 1249, 1250, 1251, 1252, 1253, 1254, 1244, 1245, 1246, 1247]](https://paste.fedoraproject.org/paste/2-8fho7yBTG~XxxtwZdEHw)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#121](https://paste.fedoraproject.org/paste/ElSTXxnFyqzQctDYOcI70A)
  * :question: python-ui-tests-parallel [#[55]](https://paste.fedoraproject.org/paste/yn7nLC5Z2Yxq38vNIWNraw)
  * :question: run-python-ui-tests [#[1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265]](https://paste.fedoraproject.org/paste/rv-~rjpplFLmd4dILWkExA)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#122](https://paste.fedoraproject.org/paste/pdDNX7Tv0Kcm5KzcpVVCHA)
  * :question: python-ui-tests-parallel [#[57]](https://paste.fedoraproject.org/paste/hc3JP9SnSYdw4rlrRAFRDg)
  * :question: run-python-ui-tests [#[1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1277, 1278, 1279]](https://paste.fedoraproject.org/paste/ohiQ7RLB3OE5ORIpQwcqpA)

**Pull request merged**
