### PR TITLE
Fixing failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
Manual run pass. Random failures because or parrallel run is out of scope.

**Pull request merged**
