### PR TITLE
Fixing failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#669](https://paste.centos.org/view/491f112f )
  * :question: upstream-istio-pipeline [#[842]](https://paste.centos.org/view/667f4be4 )
  * :heavy_check_mark: build-kiali [#[3581]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1053]](Log omitted)
  * :heavy_check_mark: install-istio [#[1839]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14092, 14093, 14094, 14095]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10036, 10037, 10038, 10039]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7408, 7406, 7407]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1983]](https://paste.centos.org/view/5062c4d5 )
  * :red_circle: run-kiali-ui-tests [#[33856, 33857, 33858, 33859, 33860, 33861, 33862, 33863, 33847, 33848, 33849, 33850, 33851, 33852, 33853, 33854, 33855]](https://paste.centos.org/view/d9420eee )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#670](https://paste.centos.org/view/316ee4c3 )
  * :question: upstream-istio-pipeline [#[847]](https://paste.centos.org/view/f915ee18 )
  * :heavy_check_mark: build-kiali [#[3591]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1062]](Log omitted)
  * :heavy_check_mark: install-istio [#[1844]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14148, 14149, 14150, 14151]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10080, 10081, 10078, 10079]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7443, 7444, 7445]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1992]](https://paste.centos.org/view/0c6e2e2a )
  * :red_circle: run-kiali-ui-tests [#[34016, 34017, 34018, 34002, 34003, 34004, 34005, 34006, 34007, 34008, 34009, 34010, 34011, 34012, 34013, 34014, 34015]](https://paste.centos.org/view/91b05ace https://paste.centos.org/view/982ce8dc )

**Pull request merged**
