### PR TITLE
Kiali Client 0.5 support: Initial commit

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#223](https://paste.fedoraproject.org/paste/Fxw3lv~CMu5NmIJ4ofr4vA)
  * :question: Istio-and-Kiali-on-Openshift [#[2209]](https://paste.fedoraproject.org/paste/1wCsniejIoU-Y2aItga6gw)
  * :heavy_check_mark: Istio-Upstream [#[929]](https://paste.fedoraproject.org/paste/rQjbymETBqBLL4mnJAW6VQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3024, 3025, 3026, 3023]](https://paste.fedoraproject.org/paste/wmZIJtS6h8Od4GRIQ7QakA)
  * :heavy_check_mark: Kiali-on-Openshift [#[1657, 1658]](https://paste.fedoraproject.org/paste/1rBXe0Gc1oNl9NN0kxNMeA)
  * :heavy_check_mark: install-bookinfo [#[1698, 1699]](https://paste.fedoraproject.org/paste/4wVTcTuHQc-ekMoqvLe1ig)
  * :question: python-ui-tests-parallel [#[308]](https://paste.fedoraproject.org/paste/J6p1Yr7fgIwf9XYYX-vNeA)
  * :question: run-python-ui-tests [#[4032, 4033, 4034, 4024, 4025, 4026, 4027, 4028, 4029, 4030, 4031]](https://paste.fedoraproject.org/paste/mnh2v60jwyJYOCenvko6gA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#224](https://paste.fedoraproject.org/paste/95rh4CuoUf~w5PYf3T8QNQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2221]](https://paste.fedoraproject.org/paste/XEHmt4Ultl1LR9Pn6~johA)
  * :heavy_check_mark: Istio-Upstream [#[940]](https://paste.fedoraproject.org/paste/6CNCx3UCVJJIf7gPGn-CwA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3065, 3066, 3067, 3068]](https://paste.fedoraproject.org/paste/S8m67J-Nd0zhg-XLQr2BPg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1685, 1686]](https://paste.fedoraproject.org/paste/dN8aRYmBXJXiO2JueL4hOg)
  * :heavy_check_mark: install-bookinfo [#[1720, 1719]](https://paste.fedoraproject.org/paste/riz~X-2wveDzf78LV56~BQ)
  * :question: python-ui-tests-parallel [#[311]](https://paste.fedoraproject.org/paste/NYb4cYWKwxGHROMbVilrWw)
  * :question: run-python-ui-tests [#[4064, 4065, 4066, 4067, 4057, 4058, 4059, 4060, 4061, 4062, 4063]](https://paste.fedoraproject.org/paste/Vya6W1hQaIiEZmgVn1Ab8Q)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#225](https://paste.fedoraproject.org/paste/evYOMATKbzzXDAtTOqnwDQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2227]](https://paste.fedoraproject.org/paste/rIKtzksKISEFm4suVS9a~w)
  * :heavy_check_mark: Istio-Upstream [#[945]](https://paste.fedoraproject.org/paste/44EUxRtgYeSKnhTWvtZpww)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3088, 3089, 3086, 3087]](https://paste.fedoraproject.org/paste/wwObFhxf5oJDDWlQfSXkvQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1698, 1699]](https://paste.fedoraproject.org/paste/hIaBX-2su3rvociJJ5cYyg)
  * :heavy_check_mark: install-bookinfo [#[1731, 1732]](https://paste.fedoraproject.org/paste/49e-mGZz6Un-cpXs69v-Ng)
  * :question: python-ui-tests-parallel [#[313]](https://paste.fedoraproject.org/paste/v5EBV26ZJvUTa3X9~CMKOg)
  * :question: run-python-ui-tests [#[4096, 4097, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095]](https://paste.fedoraproject.org/paste/ddJFM9elgPRi92WbNDPYMQ)

**Comment by hhovsepy** [comment]
Manually run http://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8080/job/python3-ui-tests-parallel/3/

**Comment by hhovsepy** [comment]
Merging PR as tests passed on manual jenkins job run.

**Pull request merged**
