### PR TITLE
Test commit

### PR DESCRIPTION
**Pull request by FilipB**
Do not merge

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#188](https://paste.fedoraproject.org/paste/eKYjk1fMm6HcirkaPPkO~g)
  * :question: Istio-and-Kiali-on-Openshift [#[2067]](https://paste.fedoraproject.org/paste/lV3RNzfK8CokFoen76CSUA)
  * :heavy_check_mark: Istio-Upstream [#[818]](https://paste.fedoraproject.org/paste/qAH6ZtgczuSt9~VEKjRpnA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2601, 2597]](https://paste.fedoraproject.org/paste/d0E2IJ56kcOh3IbEhALCSw)
  * :heavy_check_mark: install-bookinfo [#[1451, 1452]](https://paste.fedoraproject.org/paste/R7pa6a2nGIKEhTzU8wgeGg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1407]](https://paste.fedoraproject.org/paste/8lt6bvJwEtH3PXLFKfPf-Q)
  * :question: python-ui-tests-parallel [#[211]](https://paste.fedoraproject.org/paste/KJ~V2dpFCiw5y-7t914v1g)
  * :question: run-python-ui-tests [#[2976, 2977, 2978, 2979, 2980, 2970, 2971, 2972, 2973, 2974, 2975]](https://paste.fedoraproject.org/paste/b~AHdzoH1rxK7TA7CBM1Ig)
  * :heavy_check_mark: run-kiali-e2e-tests [#[768]](https://paste.fedoraproject.org/paste/~L~G2paVB4mEDVk-2JvkoA)

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#192](https://paste.fedoraproject.org/paste/Ubq3awTETq7LnSb7p5XWrA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2135]](https://paste.fedoraproject.org/paste/Y6O~BSVDieVz3I5uLDx8GQ)
  * :heavy_check_mark: Istio-Upstream [#[881]](https://paste.fedoraproject.org/paste/Bi0DLtjGFd~3UUdwgmx3Fw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2792, 2794]](https://paste.fedoraproject.org/paste/GsFhzCHVfG-Dhz4nVvp5Nw)
  * :heavy_check_mark: install-bookinfo [#[1557, 1558]](https://paste.fedoraproject.org/paste/EgULrLD9IGU3xgvBjM9Mcw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1482]](https://paste.fedoraproject.org/paste/K4gvNvgT3vSeen0wuZvhew)
  * :heavy_check_mark: python-ui-tests-parallel [#[252]](https://paste.fedoraproject.org/paste/WDOtdmRy5dMEih49r~u3hA)
  * :heavy_check_mark: run-python-ui-tests [#[3424, 3425, 3426, 3427, 3428, 3430, 3419, 3420, 3421, 3422, 3423]](https://paste.fedoraproject.org/paste/sDM7svvXLcTSPIzNDe8EHg)

**Comment by FilipB** [comment]
kialiqeci

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#193](https://paste.fedoraproject.org/paste/edKhD70f9saJQYsShUiuJQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2137]](https://paste.fedoraproject.org/paste/04dUHCBEMXE5SWzRFRD9xQ)
  * :heavy_check_mark: Istio-Upstream [#[883]](https://paste.fedoraproject.org/paste/6am26yfc0cFMW6rUuwgp7g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2797, 2799]](https://paste.fedoraproject.org/paste/bQAYvHgUlm8HnA7W4eYbaA)
  * :heavy_check_mark: install-bookinfo [#[1561, 1562]](https://paste.fedoraproject.org/paste/q5uvpyvXa9NySERFEwGHKw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1484]](https://paste.fedoraproject.org/paste/R4X-rAHr-09iu25KRT3BdQ)
  * :heavy_check_mark: python-ui-tests-parallel [#[254]](https://paste.fedoraproject.org/paste/M9iJyzUbTGLrbs9b-Ff52w)
  * :heavy_check_mark: run-python-ui-tests [#[3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3452]](https://paste.fedoraproject.org/paste/1MbpSw9dPBC75XF4mdsJAA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#194](https://paste.fedoraproject.org/paste/amv8aLirRXNUK26bLo9Aew)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2139]](https://paste.fedoraproject.org/paste/gted8vSZcJgmxKWRyzx5QQ)
  * :heavy_check_mark: Istio-Upstream [#[884]](https://paste.fedoraproject.org/paste/29pCSIoh0gKdgSiWmvKNXQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2802, 2803]](https://paste.fedoraproject.org/paste/j~iA0-e4w-1y~~SyD9wTcg)
  * :heavy_check_mark: install-bookinfo [#[1563, 1564]](https://paste.fedoraproject.org/paste/s~YyKIxc3W8RrKLLYOw7sQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1486]](https://paste.fedoraproject.org/paste/e1d~1S0t7797XmUF0DYVkA)
  * :heavy_check_mark: python-ui-tests-parallel [#[256]](https://paste.fedoraproject.org/paste/P2L3wr569tHbacTuf-upcg)
  * :heavy_check_mark: run-python-ui-tests [#[3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474]](https://paste.fedoraproject.org/paste/hSNO9NCjgt~BNt4oAdn3sQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#196](https://paste.fedoraproject.org/paste/Lxh9zW8jT1INvigd5sYLEA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2145]](https://paste.fedoraproject.org/paste/AlHuxPAbX101zCIHV2RcfA)
  * :heavy_check_mark: Istio-Upstream [#[889]](https://paste.fedoraproject.org/paste/OxyQPQn2tgrBrdOJlhkS8A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2816, 2819]](https://paste.fedoraproject.org/paste/wDvmxjZ46j4dr1YCmwwWmw)
  * :heavy_check_mark: install-bookinfo [#[1576, 1577]](https://paste.fedoraproject.org/paste/EVQ3RB4~QVHozTJ2Ye0kzg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1495]](https://paste.fedoraproject.org/paste/qeZJKGlEMSXa1zynXCumVQ)
  * :heavy_check_mark: python-ui-tests-parallel [#[258]](https://paste.fedoraproject.org/paste/ymJA1Pct2hQI2~Q0MgQNmg)
  * :heavy_check_mark: run-python-ui-tests [#[3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3506, 3486, 3487]](https://paste.fedoraproject.org/paste/gZock5kOMg-5KqWvH75ENw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#197](https://paste.fedoraproject.org/paste/vipm6BwgsaRslGN0cE7-NQ)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2146]](https://paste.fedoraproject.org/paste/Y1BSIf9pQ~UR8j1i~rv0Fg)
  * :heavy_check_mark: Istio-Upstream [#[890]](https://paste.fedoraproject.org/paste/uy3XYiMA47~5K9T3RTpVqA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2817, 2820]](https://paste.fedoraproject.org/paste/~aoAIzNayZU0HZt~zQieeA)
  * :heavy_check_mark: install-bookinfo [#[1578, 1579]](https://paste.fedoraproject.org/paste/wM0D8mF3YQXgacQirPW8yw)
  * :heavy_check_mark: Kiali-on-Openshift [#[1496]](https://paste.fedoraproject.org/paste/QBgKWZe4Lf181ehbff-kxQ)
  * :heavy_check_mark: python-ui-tests-parallel [#[259]](https://paste.fedoraproject.org/paste/G7AE-w92pjXTrXeQP2F~BQ)
  * :heavy_check_mark: run-python-ui-tests [#[3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3507]](https://paste.fedoraproject.org/paste/bJrypGQ00uISpudmL8wisQ)

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request closed without merging**
