### PR TITLE
Various test fixes

### PR DESCRIPTION
**Pull request by FilipB**

### CODE REVIEW

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#422](https://paste.fedoraproject.org/paste/rCFxpk-FVCo~nK~BWD6TYA)
  * :red_circle: upstream-pipeline [#[325]](https://paste.fedoraproject.org/paste/b9-PQU1unGjQiUylroZkng)
  * :heavy_check_mark: install-maistra [#[1075]](https://paste.fedoraproject.org/paste/MWQzA6gcBsI1x5BugF9PfQ)
  * :heavy_check_mark: clean-environment [#[2272, 2269, 2270, 2271]](https://paste.fedoraproject.org/paste/ig3SF1O1USMF3UtS62VE0Q)
  * :red_circle: istio-kiali-mesh-checker [#[1123, 1124, 1125]](https://paste.fedoraproject.org/paste/cd6eRwh1U1s4cCk2aA~qPg)
  * :red_circle: install-bookinfo [#[1145, 1146]](https://paste.fedoraproject.org/paste/HvEG8XDu9-Ex3K-j-~Eb9g)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[624]](https://paste.fedoraproject.org/paste/uFqLkL2-LW6wwQ-fIkrYlA)

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#424](https://paste.fedoraproject.org/paste/GbChGeCxvR4eIwin-UJvCA)
  * :question: upstream-pipeline [#[330]](https://paste.fedoraproject.org/paste/edF5L8YNn5SsCi5-OeLDlw)
  * :heavy_check_mark: install-maistra [#[1080]](https://paste.fedoraproject.org/paste/RZrfPrhNbNkbBGeD0005Cg)
  * :heavy_check_mark: clean-environment [#[2288, 2290, 2291, 2292]](https://paste.fedoraproject.org/paste/RbxkJdRCpewYyamTPYmYcg)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1138, 1139, 1140]](https://paste.fedoraproject.org/paste/GouXLyF6l3xQ7CwkCpphbQ)
  * :heavy_check_mark: install-bookinfo [#[1155, 1156]](https://paste.fedoraproject.org/paste/U8TSJNBrzWAkXI1MXFWp-g)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[629]](https://paste.fedoraproject.org/paste/C47f4fBgdkw7ji-B51SVeA)
  * :question: run-kiali-ui-tests-parallel [#[256]](https://paste.fedoraproject.org/paste/Lzn4V3rI14B9TioNPk4KzA)
  * :question: run-kiali-ui-tests [#[4259, 4260, 4261, 4262, 4263, 4264, 4265, 4266, 4267, 4268, 4270, 4271, 4272, 4273, 4274, 4275, 4276]](https://paste.fedoraproject.org/paste/73DlIB-Z2n-aQCql3X1gYQ)

**Pull request merged**
