### PR TITLE
Adding Overview_Health_testcases:UI

### PR DESCRIPTION
**Pull request by pbajjuri20**
Adding Health new test cases for test_overview_page.py

Adding OverviewHealth values for enums.py

### CODE REVIEW

**Comment by kialiqeci** [comment]
Can one of the admins verify this patch?

**Comment by hhovsepy** [comment]
Travis CI fails with code style:
./kiali_qe/components/enums.py:139:1: W293 blank line contains whitespace
./kiali_qe/components/enums.py:142:1: E303 too many blank lines (3)
./kiali_qe/components/enums.py:445:1: W293 blank line contains whitespace
./kiali_qe/components/enums.py:446:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:177:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:178:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:203:89: W291 trailing whitespace

run flake8 before the commit

**Comment by pbajjuri20** [comment]
I have run the flake8 in the local and removed all the blank spaces.

**Comment by hhovsepy** [comment]
@pbajjuri20 please squash and merge all 3 commits into one.

**Comment by pbajjuri20** [comment]
@hhovsepy: I try to do once again with Squash Commits are doing some conflict with the last commit. I will create the New PR for this one.

**Pull request closed without merging**
