### PR TITLE
Tests for VS and DR config overview pages

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#625](https://paste.centos.org/view/3f5cc8ac )
  * :question: upstream-istio-pipeline [#[682]](https://paste.centos.org/view/5981d851 )
  * :heavy_check_mark: build-kiali [#[2975]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[689]](Log omitted)
  * :heavy_check_mark: install-istio [#[1473]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11010, 11011, 11012]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7515, 7516, 7517]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5294, 5295]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1620]](https://paste.centos.org/view/c22f2f5b )
  * :question: run-kiali-ui-tests [#[27424, 27425, 27426, 27427, 27428, 27429, 27430, 27431, 27432, 27433, 27434, 27435, 27436, 27420, 27421, 27422, 27423]](https://paste.centos.org/view/29d1d830 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#626](https://paste.centos.org/view/eb8a9ebf )
  * :question: upstream-istio-pipeline [#[683]](https://paste.centos.org/view/acf070f9 )
  * :heavy_check_mark: build-kiali [#[2977]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[690]](Log omitted)
  * :heavy_check_mark: install-istio [#[1475]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11024, 11025, 11020]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7528, 7526, 7527]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5301, 5302]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1622]](https://paste.centos.org/view/77956a68 )
  * :question: run-kiali-ui-tests [#[27456, 27457, 27458, 27459, 27460, 27461, 27462, 27463, 27464, 27465, 27466, 27467, 27468, 27470, 27453, 27454, 27455]](https://paste.centos.org/view/968308a4 https://paste.centos.org/view/15135ae6 )

**Comment by hhovsepy** [comment]
Details tests pass in manual run.

**Pull request merged**
