### PR TITLE
Wizzard: added PeerAuth tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#604](https://paste.centos.org/view/f098b456 )
  * :red_circle: upstream-istio-pipeline [#[610]](https://paste.centos.org/view/6c5e103f )
  * :heavy_check_mark: build-kiali [#[2716]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[535]](Log omitted)
  * :red_circle: install-istio [#[1290]](https://paste.centos.org/view/59a5e082 )
  * :heavy_check_mark: clean-environment [#[9996]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#605](https://paste.centos.org/view/a561bcff )
  * :question: upstream-istio-pipeline [#[611]](https://paste.centos.org/view/999d624b )
  * :heavy_check_mark: build-kiali [#[2717]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[536]](Log omitted)
  * :heavy_check_mark: install-istio [#[1291]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10000, 10001, 9999]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6829, 6830, 6831]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4856, 4855]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1477]](https://paste.centos.org/view/36b9a41c )
  * :question: run-kiali-ui-tests [#[24992, 24993, 24994, 24995, 24996, 24997, 24998, 24982, 24983, 24984, 24985, 24986, 24987, 24988, 24989, 24990, 24991]](https://paste.centos.org/view/73bed57b https://paste.centos.org/view/03b1e5ee https://paste.centos.org/view/04b0a55e )

**Comment by hhovsepy** [comment]
Wizzard tests are passing.

**Pull request merged**
