### PR TITLE
Added Istio Configs comparing with OC results in Workload and Service pages

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#653](https://paste.centos.org/view/2cb50e7f )
  * :question: upstream-istio-pipeline [#[764]](https://paste.centos.org/view/092e4242 )
  * :heavy_check_mark: build-kiali [#[3318]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[907]](Log omitted)
  * :heavy_check_mark: install-istio [#[1686]](Log omitted)
  * :heavy_check_mark: clean-environment [#[12512, 12513, 12511]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8672, 8673, 8674]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6133, 6134]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1842]](https://paste.centos.org/view/5b612ae4 )
  * :question: run-kiali-ui-tests [#[31328, 31329, 31330, 31331, 31332, 31333, 31334, 31335, 31336, 31337, 31338, 31322, 31323, 31324, 31325, 31326, 31327]](https://paste.centos.org/view/d3681de5 https://paste.centos.org/view/c11cdf29 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#654](https://paste.centos.org/view/5d4357b7 )
  * :question: upstream-istio-pipeline [#[766]](https://paste.centos.org/view/4b5eed5d )
  * :heavy_check_mark: build-kiali [#[3324]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[910]](Log omitted)
  * :heavy_check_mark: install-istio [#[1690]](Log omitted)
  * :heavy_check_mark: clean-environment [#[12528, 12526, 12527]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[8688, 8689, 8687]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6144, 6143]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1846]](https://paste.centos.org/view/7555b2f0 )
  * :question: run-kiali-ui-tests [#[31392, 31393, 31394, 31395, 31396, 31397, 31398, 31399, 31400, 31401, 31402, 31403, 31404, 31405, 31406, 31407, 31391]](https://paste.centos.org/view/b2dcc355 https://paste.centos.org/view/7ac71893 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
