### PR TITLE
Filter items in REST and OC results for Services

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#684](https://paste.centos.org/view/a457eead )
  * :question: upstream-istio-pipeline [#[911]](https://paste.centos.org/view/4314ce56 )
  * :heavy_check_mark: build-kiali [#[3722]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1154]](Log omitted)
  * :heavy_check_mark: install-istio [#[1946]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14828, 14829, 14830, 14831]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10672, 10673, 10674, 10675]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7957, 7958, 7959]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2089]](https://paste.centos.org/view/ad2d3827 )
  * :question: run-kiali-ui-tests [#[35744, 35745, 35729, 35730, 35731, 35732, 35733, 35734, 35735, 35736, 35737, 35738, 35739, 35740, 35741, 35742, 35743]](https://paste.centos.org/view/c4355d3a https://paste.centos.org/view/a3f24d9d https://paste.centos.org/view/9ef83dfb )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#685](https://paste.centos.org/view/764b3b52 )
  * :question: upstream-istio-pipeline [#[912]](https://paste.centos.org/view/d7089f19 )
  * :heavy_check_mark: build-kiali [#[3723]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1155]](Log omitted)
  * :heavy_check_mark: install-istio [#[1947]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14832, 14833, 14834, 14835]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10676, 10677, 10678, 10679]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7960, 7961, 7962]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2090]](https://paste.centos.org/view/51729d8b )
  * :question: run-kiali-ui-tests [#[35747, 35748, 35749, 35750, 35751, 35752, 35753, 35754, 35755, 35756, 35757, 35758, 35759, 35760, 35761, 35762, 35763]](https://paste.centos.org/view/f74ff380 https://paste.centos.org/view/18db7a24 https://paste.centos.org/view/96edc083 )

**Pull request merged**
