### PR TITLE
Fixed failing tests. Skip intermittent failing config list check for CRUD tests. Skip Jaeger checking based on config.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#414](https://paste.fedoraproject.org/paste/1zk72uvazGEK9WpNIJw6jg)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#415](https://paste.fedoraproject.org/paste/rQEIRcwIZ~QjCq~yj0LW8Q)
  * :question: upstream-pipeline [#[134]](https://paste.fedoraproject.org/paste/RBexMboI7V7SD6ksO6R2Ig)
  * :heavy_check_mark: install-maistra [#[667]](https://paste.fedoraproject.org/paste/6wXnFi3XaTUWk1SfEBmC3w)
  * :heavy_check_mark: clean-environment [#[1152, 1149, 1150, 1151]](https://paste.fedoraproject.org/paste/WQGSOzL9o2ofJ2XnH3cjbg)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[268, 269, 270]](https://paste.fedoraproject.org/paste/Y~lyZxcEghzfmcJ-a852yg)
  * :heavy_check_mark: install-bookinfo [#[617, 618]](https://paste.fedoraproject.org/paste/WCc55XVy8Vxr~0MOGAjtLA)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[335]](https://paste.fedoraproject.org/paste/yLMK9-EQmYdjvsRZjFkbPQ)
  * :question: run-kiali-ui-tests-parallel [#[58]](https://paste.fedoraproject.org/paste/mk1728~TTg2Q3Eogdc830Q)
  * :question: run-kiali-ui-tests [#[896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 891, 892, 893, 894, 895]](https://paste.fedoraproject.org/paste/6YoTdXwauIAUfFRmnjC0dQ)

**Comment by hhovsepy** [comment]
> What about introducing new config in env.yaml for external resources like grafana,jaeger? Checking if Jaeger exists in kiali_client.get_response('getStatus') is not 100%. We would miss cases when Jaeger is expected but kiali_client.get_response('getStatus') incorrectly returns status without Jaeger.
> I vote for new config in env.yaml and fail Jaeger integration tests every time it's expected but is not available.

+1

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#416](https://paste.fedoraproject.org/paste/ubLP92UMK8neZ0gMH32daQ)
  * :question: upstream-pipeline [#[135]](https://paste.fedoraproject.org/paste/UtlBZnQKb-qYqQgwRul5CA)
  * :heavy_check_mark: install-maistra [#[669]](https://paste.fedoraproject.org/paste/s~tNJYYrtY7qW4L1Xj6DuQ)
  * :heavy_check_mark: clean-environment [#[1160, 1157, 1158, 1159]](https://paste.fedoraproject.org/paste/dgW-Qo6XEG87Ojd6SYtgLw)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[274, 275, 276]](https://paste.fedoraproject.org/paste/ZZsDVePwt9YbVdaQMt00jQ)
  * :heavy_check_mark: install-bookinfo [#[621, 622]](https://paste.fedoraproject.org/paste/JBtKth79h~IpL45KWwrR6A)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[337]](https://paste.fedoraproject.org/paste/G78WT1fiGmuhQX7EGPLShA)
  * :question: run-kiali-ui-tests-parallel [#[59]](https://paste.fedoraproject.org/paste/8dRtq2vQpsUjUFd3xTS6nw)
  * :question: run-kiali-ui-tests [#[909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925]](https://paste.fedoraproject.org/paste/iTSqoZOLrP~4T3F7Y2eJLg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#417](https://paste.fedoraproject.org/paste/YYn~TnYYKTwhly2QP~EUIg)
  * :question: upstream-pipeline [#[136]](https://paste.fedoraproject.org/paste/oWLG9FPWFcfBTtt3nkVBkg)
  * :heavy_check_mark: install-maistra [#[670]](https://paste.fedoraproject.org/paste/a0XBfH8qMyIwlhyNRKOLmw)
  * :heavy_check_mark: clean-environment [#[1161, 1162, 1163, 1164]](https://paste.fedoraproject.org/paste/ux29qlo7WlrGUK47IyRASQ)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[277, 278, 279]](https://paste.fedoraproject.org/paste/WYysvQsLkl5nRyxPYu59pg)
  * :heavy_check_mark: install-bookinfo [#[624, 623]](https://paste.fedoraproject.org/paste/uNiZiPReke-mA4coOmv1mA)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[338]](https://paste.fedoraproject.org/paste/~iuGspegNZxrymM7CC~TrQ)
  * :question: run-kiali-ui-tests-parallel [#[60]](https://paste.fedoraproject.org/paste/K5uZcqrAZhRWVy0OsW~vwA)
  * :question: run-kiali-ui-tests [#[928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 926, 927]](https://paste.fedoraproject.org/paste/nxgV3JBMNoiYgoN6V8HxvQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#419](https://paste.fedoraproject.org/paste/~oS-RbZB2cDvnTXWQ2Nrjg)
  * :question: upstream-pipeline [#[231]](https://paste.fedoraproject.org/paste/SI~xqoNYrodnsNCNnbV2FA)
  * :heavy_check_mark: install-maistra [#[891]](https://paste.fedoraproject.org/paste/IJA8oMj8geKFVWbkAUYp-A)
  * :heavy_check_mark: clean-environment [#[1744, 1740, 1742, 1743]](https://paste.fedoraproject.org/paste/r9OY1wpwi6QTxYyzhv6qJQ)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[704, 706, 703]](https://paste.fedoraproject.org/paste/QaS2180v9-H3h2kfSeosgw)
  * :heavy_check_mark: install-bookinfo [#[890, 892]](https://paste.fedoraproject.org/paste/ZJ6ClsmmMSC9vnC5J36Wvg)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[491]](https://paste.fedoraproject.org/paste/sdfwTGFPfOnpHvGQU-n6eg)
  * :question: run-kiali-ui-tests-parallel [#[158]](https://paste.fedoraproject.org/paste/L~NDZrlrrybFxA-EqMGpXA)
  * :question: run-kiali-ui-tests [#[2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613]](https://paste.fedoraproject.org/paste/62HGdz69XFm2-u2Ai~Hvng)

**Pull request merged**
