### PR TITLE
Workload Pods reading from OC

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#663](https://paste.centos.org/view/944c92c2 )
  * :question: upstream-istio-pipeline [#[805]](https://paste.centos.org/view/e76750bd )
  * :heavy_check_mark: build-kiali [#[3451]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[989]](Log omitted)
  * :heavy_check_mark: install-istio [#[1771]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13465, 13466, 13467, 13468]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9504, 9505, 9506, 9503]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6929, 6930, 6931]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1918]](https://paste.centos.org/view/a0603a29 )
  * :question: run-kiali-ui-tests [#[32679, 32680, 32681, 32682, 32683, 32684, 32685, 32686, 32687, 32688, 32689, 32690, 32691, 32692, 32693, 32694, 32695]](https://paste.centos.org/view/7d5794e8 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#664](https://paste.centos.org/view/ffada33d )
 :red_circle: PRT Failed, Please Contact QE

**Pull request merged**
