### PR TITLE
Moved Traces tab tests from Services to Applications

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#602](https://paste.centos.org/view/d3715351 )
  * :red_circle: upstream-istio-pipeline [#[608]](https://paste.centos.org/view/93c23ce8 )
  * :heavy_check_mark: build-kiali [#[2714]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[533]](Log omitted)
  * :red_circle: install-istio [#[1286]](https://paste.centos.org/view/947ffdf3 )
  * :heavy_check_mark: clean-environment [#[9985]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#603](https://paste.centos.org/view/dfd94abc )
  * :question: upstream-istio-pipeline [#[609]](https://paste.centos.org/view/b90e54b7 )
  * :heavy_check_mark: build-kiali [#[2715]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[534]](Log omitted)
  * :heavy_check_mark: install-istio [#[1287]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9987, 9990, 9991]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6820, 6822, 6823]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4852, 4853]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1476]](https://paste.centos.org/view/6a054e0d )
  * :question: run-kiali-ui-tests [#[24963, 24964, 24965, 24966, 24967, 24968, 24969, 24970, 24971, 24972, 24973, 24974, 24975, 24976, 24977, 24978, 24979]](https://paste.centos.org/view/cd09b904 https://paste.centos.org/view/80100374 https://paste.centos.org/view/a7370880 https://paste.centos.org/view/be28ff03 )

**Pull request merged**
