### PR TITLE
Added_OverviewHealth_enum_values

### PR DESCRIPTION
**Pull request by pbajjuri20**
Added new Health test cases for the Overview page.

### CODE REVIEW

**Comment by kialiqeci** [comment]
Can one of the admins verify this patch?

**Comment by pbajjuri20** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#675](https://paste.centos.org/view/cb279d85 )
  * :question: upstream-istio-pipeline [#[882]](https://paste.centos.org/view/b3aefc21 )
  * :heavy_check_mark: build-kiali [#[3674]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1114]](Log omitted)
  * :heavy_check_mark: install-istio [#[1910]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14595, 14596, 14597, 14598]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10474, 10475, 10476, 10477]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7800, 7801, 7799]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2054]](https://paste.centos.org/view/2ad0dfa8 )
  * :question: run-kiali-ui-tests [#[35136, 35137, 35138, 35139, 35140, 35141, 35142, 35143, 35127, 35128, 35129, 35130, 35131, 35132, 35133, 35134, 35135]](https://paste.centos.org/view/9eb0f717 https://paste.centos.org/view/d65dbcfa )

**Review by hhovsepy — APPROVED** [review]

**Pull request merged**
