### PR TITLE
Added Application Details OC call

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#266](https://paste.fedoraproject.org/paste/YZDTJ9E1Z7tRVGaPAYhWYg)
  * :question: Istio-and-Kiali-on-Openshift [#[2505]](https://paste.fedoraproject.org/paste/FWjCd-8lbzgi5Nh9zSBaEw)
  * :heavy_check_mark: Istio-Upstream [#[1173]](https://paste.fedoraproject.org/paste/2zbRez30g6FHzg9oEUsugA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4107, 4109, 4110, 4111]](https://paste.fedoraproject.org/paste/BGn6cQnUMRwIjm9MBuX~iw)
  * :heavy_check_mark: Kiali-on-Openshift [#[2358, 2359]](https://paste.fedoraproject.org/paste/8qsW1kS6Y0Hpzai-aDFEcw)
  * :heavy_check_mark: install-bookinfo [#[2164, 2165]](https://paste.fedoraproject.org/paste/w1E0vLT2nDxrzAvs6QJ9mg)
  * :question: python-ui-tests-parallel [#[422]](https://paste.fedoraproject.org/paste/uGo9i6WALjtK-QwYSMUdQQ)
  * :question: run-python3-ui-tests [#[1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209]](https://paste.fedoraproject.org/paste/hRS20a5V58ROHiqPA5g-gw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#267](https://paste.fedoraproject.org/paste/lO0odnpjogGli3l~DZ2d9A)
  * :question: Istio-and-Kiali-on-Openshift [#[2506]](https://paste.fedoraproject.org/paste/OQgIlC-LOeSk3~NIN23i5Q)
  * :heavy_check_mark: Istio-Upstream [#[1174]](https://paste.fedoraproject.org/paste/gsBYyfX7o7LOPYe8pRT14g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4112, 4113, 4115, 4117]](https://paste.fedoraproject.org/paste/c7Gsc7MXwZ~OqUOAZ2UOqw)
  * :heavy_check_mark: Kiali-on-Openshift [#[2360, 2362]](https://paste.fedoraproject.org/paste/ALDedEA2IPJ5f~LkcSWc8w)
  * :heavy_check_mark: install-bookinfo [#[2166, 2167]](https://paste.fedoraproject.org/paste/5QWqt51DJzWme29brdn5BQ)
  * :question: python-ui-tests-parallel [#[423]](https://paste.fedoraproject.org/paste/TQCtHBCk~6gdEoPiI7o7MQ)
  * :question: run-python3-ui-tests [#[1216, 1217, 1218, 1219, 1220, 1210, 1211, 1212, 1213, 1214, 1215]](https://paste.fedoraproject.org/paste/XEIxZn821DjpgT6wdykSVw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#268](https://paste.fedoraproject.org/paste/D-CO642tZLCfUoAQq2EfFQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2510]](https://paste.fedoraproject.org/paste/EswZZwUCmOCbNBtT7jYe8w)
  * :heavy_check_mark: Istio-Upstream [#[1178]](https://paste.fedoraproject.org/paste/uq~eH13KOkT6VBQswb10JQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4128, 4129, 4126, 4127]](https://paste.fedoraproject.org/paste/T1Bsyqmbp0-w2DS1HEd1JQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[2369, 2370]](https://paste.fedoraproject.org/paste/L8lWzYoS4p9p78B-R8aXig)
  * :heavy_check_mark: install-bookinfo [#[2171, 2172]](https://paste.fedoraproject.org/paste/KCRSMrdrOUnDNb9wuKVx4w)
  * :question: python-ui-tests-parallel [#[424]](https://paste.fedoraproject.org/paste/qFHBsJ-b7HqhTPSLA3U1uA)
  * :question: run-python3-ui-tests [#[1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231]](https://paste.fedoraproject.org/paste/viXnSZfv0xpl8YOhkd4x5g)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#269](https://paste.fedoraproject.org/paste/j5JHy1BCJFQIlzsSdQo8jg)
  * :question: Istio-and-Kiali-on-Openshift [#[2514]](https://paste.fedoraproject.org/paste/orGe8ZJeM3tVrUi4B9FAbw)
  * :heavy_check_mark: Istio-Upstream [#[1182]](https://paste.fedoraproject.org/paste/54QauA1vfuXBmHUEQ9xn7Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4146, 4147, 4148, 4149]](https://paste.fedoraproject.org/paste/V2GdMoFc-KqrYoNMoI2eOg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2379, 2380]](https://paste.fedoraproject.org/paste/j6HmNte3UWjNSuMejn-nPw)
  * :heavy_check_mark: install-bookinfo [#[2181, 2182]](https://paste.fedoraproject.org/paste/nFAE9CtW-GsMTg~KNg3t1A)
  * :question: python-ui-tests-parallel [#[426]](https://paste.fedoraproject.org/paste/Zbr4hur7Twh3wvx2Vin~TA)
  * :question: run-python3-ui-tests [#[1248, 1249, 1250, 1251, 1252, 1253, 1243, 1244, 1245, 1246, 1247]](https://paste.fedoraproject.org/paste/95t~hcV2w6cMhuOSxEL~sA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#270](https://paste.fedoraproject.org/paste/vzu-fB1WXijZtz4BL8B0fw)
  * :question: Istio-and-Kiali-on-Openshift [#[2517]](https://paste.fedoraproject.org/paste/1HBmxvMAJiPcGD1OO36UHA)
  * :heavy_check_mark: Istio-Upstream [#[1185]](https://paste.fedoraproject.org/paste/V88758TVDNMG-tuLrgroGw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4160, 4161, 4156, 4159]](https://paste.fedoraproject.org/paste/ZFSaKmZk80489O0iBupnMg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2385, 2386]](https://paste.fedoraproject.org/paste/aQU9K~U9zhqNqkYFlEGMPQ)
  * :heavy_check_mark: install-bookinfo [#[2185, 2186]](https://paste.fedoraproject.org/paste/mi76i59fzdF0j1WkSKx8uw)
  * :question: python-ui-tests-parallel [#[427]](https://paste.fedoraproject.org/paste/Oi1AROT00D0FhsibWxbRtA)
  * :question: run-python3-ui-tests [#[1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265]](https://paste.fedoraproject.org/paste/2obZlUE5gToJxDb~jvTsnw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#271](https://paste.fedoraproject.org/paste/gV0qoG-zV7f9qejjg4IsWw)
  * :question: Istio-and-Kiali-on-Openshift [#[2526]](https://paste.fedoraproject.org/paste/CzxH9-X1~f5Fq17EKe74FQ)
  * :heavy_check_mark: Istio-Upstream [#[1194]](https://paste.fedoraproject.org/paste/K5gDCzoGIbAZC6BXaYarBQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4195, 4196, 4197, 4198]](https://paste.fedoraproject.org/paste/71rJK6H6yYdSFppfGIg9JQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[2411, 2412]](https://paste.fedoraproject.org/paste/DqDlujK9x5AwIwN8VfPn9g)
  * :heavy_check_mark: install-bookinfo [#[2200, 2199]](https://paste.fedoraproject.org/paste/hq0~sO6nWNR1~E~JO4w1qg)
  * :question: python-ui-tests-parallel [#[429]](https://paste.fedoraproject.org/paste/z4E41VXOIjC8DDnxJj3~eA)
  * :question: run-python3-ui-tests [#[1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1277, 1278, 1279]](https://paste.fedoraproject.org/paste/CIsZXdYQ7P2PjfKa1cJhNg)

**Comment by hhovsepy** [comment]
Failed test is because of https://issues.jboss.org/browse/KIALI-2354
The other one is random failure.

**Pull request merged**
