### PR TITLE
Retrieve correct list of Workloads from OC

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#573](https://paste.centos.org/view/9615a086 )
  * :question: upstream-istio-pipeline [#[475]](https://paste.centos.org/view/7d2eaaf5 )
  * :heavy_check_mark: build-kiali [#[2407]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[346]](Log omitted)
  * :heavy_check_mark: install-istio [#[1013]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8721, 8722, 8719]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6042, 6043, 6044]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4350, 4351]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1308]](https://paste.centos.org/view/b10ea049 )
  * :question: run-kiali-ui-tests [#[22112, 22113, 22114, 22115, 22116, 22117, 22118, 22119, 22103, 22104, 22105, 22106, 22107, 22108, 22109, 22110, 22111]](https://paste.centos.org/view/00373078 https://paste.centos.org/view/a695180a )

**Comment by hhovsepy** [comment]
manual rerun of tests pass (the workload lists tests)

**Pull request merged**
