### PR TITLE
Switched tests to bookinfo3

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#661](https://paste.centos.org/view/0416aa5f )
  * :question: upstream-istio-pipeline [#[800]](https://paste.centos.org/view/e59d1b01 )
  * :heavy_check_mark: build-kiali [#[3442]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[982]](Log omitted)
  * :heavy_check_mark: install-istio [#[1765]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13320, 13317, 13318, 13319]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9368, 9369, 9370, 9367]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6800, 6801, 6802]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1909]](https://paste.centos.org/view/7a03cad8 )
  * :question: run-kiali-ui-tests [#[32518, 32519, 32520, 32521, 32522, 32523, 32524, 32525, 32526, 32527, 32528, 32529, 32530, 32531, 32532, 32533, 32534]](https://paste.centos.org/view/e1befdf2 https://paste.centos.org/view/a3efe40e )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#662](https://paste.centos.org/view/5c60ef94 )
  * :question: upstream-istio-pipeline [#[801]](https://paste.centos.org/view/87c2ea3c )
  * :heavy_check_mark: build-kiali [#[3443]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[983]](Log omitted)
  * :heavy_check_mark: install-istio [#[1766]](Log omitted)
  * :heavy_check_mark: clean-environment [#[13321, 13322, 13323, 13324]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9371, 9372, 9373, 9374]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[6803, 6804, 6805]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1910]](https://paste.centos.org/view/f5230f4f )
  * :question: run-kiali-ui-tests [#[32544, 32545, 32546, 32547, 32548, 32549, 32550, 32551, 32535, 32536, 32537, 32538, 32539, 32540, 32541, 32542, 32543]](https://paste.centos.org/view/91ea4bf6 )

**Pull request merged**
