### PR TITLE
Added Workloads tests. Added more checks on Services tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#106](https://paste.fedoraproject.org/paste/sUPu1TVTl8GseSTKua93rw)
  * :question: python-ui-tests-parallel [#[30]](https://paste.fedoraproject.org/paste/S4ZQ0tAvLmmDWAy5CNNVgA)
  * :question: run-python-ui-tests [#[980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990]](https://paste.fedoraproject.org/paste/yP5L9Gaw5E98BukOFqYHZQ)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#107](https://paste.fedoraproject.org/paste/-Pv~j2O16HGY49K4kr2eTw)
  * :question: python-ui-tests-parallel [#[31]](https://paste.fedoraproject.org/paste/9Cj87njd7UDoIkftukGiEg)
  * :question: run-python-ui-tests [#[992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 991]](https://paste.fedoraproject.org/paste/K7I111uEJfxRV1sNkgf0BQ)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#108](https://paste.fedoraproject.org/paste/R6EItkz55E8eN8QIkDcFEQ)
  * :question: python-ui-tests-parallel [#[32]](https://paste.fedoraproject.org/paste/RiULyzdcGjGbgVleEznJYQ)
  * :question: run-python-ui-tests [#[1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012]](https://paste.fedoraproject.org/paste/huAHs9pvCwijpKUck8Dhug)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#109](https://paste.fedoraproject.org/paste/ZkcSfXSJ8mEHESVmaI0w1w)
  * :heavy_check_mark: python-ui-tests-parallel [#[33]](https://paste.fedoraproject.org/paste/sjU1kL0Ld0lMHMFXydAbNg)
  * :heavy_check_mark: run-python-ui-tests [#[1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023]](https://paste.fedoraproject.org/paste/iiPPxmyLDz3Tv8yRvb0HEw)

**Pull request merged**
