### PR TITLE
Graph page Hide/Show filters automated.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#567](https://paste.centos.org/view/46578751 )
  * :question: upstream-istio-pipeline [#[445]](https://paste.centos.org/view/35330efe )
  * :heavy_check_mark: build-kiali [#[2327]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[290]](Log omitted)
  * :heavy_check_mark: install-istio [#[967]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8509, 8510, 8511]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5848, 5849, 5850]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4227, 4228]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1274]](https://paste.centos.org/view/f99f5d80 )
  * :question: run-kiali-ui-tests [#[21536, 21537, 21538, 21539, 21540, 21541, 21542, 21543, 21544, 21545, 21546, 21530, 21531, 21532, 21533, 21534, 21535]](https://paste.centos.org/view/3dae906f https://paste.centos.org/view/ab2ec66b https://paste.centos.org/view/51ddb50d )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#568](https://paste.centos.org/view/9fa5d51c )
  * :question: upstream-istio-pipeline [#[454]](https://paste.centos.org/view/20c72fe6 )
  * :heavy_check_mark: build-kiali [#[2350]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[307]](Log omitted)
  * :heavy_check_mark: install-istio [#[977]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8555, 8556, 8557]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5891, 5892, 5893]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4254, 4255]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1287]](https://paste.centos.org/view/6b61d3b4 )
  * :question: run-kiali-ui-tests [#[21760, 21761, 21762, 21763, 21764, 21765, 21766, 21767, 21751, 21752, 21753, 21754, 21755, 21756, 21757, 21758, 21759]](https://paste.centos.org/view/ee695e50 )

**Pull request merged**
