### PR TITLE
Filter items in REST and OC results for Workloads.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#681](https://paste.centos.org/view/1ff1ac39 )
  * :question: upstream-istio-pipeline [#[904]](https://paste.centos.org/view/62318197 )
  * :heavy_check_mark: build-kiali [#[3709]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1141]](Log omitted)
  * :heavy_check_mark: install-istio [#[1936]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14753, 14754, 14755, 14756]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10608, 10605, 10606, 10607]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7905, 7906, 7907]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2078]](https://paste.centos.org/view/6d117672 )
  * :question: run-kiali-ui-tests [#[35552, 35553, 35554, 35555, 35539, 35540, 35541, 35542, 35543, 35544, 35545, 35546, 35547, 35548, 35549, 35550, 35551]](https://paste.centos.org/view/f62ed478 https://paste.centos.org/view/4c139b5e https://paste.centos.org/view/bb0f60b1 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#682](https://paste.centos.org/view/852296ad )
  * :question: upstream-istio-pipeline [#[906]](https://paste.centos.org/view/44b77762 )
  * :heavy_check_mark: build-kiali [#[3712]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1144]](Log omitted)
  * :heavy_check_mark: install-istio [#[1938]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14768, 14769, 14766, 14767]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10617, 10618, 10619, 10620]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7914, 7915, 7916]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2081]](https://paste.centos.org/view/ee8a07d4 )
  * :question: run-kiali-ui-tests [#[35590, 35591, 35592, 35593, 35594, 35595, 35596, 35597, 35598, 35599, 35600, 35601, 35602, 35603, 35604, 35605, 35606]](https://paste.centos.org/view/016d1254 https://paste.centos.org/view/013886bc )

**Pull request merged**
