### PR TITLE
Added more check for AuthPolicy

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#588](https://paste.centos.org/view/99b700fb )
  * :question: upstream-istio-pipeline [#[521]](https://paste.centos.org/view/6a7d1d9f )
  * :heavy_check_mark: build-kiali [#[2510]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[419]](Log omitted)
  * :heavy_check_mark: install-istio [#[1086]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9088, 9085, 9087]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6304, 6305, 6302]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4512, 4511]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1365]](https://paste.centos.org/view/6e9c0a84 )
  * :question: run-kiali-ui-tests [#[23072, 23073, 23057, 23058, 23059, 23060, 23061, 23062, 23063, 23064, 23065, 23066, 23067, 23068, 23069, 23070, 23071]](https://paste.centos.org/view/4cd65a6d https://paste.centos.org/view/8a40c5c0 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#598](https://paste.centos.org/view/e0ba5b14 )
  * :question: upstream-istio-pipeline [#[572]](https://paste.centos.org/view/d01b0ec5 )
  * :heavy_check_mark: build-kiali [#[2609]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[482]](Log omitted)
  * :heavy_check_mark: install-istio [#[1173]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9514, 9515, 9516]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6579, 6580, 6581]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4691, 4692]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1418]](https://paste.centos.org/view/edd5b9c7 )
  * :question: run-kiali-ui-tests [#[23968, 23969, 23970, 23971, 23972, 23973, 23974, 23975, 23959, 23960, 23961, 23962, 23963, 23964, 23965, 23966, 23967]](https://paste.centos.org/view/a40dc8b6 https://paste.centos.org/view/e542fe26 https://paste.centos.org/view/ea60e2cc )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#600](https://paste.centos.org/view/654bfa0a )
  * :question: upstream-istio-pipeline [#[574]](https://paste.centos.org/view/d544fe8a )
  * :heavy_check_mark: build-kiali [#[2611]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[484]](Log omitted)
  * :heavy_check_mark: install-istio [#[1177]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9529, 9530, 9531]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6586, 6587, 6588]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4696, 4695]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1420]](https://paste.centos.org/view/32e675e0 )
  * :question: run-kiali-ui-tests [#[24000, 24001, 24002, 24003, 24004, 24005, 24006, 24007, 24008, 24009, 24010, 24011, 23995, 23996, 23997, 23998, 23999]](https://paste.centos.org/view/cac12213 https://paste.centos.org/view/f8b76946 )

**Comment by hhovsepy** [comment]
failing tests are not the changed ones and are random related to poor performance

**Pull request merged**
