### PR TITLE
Fixed failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#277](https://paste.fedoraproject.org/paste/9LH1UKRIG5PcqxlGCYnYfw)
  * :question: Istio-and-Kiali-on-Openshift [#[2690]](https://paste.fedoraproject.org/paste/vkulr8EHkx-Usx682GS6Bw)
  * :heavy_check_mark: Istio-Upstream [#[1358]](https://paste.fedoraproject.org/paste/XiUUI-qsHRR-sVZFKFCxog)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4873, 4875, 4876, 4877]](https://paste.fedoraproject.org/paste/rI3sgoUSJ4R4QbCcNUlPwg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2848, 2846]](https://paste.fedoraproject.org/paste/22XYRhFKo8PbSrpYnWADxg)
  * :heavy_check_mark: install-bookinfo [#[2454, 2455]](https://paste.fedoraproject.org/paste/ejqhZr93JMJMMbBbzE0EaA)
  * :question: python-ui-tests-parallel [#[484]](https://paste.fedoraproject.org/paste/sAA4TVEgt9qpSlT7Jipe4A)
  * :question: run-python3-ui-tests [#[1856, 1857, 1858, 1859, 1860, 1861, 1862, 1852, 1853, 1854, 1855]](https://paste.fedoraproject.org/paste/uL~6AJFVvEYllZ01YsuxPg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#279](https://paste.fedoraproject.org/paste/kXwQr926yPLeLA2cQlGx8Q)
  * :question: Istio-and-Kiali-on-Openshift [#[2700]](https://paste.fedoraproject.org/paste/SIa5jAOMwqbWeSSrCiS3vQ)
  * :heavy_check_mark: Istio-Upstream [#[1368]](https://paste.fedoraproject.org/paste/uE63QyfSKQrPx48nAAZLrQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4904, 4905, 4906, 4903]](https://paste.fedoraproject.org/paste/kRiZAMIrD08iPI1nBwZ3Qg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2869, 2870]](https://paste.fedoraproject.org/paste/aBSoEAGLTtEDDJJzBAhpfA)
  * :heavy_check_mark: install-bookinfo [#[2464, 2465]](https://paste.fedoraproject.org/paste/1E0cohl9VK3EGJ5Tpi6kkg)
  * :question: python-ui-tests-parallel [#[486]](https://paste.fedoraproject.org/paste/N2duCn9vksaSSTH1nY1c4A)
  * :question: run-python3-ui-tests [#[1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884]](https://paste.fedoraproject.org/paste/SKRGTlf5AliCsEszCwPx2g)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#280](https://paste.fedoraproject.org/paste/dEZdP2-qvdLDQlQOhtsBbg)
  * :question: Istio-and-Kiali-on-Openshift [#[2711]](https://paste.fedoraproject.org/paste/UfGB7dSYNvkZtgFZ2v42EA)
  * :heavy_check_mark: Istio-Upstream [#[1379]](https://paste.fedoraproject.org/paste/uYhhlhHjrsEFZxz8QnhEiQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[4946, 4947, 4948, 4949]](https://paste.fedoraproject.org/paste/pD0oVbAPVmFcrp2NZ3LwHA)
  * :heavy_check_mark: Kiali-on-Openshift [#[2894, 2895]](https://paste.fedoraproject.org/paste/8wcUZX4pmjpCLghF3pKs6Q)
  * :heavy_check_mark: install-bookinfo [#[2481, 2482]](https://paste.fedoraproject.org/paste/ntXTN1lT1KJGzPPJyt0kJg)
  * :question: python-ui-tests-parallel [#[492]](https://paste.fedoraproject.org/paste/A56wVJ8habSMAne-b7NmZw)
  * :question: run-python3-ui-tests [#[1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950]](https://paste.fedoraproject.org/paste/gzxN8VtujmTem~80ylTd9Q)

**Comment by hhovsepy** [comment]
Failing tests are logged as jira issues:
https://issues.jboss.org/browse/KIALI-2487
https://issues.jboss.org/browse/KIALI-2486

**Pull request merged**
