### PR TITLE
Changed XPaths according to UI

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#436](https://paste.fedoraproject.org/paste/cXPmtpNos7LVmT1SEQrdyg)
  * :question: upstream-pipeline [#[402]](https://paste.fedoraproject.org/paste/KTs~AkDU2dEfhdUhnExV2w)
  * :heavy_check_mark: build-kiali [#[655]](https://paste.fedoraproject.org/paste/hOdP4fkQ4V6ZoVILe1R5vg)
  * :heavy_check_mark: install-maistra [#[1177]](https://paste.fedoraproject.org/paste/1pYu86N1~jX79blhxDwkSA)
  * :heavy_check_mark: clean-environment [#[2600, 2601, 2602, 2599]](https://paste.fedoraproject.org/paste/WlFyMwyFsbotBYQnaa5kbw)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1376, 1377, 1378]](https://paste.fedoraproject.org/paste/sXJZslTzNxpjycEx2uemAA)
  * :heavy_check_mark: install-bookinfo [#[1310, 1311]](https://paste.fedoraproject.org/paste/byQRAL2qXUHP8vvlZqNfgg)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[717]](https://paste.fedoraproject.org/paste/LIeEVcehw8zi1cXn5SKMcA)
  * :question: run-kiali-ui-tests-parallel [#[312]](https://paste.fedoraproject.org/paste/igAj2L8NTH8ET0u5MOBudA)
  * :question: run-kiali-ui-tests [#[5216, 5217, 5218, 5219, 5220, 5221, 5222, 5205, 5206, 5207, 5208, 5209, 5210, 5211, 5212, 5213, 5214]](https://paste.fedoraproject.org/paste/Nja7tr01k5GGKcbK~9nHWg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#437](https://paste.fedoraproject.org/paste/itI7uunlpiCI6EcGmMTq~Q)
  * :question: upstream-pipeline [#[403]](https://paste.fedoraproject.org/paste/qUHxAmxjXPi67H59wBXzGg)
  * :heavy_check_mark: build-kiali [#[656]](https://paste.fedoraproject.org/paste/Gi~uSbtz9g3dUmuOK4eS6w)
  * :heavy_check_mark: install-maistra [#[1178]](https://paste.fedoraproject.org/paste/Nay4nO2pAlrbH5iBOGGtWQ)
  * :heavy_check_mark: clean-environment [#[2603, 2604, 2605, 2606]](https://paste.fedoraproject.org/paste/mpGgCdsc~yTelg7EdlOIIQ)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1379, 1380, 1381]](https://paste.fedoraproject.org/paste/1ZQZc0xl-kYLypCI0UDMTQ)
  * :heavy_check_mark: install-bookinfo [#[1312, 1313]](https://paste.fedoraproject.org/paste/~hf03fmi2Yz9Ir6MT2jx9w)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[718]](https://paste.fedoraproject.org/paste/qlbw058P75thjk-azO1YKQ)
  * :question: run-kiali-ui-tests-parallel [#[314]](https://paste.fedoraproject.org/paste/iDKhmSabtV-dJB8kLZ4l~g)
  * :question: run-kiali-ui-tests [#[5249, 5250, 5251, 5252, 5253, 5254, 5256, 5233, 5234, 5235, 5236, 5237, 5238, 5239, 5240, 5241, 5242]](https://paste.fedoraproject.org/paste/tekLIT2Z9k~Wls1msNxN~g)

**Pull request merged**
