### PR TITLE
Added Label checks for Services and Workloads

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#164](https://paste.fedoraproject.org/paste/kgITvuCEXsreJ4txBzu-fA)
  * :question: python-ui-tests-parallel [#[146]](https://paste.fedoraproject.org/paste/v-H2YAN0gJ6H7pcAWday1A)
  * :question: run-python-ui-tests [#[2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268]](https://paste.fedoraproject.org/paste/o6YvX19JwDkbejPnfio8Fg)

**Comment by hhovsepy** [comment]
Only failure is because of bug: https://issues.jboss.org/browse/KIALI-1851

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#171](https://paste.fedoraproject.org/paste/H4KE6bh9vQbNzuzdfaUciw)
  * :question: python-ui-tests-parallel [#[163]](https://paste.fedoraproject.org/paste/~zD4MF1boYfTRZaxLMJQbA)
  * :question: run-python-ui-tests [#[2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455]](https://paste.fedoraproject.org/paste/0J0Z9jP~RDxs1K7ECpdXOg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#175](https://paste.fedoraproject.org/paste/SKOOJXtyBzdqR2j~IbvRyQ)
  * :question: python-ui-tests-parallel [#[168]](https://paste.fedoraproject.org/paste/~fnBs2aC3WVlJ6WE8oBoNg)
  * :question: run-python-ui-tests [#[2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510]](https://paste.fedoraproject.org/paste/MGInQKK0-7U~EGWYCmVURw)

**Pull request merged**
