### PR TITLE
Added Health & IstioSidecar  testcases for Application.py :UI

### PR DESCRIPTION
**Pull request by pbajjuri20**

### CODE REVIEW

**Comment by pbajjuri20** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#678](https://paste.centos.org/view/1e5bdafd )
  * :question: upstream-istio-pipeline [#[899]](https://paste.centos.org/view/29f87e5a )
  * :heavy_check_mark: build-kiali [#[3700]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1133]](Log omitted)
  * :heavy_check_mark: install-istio [#[1928]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14704, 14706, 14700, 14702]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10561, 10563, 10565, 10559]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7865, 7867, 7863]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2071]](https://paste.centos.org/view/b0186f34 )
  * :question: run-kiali-ui-tests [#[35424, 35425, 35409, 35410, 35411, 35412, 35413, 35414, 35415, 35416, 35417, 35418, 35419, 35420, 35421, 35422, 35423]](https://paste.centos.org/view/96b5bac7 https://paste.centos.org/view/a88f8311 )

**Comment by hhovsepy** [comment]
kiali_qe/tests/test_applications_page.py:4: in <module>
    from kiali_qe.components.enums import (
E   ImportError: cannot import name 'AppIstioSideCar'

**Comment by pbajjuri20** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
please squash the commits

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#680](https://paste.centos.org/view/21933b03 )
  * :question: upstream-istio-pipeline [#[901]](https://paste.centos.org/view/652f6f5a )
  * :heavy_check_mark: build-kiali [#[3702]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1134]](Log omitted)
  * :heavy_check_mark: install-istio [#[1930]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14707, 14708, 14709, 14710]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10568, 10569, 10566, 10567]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7868, 7869, 7870]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2072]](https://paste.centos.org/view/1eafa42f )
  * :question: run-kiali-ui-tests [#[35432, 35433, 35434, 35435, 35436, 35437, 35438, 35439, 35440, 35441, 35443, 35444, 35445, 35446, 35447, 35448, 35449]](https://paste.centos.org/view/b74e720b https://paste.centos.org/view/1bcf1089 )

**Pull request merged**
