### PR TITLE
Create Idle service for Overview tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#592](https://paste.centos.org/view/2ba5a413 )
  * :question: upstream-istio-pipeline [#[551]](https://paste.centos.org/view/c53adc5b )
  * :heavy_check_mark: build-kiali [#[2565]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[455]](Log omitted)
  * :heavy_check_mark: install-istio [#[1140]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9344, 9345, 9343]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6464, 6462, 6463]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4616, 4617]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1391]](https://paste.centos.org/view/fc4382b7 )
  * :question: run-kiali-ui-tests [#[23499, 23500, 23501, 23502, 23503, 23504, 23505, 23506, 23507, 23508, 23509, 23510, 23511, 23512, 23513, 23514, 23515]](https://paste.centos.org/view/c2c4a04d https://paste.centos.org/view/60b110a2 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#606](https://paste.centos.org/view/889afb6e )
  * :red_circle: upstream-istio-pipeline [#[612]](https://paste.centos.org/view/48f779bc )
  * :heavy_check_mark: build-kiali [#[2718]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[537]](Log omitted)
  * :red_circle: install-istio [#[1292]](https://paste.centos.org/view/ba473c38 )
  * :heavy_check_mark: clean-environment [#[10005]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#607](https://paste.centos.org/view/0c31cb61 )
  * :question: upstream-istio-pipeline [#[615]](https://paste.centos.org/view/dfad98e7 )
  * :heavy_check_mark: build-kiali [#[2726]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[541]](Log omitted)
  * :heavy_check_mark: install-istio [#[1299]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10029, 10030, 10031]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6849, 6850, 6851]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4868, 4869]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1482]](https://paste.centos.org/view/b06c169e )
  * :question: run-kiali-ui-tests [#[25071, 25072, 25073, 25074, 25075, 25076, 25077, 25078, 25079, 25080, 25081, 25082, 25083, 25084, 25085, 25086, 25087]](https://paste.centos.org/view/c068c55e https://paste.centos.org/view/f2d97ffb https://paste.centos.org/view/0129cd40 https://paste.centos.org/view/a1987193 https://paste.centos.org/view/c8377929 )

**Comment by hhovsepy** [comment]
Overview tests pass, failures are timeouts in other tests.

**Pull request merged**
