### PR TITLE
Support Selector in Service details.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#362](https://paste.fedoraproject.org/paste/YJoW5qWWchixp07GuGcuYQ)
  * :question: Istio-and-Kiali-on-Openshift [#[97]](https://paste.fedoraproject.org/paste/9F3okuaZl0i6rnqlB-5cHA)
  * :heavy_check_mark: Istio-Upstream [#[2046]](https://paste.fedoraproject.org/paste/~lXJYeBFtrOn-seh~f9a6g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7477, 7478]](https://paste.fedoraproject.org/paste/nCj8stw39ZJPKDZuL1yxiw)
  * :heavy_check_mark: Kiali-on-Openshift [#[345, 347]](https://paste.fedoraproject.org/paste/-WTzibZSmFEjQLZ-kG5WVg)
  * :heavy_check_mark: old-bookinfo [#[3261]](https://paste.fedoraproject.org/paste/NZMxrjZLzFlwPH2ZCfBQgw)
  * :question: python-ui-tests-parallel [#[710]](https://paste.fedoraproject.org/paste/ULtF1aCSjlEvr1bh6bCoEg)
  * :question: run-python3-ui-tests [#[4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4373, 4374]](https://paste.fedoraproject.org/paste/kzMsjNrr-Pqw5ef9GI6a9A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#363](https://paste.fedoraproject.org/paste/GPR~R6VTdPoR9A5yD39OBw)
  * :question: Istio-and-Kiali-on-Openshift [#[100]](https://paste.fedoraproject.org/paste/q7K7BjU8WgLzys4Y7Zl58A)
  * :heavy_check_mark: Istio-Upstream [#[2049]](https://paste.fedoraproject.org/paste/jIgKgVQ-KDqSaMlELzsStg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7486, 7487]](https://paste.fedoraproject.org/paste/Vr6zexNz0eyvEVKoSnJZ~w)
  * :heavy_check_mark: Kiali-on-Openshift [#[354, 355]](https://paste.fedoraproject.org/paste/8SH5uxxRSPkTuSwRiK7QIQ)
  * :heavy_check_mark: old-bookinfo [#[3263]](https://paste.fedoraproject.org/paste/hdnrQYDtAZIbyOIRhoweIA)
  * :question: python-ui-tests-parallel [#[712]](https://paste.fedoraproject.org/paste/xAigWwVE5fiP5YJcM7ofsg)
  * :question: run-python3-ui-tests [#[4385, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4394, 4396]](https://paste.fedoraproject.org/paste/39jzJT19lTsrDTsPDEwDQA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#364](https://paste.fedoraproject.org/paste/-uBssMMXvaMniOMGgNOiKQ)
  * :question: Istio-and-Kiali-on-Openshift [#[101]](https://paste.fedoraproject.org/paste/RXFM2iFvAGNIzgLpTNNmqw)
  * :heavy_check_mark: Istio-Upstream [#[2050]](https://paste.fedoraproject.org/paste/4F8QYyiPx68dmOsu8VqHNQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7488, 7489]](https://paste.fedoraproject.org/paste/E1aderCdSVUpesV7JFUlrQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[357, 358]](https://paste.fedoraproject.org/paste/yZnT~NJsmdDnmC8xvlP83g)
  * :heavy_check_mark: old-bookinfo [#[3264]](https://paste.fedoraproject.org/paste/b7s~V70sq9GEngQsbqLE9Q)
  * :question: python-ui-tests-parallel [#[713]](https://paste.fedoraproject.org/paste/kANhxHJx7AGyvH6xapXMxg)
  * :question: run-python3-ui-tests [#[4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407]](https://paste.fedoraproject.org/paste/TLgoLv526GDsJjD7LTQmYA)

**Comment by hhovsepy** [comment]
Random failures

**Pull request merged**
