### PR TITLE
Workload_health_enums

### PR DESCRIPTION
**Pull request by pbajjuri20**
Verify with test_workload_page.py::test_workloads_filter_health

wd

### CODE REVIEW

**Review by ScriptingShrimp — COMMENTED** [review]
The branch `pbajjuri20:pbajjuri_workload_enums` no longer exists, so I'm unable to verify.

**Comment by pbajjuri20** [comment]
I will created the New PR, https://github.com/Kiali-QE/kiali-qe-python/pull/443. Branch is deleted

**Comment by ScriptingShrimp** [comment]
still have same error, IDK why
`Fail: AssertionError: Workload Tooltip Health HealthType.IDLE is not equal to UI Health HealthType.HEALTHY for istiod`

**Comment by ScriptingShrimp** [comment]
Verify with test_workload_page.py::test_workloads_filter_health
still have same error IDK why
`Fail: AssertionError: Workload Tooltip Health HealthType.IDLE is not equal to UI Health HealthType.HEALTHY for istiod`

**Pull request closed without merging**
