### PR TITLE
Removed already deleted Istio Objects.Tests for VS and DR config overview pages.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#627](https://paste.centos.org/view/801e8191 )
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#628](https://paste.centos.org/view/ee6ad97b )
  * :question: upstream-pipeline [#[1337]](https://paste.centos.org/view/7d2f8c75 )
  * :heavy_check_mark: build-kiali [#[3023]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[714]](Log omitted)
  * :heavy_check_mark: install-maistra [#[2302]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11235, 11236, 11237]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7656, 7657, 7655]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5392, 5391]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1648]](https://paste.centos.org/view/a7143d97 )
  * :question: run-kiali-ui-tests [#[27904, 27905, 27906, 27907, 27908, 27909, 27910, 27911, 27912, 27913, 27914, 27915, 27916, 27917, 27918, 27919, 27920]](https://paste.centos.org/view/1c3bc4a8 https://paste.centos.org/view/0aa6d650 https://paste.centos.org/view/e5c7e466 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#629](https://paste.centos.org/view/86f8c192 )
  * :question: upstream-pipeline [#[1338]](https://paste.centos.org/view/49a02691 )
  * :heavy_check_mark: build-kiali [#[3024]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[715]](Log omitted)
  * :heavy_check_mark: install-maistra [#[2303]](Log omitted)
  * :heavy_check_mark: clean-environment [#[11242, 11243, 11244]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7660, 7661, 7662]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5395, 5396]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1650]](https://paste.centos.org/view/244aba4b )
  * :question: run-kiali-ui-tests [#[27941, 27942, 27943, 27944, 27945, 27946, 27947, 27948, 27949, 27950, 27951, 27952, 27953, 27954, 27955, 27956, 27957]](https://paste.centos.org/view/4841124e https://paste.centos.org/view/6f845aca https://paste.centos.org/view/52207386 )

**Pull request merged**
