### PR TITLE
Added Masthead tooltip test.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#530](https://paste.centos.org/view/b5a95dff )
  * :question: upstream-istio-pipeline [#[282]](https://paste.centos.org/view/0f900df1 )
  * :heavy_check_mark: build-kiali [#[1867]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[23]](Log omitted)
  * :heavy_check_mark: install-istio [#[557]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7088, 7089, 7086, 7087]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4699, 4700, 4701]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3467, 3468]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1978]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1001]](https://paste.centos.org/view/7bc913ef )
  * :question: run-kiali-ui-tests [#[16896, 16897, 16898, 16899, 16900, 16901, 16902, 16903, 16904, 16905, 16906, 16890, 16891, 16892, 16893, 16894, 16895]](https://paste.centos.org/view/adbf3090 https://paste.centos.org/view/d4e8d048 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#534](https://paste.centos.org/view/9905e19b )
  * :question: upstream-istio-pipeline [#[301]](https://paste.centos.org/view/905df677 )
  * :heavy_check_mark: build-kiali [#[1937]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[56]](Log omitted)
  * :heavy_check_mark: install-istio [#[627]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7280, 7281, 7278, 7279]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4828, 4829, 4830]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3544, 3545]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[2033]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1032]](https://paste.centos.org/view/2758e986 )
  * :question: run-kiali-ui-tests [#[17417, 17418, 17419, 17420, 17421, 17422, 17423, 17424, 17425, 17426, 17427, 17428, 17429, 17430, 17431, 17432, 17433]](https://paste.centos.org/view/66f193ed https://paste.centos.org/view/1879c3af )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#535](https://paste.centos.org/view/e4ca52d0 )
  * :question: upstream-istio-pipeline [#[302]](https://paste.centos.org/view/a43deb28 )
  * :heavy_check_mark: build-kiali [#[1940]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[57]](Log omitted)
  * :heavy_check_mark: install-istio [#[632]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7288, 7289, 7290, 7287]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4836, 4837, 4838]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3548, 3549]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[2036]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1033]](https://paste.centos.org/view/68717250 )
  * :red_circle: run-kiali-ui-tests [#[17440, 17441, 17442, 17443, 17444, 17445, 17446, 17447, 17448, 17449, 17450, 17434, 17435, 17436, 17437, 17438, 17439]](https://paste.centos.org/view/543d8b0a https://paste.centos.org/view/5f2cf051 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#536](https://paste.centos.org/view/83de99e0 )
  * :question: upstream-istio-pipeline [#[305]](https://paste.centos.org/view/f033c0aa )
  * :heavy_check_mark: build-kiali [#[1945]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[61]](Log omitted)
  * :heavy_check_mark: install-istio [#[635]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7304, 7305, 7306, 7307]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4848, 4849, 4850]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3556, 3557]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[2040]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1037]](https://paste.centos.org/view/ca2b3da6 )
  * :question: run-kiali-ui-tests [#[17504, 17505, 17506, 17507, 17508, 17509, 17510, 17512, 17513, 17514, 17515, 17516, 17517, 17518, 17501, 17502, 17503]](https://paste.centos.org/view/cef5314f https://paste.centos.org/view/47ce9cb9 )

**Pull request merged**
