### PR TITLE
Graph Overview links tests for Service, Workload and Apps details pages.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#520](https://paste.centos.org/view/23e54792 )
  * :question: upstream-istio-pipeline [#[220]](https://paste.centos.org/view/a2890340 )
  * :heavy_check_mark: build-kiali [#[1691]](Log omitted)
  * :heavy_check_mark: install-istio [#[430]](Log omitted)
  * :heavy_check_mark: clean-environment [#[6378, 6389, 6390, 6391]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4161, 4163, 4159]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3116, 3117]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1770]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[870]](https://paste.centos.org/view/5d4ed4ab )
  * :question: run-kiali-ui-tests [#[14688, 14689, 14690, 14691, 14692, 14693, 14694, 14695, 14696, 14697, 14698, 14699, 14700, 14701, 14702, 14703, 14714]](https://paste.centos.org/view/0b367035 https://paste.centos.org/view/3c6786fb https://paste.centos.org/view/069cfba9 https://paste.centos.org/view/6cc7c78a https://paste.centos.org/view/d58efe31 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#521](https://paste.centos.org/view/6dda1ff7 )
  * :question: upstream-istio-pipeline [#[221]](https://paste.centos.org/view/493dd67f )
  * :heavy_check_mark: build-kiali [#[1695]](Log omitted)
  * :heavy_check_mark: install-istio [#[431]](Log omitted)
  * :heavy_check_mark: clean-environment [#[6409, 6410, 6411, 6404]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4176, 4178, 4175]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3124, 3125]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1775]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[873]](https://paste.centos.org/view/d9e11f3f )
  * :question: run-kiali-ui-tests [#[14752, 14753, 14755, 14738, 14739, 14740, 14741, 14742, 14743, 14744, 14745, 14746, 14747, 14748, 14749, 14750, 14751]](https://paste.centos.org/view/5eff7876 )

**Pull request merged**
