### PR TITLE
Added Sort options tests

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#370](https://paste.fedoraproject.org/paste/6vqU9PthOFnWXuqB0vDKYA)
  * :question: Istio-and-Kiali-on-Openshift [#[148]](https://paste.fedoraproject.org/paste/rbYBgLcYQoOTuN0dIiuwIQ)
  * :heavy_check_mark: Istio-Upstream [#[2097]](https://paste.fedoraproject.org/paste/heOXfQWl0B~Pb4noyCB7Lw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7600, 7599]](https://paste.fedoraproject.org/paste/byNSRggGYizaoLoPzA~OZQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[460, 461]](https://paste.fedoraproject.org/paste/4VEVDff6YDd~iPPOvuiaNg)
  * :heavy_check_mark: old-bookinfo [#[3307]](https://paste.fedoraproject.org/paste/1dPrdggAku0rFVpsh4bAXg)
  * :question: python-ui-tests-parallel [#[728]](https://paste.fedoraproject.org/paste/rmWOv4ingskRNUbfDz8F9w)
  * :question: run-python3-ui-tests [#[4562, 4563, 4564, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4572]](https://paste.fedoraproject.org/paste/cCK56yNLI0aExNSvN3Fhuw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#371](https://paste.fedoraproject.org/paste/BOpvpA1g4T~UNX5XwOO2bg)
  * :question: Istio-and-Kiali-on-Openshift [#[159]](https://paste.fedoraproject.org/paste/fEWrYQa8FjmgwtJe3UrMWA)
  * :heavy_check_mark: Istio-Upstream [#[2108]](https://paste.fedoraproject.org/paste/3eJdA49YVSfcPHfwgXfEuQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7632, 7633]](https://paste.fedoraproject.org/paste/--1w2jz4Z92IJKmegsL-0A)
  * :heavy_check_mark: Kiali-on-Openshift [#[493, 494]](https://paste.fedoraproject.org/paste/FXLpSir4bm0IWeD5MQMruw)
  * :heavy_check_mark: old-bookinfo [#[3318]](https://paste.fedoraproject.org/paste/OLJmTqFj5HpNW8TpS2mC7g)
  * :question: python-ui-tests-parallel [#[731]](https://paste.fedoraproject.org/paste/L-BpD3bsJZo1CYhXsdZGkw)
  * :question: run-python3-ui-tests [#[4595, 4596, 4597, 4598, 4599, 4600, 4601, 4602, 4603, 4604, 4605]](https://paste.fedoraproject.org/paste/bF8UDJng-KqhNceWRe9lQg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#373](https://paste.fedoraproject.org/paste/L0Opw9vuwYWL8YgPFC6Aew)
  * :question: Istio-and-Kiali-on-Openshift [#[167]](https://paste.fedoraproject.org/paste/DGt8AgAY54hqtjEwsyeq6Q)
  * :heavy_check_mark: Istio-Upstream [#[2116]](https://paste.fedoraproject.org/paste/uFY6FZX2EF~gAS2Ra1RETA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7656, 7655]](https://paste.fedoraproject.org/paste/zWWyqOSa9ICI1df20D7Xgw)
  * :heavy_check_mark: Kiali-on-Openshift [#[516, 517]](https://paste.fedoraproject.org/paste/I8YEMQHLnr3zCSEKQ5LuxA)
  * :heavy_check_mark: old-bookinfo [#[3326]](https://paste.fedoraproject.org/paste/BISZKAOqq7xTsktLf40kRg)
  * :question: python-ui-tests-parallel [#[734]](https://paste.fedoraproject.org/paste/Ipx~MqQs6~qrlViX~Q1sQQ)
  * :question: run-python3-ui-tests [#[4640, 4630, 4631, 4632, 4633, 4634, 4635, 4636, 4637, 4638, 4639]](https://paste.fedoraproject.org/paste/vQhP1QbwVYASZWBffm5CbA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#374](https://paste.fedoraproject.org/paste/v-9hxhVbZDn86WO3no1ShQ)
  * :question: Istio-and-Kiali-on-Openshift [#[168]](https://paste.fedoraproject.org/paste/2-aocrk58CM~DiwInG3A9A)
  * :heavy_check_mark: Istio-Upstream [#[2117]](https://paste.fedoraproject.org/paste/o-4eTAamvgDohHDLd92uRQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7657, 7658]](https://paste.fedoraproject.org/paste/bNRUj5OQUOly9GEJava3RQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[518, 519]](https://paste.fedoraproject.org/paste/7~oxbIlNXWDan-9ovw4dLg)
  * :heavy_check_mark: old-bookinfo [#[3327]](https://paste.fedoraproject.org/paste/AYs9TYFPZoCZxTdyUCNAwg)
  * :question: python-ui-tests-parallel [#[735]](https://paste.fedoraproject.org/paste/Dkxa~K438d5XuCOwce7SAg)
  * :question: run-python3-ui-tests [#[4641, 4642, 4643, 4644, 4645, 4646, 4647, 4648, 4649, 4650, 4651]](https://paste.fedoraproject.org/paste/-~V-dWtFudzxTzXYLO4tLw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#375](https://paste.fedoraproject.org/paste/UvC0GJY3lzFUFE3fJoYqFw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[175]](https://paste.fedoraproject.org/paste/LaEB57LRcNpdQDz0P0sD~w)
  * :heavy_check_mark: Istio-Upstream [#[2124]](https://paste.fedoraproject.org/paste/ZbGfmPcKM6ZYnh-b-LTdpQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7682]](https://paste.fedoraproject.org/paste/IXGEufjPU~7pEdZ2uCXUwA)
  * :red_circle: Kiali-on-Openshift [#[542]](https://paste.fedoraproject.org/paste/WjkD8NfiA7x0rg4HyeA3wQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#376](https://paste.fedoraproject.org/paste/qdiMQ9GdUWydQfmNPP31XQ)
  * :question: Istio-and-Kiali-on-Openshift [#[177]](https://paste.fedoraproject.org/paste/0n2xYLHnCMtIIaOAYcwfhQ)
  * :heavy_check_mark: Istio-Upstream [#[2126]](https://paste.fedoraproject.org/paste/RfCw3VbdcFwJhQSVZodjAA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7692, 7693]](https://paste.fedoraproject.org/paste/0Si6bgQBfk~vC79Cogz0Sw)
  * :heavy_check_mark: Kiali-on-Openshift [#[553, 554]](https://paste.fedoraproject.org/paste/6B5wLC32w3KaVlDTRIR9jQ)
  * :heavy_check_mark: old-bookinfo [#[3333]](https://paste.fedoraproject.org/paste/nwzwBczQp43igrhSTaVCcA)
  * :question: python-ui-tests-parallel [#[741]](https://paste.fedoraproject.org/paste/Wru1EvzpoNeuEjjOx9IV5Q)
  * :question: run-python3-ui-tests [#[4708, 4709, 4710, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718]](https://paste.fedoraproject.org/paste/~NHK2zFWoOjP4P8krVw2Aw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#377](https://paste.fedoraproject.org/paste/wjFYB8eAj~uQr~3aByw1yg)
  * :question: Istio-and-Kiali-on-Openshift [#[178]](https://paste.fedoraproject.org/paste/fd88OtBJ2YSxXYByyJqUNA)
  * :heavy_check_mark: Istio-Upstream [#[2127]](https://paste.fedoraproject.org/paste/wmApu67ZTb-i-Jxkyf-85A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7694, 7695]](https://paste.fedoraproject.org/paste/nemV1gJ55zIOx3GazWoJow)
  * :heavy_check_mark: Kiali-on-Openshift [#[555, 556]](https://paste.fedoraproject.org/paste/EWItkMEdsYX-8xWqC7-Idg)
  * :heavy_check_mark: old-bookinfo [#[3334]](https://paste.fedoraproject.org/paste/soaoFmg6pBwdVwSn0~Zl5w)
  * :question: python-ui-tests-parallel [#[742]](https://paste.fedoraproject.org/paste/MNBA2V7yKOX~tRcyv~ab6g)
  * :question: run-python3-ui-tests [#[4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729]](https://paste.fedoraproject.org/paste/OR2FGXx9sOt6bzEeuRa45Q)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#378](https://paste.fedoraproject.org/paste/kdCIlRkWduS~~MToiQXioQ)
  * :question: Istio-and-Kiali-on-Openshift [#[179]](https://paste.fedoraproject.org/paste/XblonkUKthdbwd4qwgIdvw)
  * :heavy_check_mark: Istio-Upstream [#[2128]](https://paste.fedoraproject.org/paste/2Z2dVdHtbKxRGDxi15JNNQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7696, 7697]](https://paste.fedoraproject.org/paste/1fwnswm5F7wdAYPRqEmYzQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[557, 558]](https://paste.fedoraproject.org/paste/drxu2Y7z-OvFDuTqEJd7RQ)
  * :heavy_check_mark: old-bookinfo [#[3335]](https://paste.fedoraproject.org/paste/-nbJh5ALJewvRNmC~FatuA)
  * :question: python-ui-tests-parallel [#[743]](https://paste.fedoraproject.org/paste/ORXIWwZIrkBeH~rwDssfUA)
  * :question: run-python3-ui-tests [#[4736, 4737, 4738, 4739, 4740, 4730, 4731, 4732, 4733, 4734, 4735]](https://paste.fedoraproject.org/paste/GeGBWTO1VkRi4YiScvmYrA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#379](https://paste.fedoraproject.org/paste/-LD2YXNO40ncAPPxc1eC-A)
  * :question: Istio-and-Kiali-on-Openshift [#[181]](https://paste.fedoraproject.org/paste/jz4xlTcNaQNuz~slWjKf5w)
  * :heavy_check_mark: Istio-Upstream [#[2130]](https://paste.fedoraproject.org/paste/dYLP6KTSjt-C1IZBxE30KQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7701, 7702]](https://paste.fedoraproject.org/paste/8IeUwf9pblmxs-zw981HHQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[562, 563]](https://paste.fedoraproject.org/paste/ZJO0n6wGVv67xmeRwHRQog)
  * :heavy_check_mark: old-bookinfo [#[3337]](https://paste.fedoraproject.org/paste/cFEHkTFCjokjnRbf4gltTw)
  * :question: python-ui-tests-parallel [#[745]](https://paste.fedoraproject.org/paste/fzDl-Xoqd6EekQ7wABt~0w)
  * :question: run-python3-ui-tests [#[4752, 4753, 4754, 4755, 4756, 4757, 4758, 4759, 4760, 4761, 4762]](https://paste.fedoraproject.org/paste/OU~K5RCJGpZFAIvkiB8Kkw)

**Comment by hhovsepy** [comment]
newly added tests are passing, the failures are random

**Pull request merged**
