### PR TITLE
Fixed failing tests after latest UI changes.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#593](https://paste.centos.org/view/54d71806 )
  * :question: upstream-istio-pipeline [#[554]](https://paste.centos.org/view/48b3af3b )
  * :heavy_check_mark: build-kiali [#[2571]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[459]](Log omitted)
  * :heavy_check_mark: install-istio [#[1147]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9384, 9385, 9386]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6485, 6486, 6487]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4630, 4631]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1397]](https://paste.centos.org/view/68612f70 )
  * :question: run-kiali-ui-tests [#[23616, 23617, 23601, 23602, 23603, 23604, 23605, 23606, 23607, 23608, 23609, 23610, 23611, 23612, 23613, 23614, 23615]](https://paste.centos.org/view/af7d04bf https://paste.centos.org/view/ea4ab2d6 https://paste.centos.org/view/93f3ab22 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#594](https://paste.centos.org/view/8e742baa )
  * :question: upstream-istio-pipeline [#[563]](https://paste.centos.org/view/03614dce )
  * :heavy_check_mark: build-kiali [#[2586]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[471]](Log omitted)
  * :heavy_check_mark: install-istio [#[1158]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9441, 9442, 9444]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6523, 6524, 6526]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4656, 4654]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1408]](https://paste.centos.org/view/3b5c1e13 )
  * :question: run-kiali-ui-tests [#[23788, 23789, 23790, 23791, 23792, 23793, 23794, 23795, 23796, 23797, 23798, 23799, 23800, 23801, 23802, 23803, 23804]](https://paste.centos.org/view/b2937a96 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#595](https://paste.centos.org/view/08968512 )
  * :red_circle: upstream-istio-pipeline [#[564]](https://paste.centos.org/view/0fd464c9 )
  * :heavy_check_mark: build-kiali [#[2587]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[472]](Log omitted)
  * :red_circle: install-istio [#[1159]](https://paste.centos.org/view/c6a41134 )
  * :heavy_check_mark: clean-environment [#[9454]](Log omitted)
  * :red_circle: istio-kiali-mesh-checker [#[6534]](https://paste.centos.org/view/4b57440d )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#596](https://paste.centos.org/view/2d9649b1 )
  * :red_circle: upstream-istio-pipeline [#[567]](https://paste.centos.org/view/f4c7f82e )
  * :heavy_check_mark: build-kiali [#[2592]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[476]](Log omitted)
  * :red_circle: install-istio [#[1162]](https://paste.centos.org/view/485a6e10 )
  * :heavy_check_mark: clean-environment [#[9471]](Log omitted)
  * :red_circle: istio-kiali-mesh-checker [#[6548]](https://paste.centos.org/view/a43711d8 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#597](https://paste.centos.org/view/b8abf900 )
  * :question: upstream-istio-pipeline [#[568]](https://paste.centos.org/view/06f4950f )
  * :heavy_check_mark: build-kiali [#[2594]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[477]](Log omitted)
  * :heavy_check_mark: install-istio [#[1163]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9481, 9478, 9479]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6553, 6554, 6555]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4675, 4676]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1413]](https://paste.centos.org/view/ff8b9bf5 )
  * :question: run-kiali-ui-tests [#[23874, 23875, 23876, 23877, 23878, 23879, 23880, 23881, 23882, 23883, 23884, 23885, 23886, 23887, 23888, 23889, 23890]](https://paste.centos.org/view/cb2c6894 https://paste.centos.org/view/06bf0f66 )

**Comment by hhovsepy** [comment]
failures are random

**Pull request merged**
