### PR TITLE
Overview page tests adjusted to latest UI changes

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#575](https://paste.centos.org/view/d43e28ed )
  * :red_circle: upstream-istio-pipeline [#[481]](https://paste.centos.org/view/8f640a6a )
  * :heavy_check_mark: build-kiali [#[2420]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[356]](Log omitted)
  * :red_circle: install-istio [#[1025]](https://paste.centos.org/view/1a0d4890 )
  * :heavy_check_mark: clean-environment [#[8806]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#576](https://paste.centos.org/view/a091c5d7 )
  * :question: upstream-istio-pipeline [#[482]](https://paste.centos.org/view/64a115c0 )
  * :heavy_check_mark: build-kiali [#[2421]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[357]](Log omitted)
  * :heavy_check_mark: install-istio [#[1026]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8808, 8809, 8807]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6104, 6105, 6106]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4384, 4383]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1318]](https://paste.centos.org/view/69c58fe4 )
  * :question: run-kiali-ui-tests [#[22273, 22274, 22275, 22276, 22277, 22278, 22279, 22280, 22281, 22282, 22283, 22284, 22285, 22286, 22287, 22288, 22289]](https://paste.centos.org/view/45999ff1 https://paste.centos.org/view/fffc7ade https://paste.centos.org/view/d58181d5 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#578](https://paste.centos.org/view/5f81bd6e )
  * :question: upstream-istio-pipeline [#[486]](https://paste.centos.org/view/35d9d0b1 )
  * :heavy_check_mark: build-kiali [#[2431]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[364]](Log omitted)
  * :heavy_check_mark: install-istio [#[1032]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8836, 8837, 8838]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6128, 6129, 6130]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4393, 4394]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1325]](https://paste.centos.org/view/d6deed95 )
  * :question: run-kiali-ui-tests [#[22400, 22401, 22402, 22403, 22404, 22405, 22406, 22407, 22408, 22392, 22393, 22394, 22395, 22396, 22397, 22398, 22399]](https://paste.centos.org/view/2c8f0dc6 https://paste.centos.org/view/65f8d40e https://paste.centos.org/view/7ee5a59f )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#579](https://paste.centos.org/view/080b92ad )
  * :red_circle: upstream-istio-pipeline [#[493]](https://paste.centos.org/view/87833c89 )
  * :red_circle: build-kiali [#[2448]](https://paste.centos.org/view/2b12f1c4 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
