### PR TITLE
Removed envoy health.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#246](https://paste.fedoraproject.org/paste/Nhrn0~9l0A2CzjJhLXmDQw)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#247](https://paste.fedoraproject.org/paste/AyQjDPF6AsLohrFtim0wWA)
  * :question: Istio-and-Kiali-on-Openshift [#[2337]](https://paste.fedoraproject.org/paste/~EyZMy2Y39IKOe3Qu-oV7A)
  * :heavy_check_mark: Istio-Upstream [#[1013]](https://paste.fedoraproject.org/paste/kLlJZMmPSC43KpOAAnimZg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3488, 3489, 3490, 3491]](https://paste.fedoraproject.org/paste/zcKQqNnrN2LfpDn~NXpi~w)
  * :heavy_check_mark: Kiali-on-Openshift [#[1988, 1989]](https://paste.fedoraproject.org/paste/tufAVyuI18R1h74EBq6uBw)
  * :heavy_check_mark: install-bookinfo [#[1910, 1911]](https://paste.fedoraproject.org/paste/1RXbaK~vUQwFDOQqo7kk2Q)
  * :question: python-ui-tests-parallel [#[380]](https://paste.fedoraproject.org/paste/KZT2f7qtBMJkPkzVOhmDBg)
  * :question: run-python3-ui-tests [#[736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746]](https://paste.fedoraproject.org/paste/BUESo0M8MafhN4n-SUx1IA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#248](https://paste.fedoraproject.org/paste/3w7yZ87WVVy6h58thJgRLA)
  * :question: Istio-and-Kiali-on-Openshift [#[2338]](https://paste.fedoraproject.org/paste/~A~dA5ZASn34OBjYBBjWRQ)
  * :heavy_check_mark: Istio-Upstream [#[1014]](https://paste.fedoraproject.org/paste/RgcIjDxJDL5SHUJd0oI8nA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3496, 3497, 3499, 3495]](https://paste.fedoraproject.org/paste/zL-9iSk4X3uNsY1Mpo21CQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1992, 1994]](https://paste.fedoraproject.org/paste/hF9liw2VEwsv1IZivu0JKw)
  * :heavy_check_mark: install-bookinfo [#[1912, 1913]](https://paste.fedoraproject.org/paste/fYnT3xeGP7dImBOQm1rrVA)
  * :question: python-ui-tests-parallel [#[381]](https://paste.fedoraproject.org/paste/V4eTJ1UClGgaeUy1Xri2ag)
  * :question: run-python3-ui-tests [#[747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757]](https://paste.fedoraproject.org/paste/KpObR5D4mh~cMduwrnHrpw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#249](https://paste.fedoraproject.org/paste/0xJSwn0l-eU5wAqTu-1pZg)
  * :question: Istio-and-Kiali-on-Openshift [#[2347]](https://paste.fedoraproject.org/paste/NI6oi~OfSr0xJ1YHT74fCg)
  * :heavy_check_mark: Istio-Upstream [#[1022]](https://paste.fedoraproject.org/paste/eaU90bMQUr4SPvsAvbUzgA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3523, 3525, 3526, 3527]](https://paste.fedoraproject.org/paste/BVdX9YA-aid-yAohNFuMCg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2010, 2011]](https://paste.fedoraproject.org/paste/BjGQ8lg7T8XQXFLElkuuOw)
  * :heavy_check_mark: install-bookinfo [#[1922, 1923]](https://paste.fedoraproject.org/paste/Hx1AbYOR4Uc6HOwCHDVxVQ)
  * :question: python-ui-tests-parallel [#[384]](https://paste.fedoraproject.org/paste/Fg8dcN02qYXVsGX3cyC78w)
  * :question: run-python3-ui-tests [#[780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790]](https://paste.fedoraproject.org/paste/NXw-W1zSnzipPaaxiIefRQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#250](https://paste.fedoraproject.org/paste/3vSGV4yuJyNmm6HIYigrww)
  * :question: Istio-and-Kiali-on-Openshift [#[2349]](https://paste.fedoraproject.org/paste/eZQYLOuPlCAr2i11AuXOrA)
  * :heavy_check_mark: Istio-Upstream [#[1024]](https://paste.fedoraproject.org/paste/qGYF-Xa-vZVi-Vk7fCCTRA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3531, 3532, 3533, 3534]](https://paste.fedoraproject.org/paste/W5tok8JdRU5KGbjk0mwa7w)
  * :heavy_check_mark: Kiali-on-Openshift [#[2014, 2015]](https://paste.fedoraproject.org/paste/2g1RtnXJz8PatxkbRNodRA)
  * :heavy_check_mark: install-bookinfo [#[1925, 1926]](https://paste.fedoraproject.org/paste/uTFeEJXWWc0msyA8rl5JeA)
  * :question: python-ui-tests-parallel [#[385]](https://paste.fedoraproject.org/paste/mwySZIgD1nFIsMtgQJFWuQ)
  * :question: run-python3-ui-tests [#[800, 801, 791, 792, 793, 794, 795, 796, 797, 798, 799]](https://paste.fedoraproject.org/paste/c5ZjPES4th6KyJstDkgEmg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#251](https://paste.fedoraproject.org/paste/h~yDAOTLX~zZNi9mhYgwRA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2355]](https://paste.fedoraproject.org/paste/PfIQtlZvlYyDq-IrSrV18g)
  * :heavy_check_mark: Istio-Upstream [#[1029]](https://paste.fedoraproject.org/paste/b7gkakzxin5ihoWpFyV43g)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3552, 3553, 3554, 3555]](https://paste.fedoraproject.org/paste/Vel8euSgVWHeQ3W3XHwDcw)
  * :heavy_check_mark: Kiali-on-Openshift [#[2026, 2027]](https://paste.fedoraproject.org/paste/ETtEXL-k8beakKSwVzZKZg)
  * :heavy_check_mark: install-bookinfo [#[1933, 1934]](https://paste.fedoraproject.org/paste/bA35RPzYnehwxJlwOkir4Q)
  * :heavy_check_mark: python-ui-tests-parallel [#[387]](https://paste.fedoraproject.org/paste/vm0Cc0M~UD1g2rrHo1ighQ)
  * :heavy_check_mark: run-python3-ui-tests [#[813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823]](https://paste.fedoraproject.org/paste/m0eq6WDejRaO6Bf1MD6F2g)

**Pull request merged**
