### PR TITLE
Added test for Overview Action Enable/Disable/Remove Auto Injection

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#608](https://paste.centos.org/view/6d507dea )
  * :red_circle: upstream-istio-pipeline [#[629]](https://paste.centos.org/view/d0f6c189 )
  * :heavy_check_mark: build-kiali [#[2768]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[563]](Log omitted)
  * :red_circle: install-istio [#[1328]](https://paste.centos.org/view/951d4db4 )
  * :heavy_check_mark: clean-environment [#[10224]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#609](https://paste.centos.org/view/0d8280a1 )
  * :question: upstream-istio-pipeline [#[630]](https://paste.centos.org/view/c693766e )
  * :heavy_check_mark: build-kiali [#[2769]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[564]](Log omitted)
  * :heavy_check_mark: install-istio [#[1330]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10232, 10230, 10231]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6957, 6958, 6959]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4930, 4931]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1503]](https://paste.centos.org/view/ca93cfa6 )
  * :question: run-kiali-ui-tests [#[25440, 25441, 25442, 25443, 25444, 25445, 25429, 25430, 25431, 25432, 25433, 25434, 25435, 25436, 25437, 25438, 25439]](https://paste.centos.org/view/216b5a38 https://paste.centos.org/view/ca4821c3 https://paste.centos.org/view/594e3372 https://paste.centos.org/view/f1dd1bb2 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#613](https://paste.centos.org/view/a4967f7c )
  * :question: upstream-istio-pipeline [#[640]](https://paste.centos.org/view/a084e729 )
  * :heavy_check_mark: build-kiali [#[2786]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[577]](Log omitted)
  * :heavy_check_mark: install-istio [#[1343]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10298, 10299, 10300]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7008, 7006, 7007]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4958, 4959]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1517]](https://paste.centos.org/view/b3a28a21 )
  * :question: run-kiali-ui-tests [#[25674, 25675, 25676, 25677, 25678, 25679, 25680, 25681, 25682, 25683, 25684, 25685, 25686, 25687, 25688, 25689, 25690]](https://paste.centos.org/view/d604f99f https://paste.centos.org/view/157b7b01 https://paste.centos.org/view/2731f337 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#614](https://paste.centos.org/view/17137c02 )
  * :question: upstream-istio-pipeline [#[641]](https://paste.centos.org/view/4b622814 )
  * :heavy_check_mark: build-kiali [#[2788]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[578]](Log omitted)
  * :heavy_check_mark: install-istio [#[1347]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10306, 10307, 10308]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7016, 7017, 7015]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4963, 4964]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1520]](https://paste.centos.org/view/a00e5f1d )
  * :question: run-kiali-ui-tests [#[25728, 25729, 25730, 25731, 25732, 25733, 25734, 25735, 25736, 25737, 25738, 25739, 25740, 25741, 25725, 25726, 25727]](https://paste.centos.org/view/a727a7b6 https://paste.centos.org/view/b626150e https://paste.centos.org/view/1e1478f3 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#615](https://paste.centos.org/view/55f7d91d )
  * :question: upstream-istio-pipeline [#[643]](https://paste.centos.org/view/ae55cd00 )
  * :heavy_check_mark: build-kiali [#[2791]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[581]](Log omitted)
  * :heavy_check_mark: install-istio [#[1351]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10320, 10318, 10319]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7025, 7026, 7027]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4969, 4970]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1523]](https://paste.centos.org/view/e8740f62 )
  * :question: run-kiali-ui-tests [#[25792, 25776, 25777, 25778, 25779, 25780, 25781, 25782, 25783, 25784, 25785, 25786, 25787, 25788, 25789, 25790, 25791]](https://paste.centos.org/view/69205d5d https://paste.centos.org/view/33f7e2e3 https://paste.centos.org/view/ae2bdc60 https://paste.centos.org/view/66b649fa https://paste.centos.org/view/3d17dc86 )

**Pull request merged**
