### PR TITLE
Kiali 1.1

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#514](https://paste.centos.org/view/a98e893a )
  * :question: upstream-pipeline [#[866]](https://paste.centos.org/view/ed862614 )
  * :heavy_check_mark: build-kiali [#[1551]](Log omitted)
  * :heavy_check_mark: install-maistra [#[1813]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5824, 5825, 5822, 5823]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3752, 3753, 3754]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2833, 2834]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1604]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[799]](https://paste.centos.org/view/7ba786fe )
  * :question: run-kiali-ui-tests [#[13481, 13482, 13483, 13484, 13485, 13486, 13487, 13488, 13489, 13490, 13491, 13492, 13493, 13494, 13495, 13496, 13497]](https://paste.centos.org/view/1313cd36 )

**Pull request merged**
