### PR TITLE
Temporary solution for OC Client switching all calls to Kiali Rest API.

### PR DESCRIPTION
**Pull request by hhovsepy**
Added new config to activate that.

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#283](https://paste.fedoraproject.org/paste/mHc1TUTFoX4YMmpMCnwc2A)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[2772]](https://paste.fedoraproject.org/paste/yNrGODK4Mj4uWbWSchDd-w)
  * :heavy_check_mark: Istio-Upstream [#[1444]](https://paste.fedoraproject.org/paste/jXnXEtgJlxp4BChtbBFscA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5189]](https://paste.fedoraproject.org/paste/ZDH5Jz3VDCT9gPFXl5zMAA)
  * :red_circle: Kiali-on-Openshift [#[3058]](https://paste.fedoraproject.org/paste/Rmq-U3QuW2aZjsOkvea3Lg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#284](https://paste.fedoraproject.org/paste/Gx3vHX-MaT4s1M6kB7l6vw)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[2773]](https://paste.fedoraproject.org/paste/FkYcQxE-d~tqTOSJDjDHOw)
  * :heavy_check_mark: Istio-Upstream [#[1445]](https://paste.fedoraproject.org/paste/VKmKcF19q25KaWNoxR1Iuw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5191]](https://paste.fedoraproject.org/paste/qYI7pRCHnlVfLxShB80EFA)
  * :red_circle: Kiali-on-Openshift [#[3060]](https://paste.fedoraproject.org/paste/zKdSxxPkGJteqsWN02hIkg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#285](https://paste.fedoraproject.org/paste/ZSUHxdauZ5yzlgshP2Zi3Q)
  * :question: Istio-and-Kiali-on-Openshift [#[2782]](https://paste.fedoraproject.org/paste/ovXWHiYXjnrw903cWneiRg)
  * :heavy_check_mark: Kiali-on-Openshift [#[3082, 3083]](https://paste.fedoraproject.org/paste/ELBnb1bMi4pk2uuWtoFy4g)
  * :heavy_check_mark: Istio-Upstream [#[1454]](https://paste.fedoraproject.org/paste/por6k-rbe-S2wMQT~DC19w)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5224, 5221, 5222, 5223]](https://paste.fedoraproject.org/paste/FTfruMaREU-I70WXbSXwPw)
  * :heavy_check_mark: install-bookinfo [#[2568, 2569]](https://paste.fedoraproject.org/paste/Ze-Dg89DCQBWq03HiLuWsA)
  * :question: python-ui-tests-parallel [#[514]](https://paste.fedoraproject.org/paste/teY-Avn4TnEpQhEFmfjjdw)
  * :question: run-python3-ui-tests [#[2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192]](https://paste.fedoraproject.org/paste/b8cRUBrt~AnUEDrx6mEdYQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#286](https://paste.fedoraproject.org/paste/uyYA2F~oElNPfOaBuNFXvg)
  * :question: Istio-and-Kiali-on-Openshift [#[2783]](https://paste.fedoraproject.org/paste/RstS~TaOLDZTkzao6SVPBA)
  * :heavy_check_mark: Istio-Upstream [#[1455]](https://paste.fedoraproject.org/paste/by6jN3xw1HEpD0251tzJsA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5234, 5235, 5236, 5237]](https://paste.fedoraproject.org/paste/~c6PqeYh8a1kg~pNHbjwxQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3089, 3090]](https://paste.fedoraproject.org/paste/BNUoXEA9N6ZTiFHLSxuY6g)
  * :heavy_check_mark: install-bookinfo [#[2572, 2573]](https://paste.fedoraproject.org/paste/i-dD8lf3MlP4VHsvVxPDDw)
  * :question: python-ui-tests-parallel [#[515]](https://paste.fedoraproject.org/paste/5dlaaiSnnLojCnzuw~k3pA)
  * :question: run-python3-ui-tests [#[2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203]](https://paste.fedoraproject.org/paste/Nz7cHRjAidH9Nclx0FUjJw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#287](https://paste.fedoraproject.org/paste/k-SJhQ1nNHsv~3v8m9W4GA)
  * :question: Istio-and-Kiali-on-Openshift [#[2791]](https://paste.fedoraproject.org/paste/~JbUlThrqx6WP6q7CK1kSA)
  * :heavy_check_mark: Istio-Upstream [#[1463]](https://paste.fedoraproject.org/paste/HWUbf3~-BhHHjD5-GtDnOA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5273, 5274, 5275, 5276]](https://paste.fedoraproject.org/paste/qIpLtNt-AojXGUKLp5NfCg)
  * :heavy_check_mark: Kiali-on-Openshift [#[3120, 3119]](https://paste.fedoraproject.org/paste/cwKiKOkRB9eD~v-4ZT5jCw)
  * :heavy_check_mark: install-bookinfo [#[2582, 2583]](https://paste.fedoraproject.org/paste/41TatbPGNd9TMJJYqZWBuA)
  * :question: python-ui-tests-parallel [#[517]](https://paste.fedoraproject.org/paste/Ae7cZDQ2~EMLkj416X8-Wg)
  * :question: run-python3-ui-tests [#[2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225]](https://paste.fedoraproject.org/paste/GcTs0GrG3b0uUD~IIXSkEQ)

**Comment by hhovsepy** [comment]
Merging, as the failures are in Enums,

**Pull request merged**
