### PR TITLE
workload-filters - Added workload filter tests with sidecar, label and version label

### PR DESCRIPTION
**Pull request by skondkar**

### CODE REVIEW

**Comment by skondkar** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#688](https://paste.centos.org/view/9cbbd6c5 )
  * :question: upstream-istio-pipeline [#[923]](https://paste.centos.org/view/ac936381 )
  * :heavy_check_mark: build-kiali [#[3738]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1167]](Log omitted)
  * :heavy_check_mark: install-istio [#[1963]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14946, 14947, 14948, 14949]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10770, 10772, 10773, 10774]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8049, 8050, 8051]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2105]](https://paste.centos.org/view/1f041db8 )
  * :question: run-kiali-ui-tests [#[36009, 36010, 36011, 36012, 36013, 36014, 36015, 36016, 36017, 36018, 36019, 36020, 36021, 36022, 36023, 36024, 36025]](https://paste.centos.org/view/0832fa63 https://paste.centos.org/view/8fdc6299 https://paste.centos.org/view/cd2098b9 https://paste.centos.org/view/e0d7d7af https://paste.centos.org/view/e0b8379e )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#689](https://paste.centos.org/view/f828757f )
  * :question: upstream-istio-pipeline [#[930]](https://paste.centos.org/view/898fb499 )
  * :heavy_check_mark: build-kiali [#[3748]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1174]](Log omitted)
  * :heavy_check_mark: install-istio [#[1970]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14992, 14993, 14994, 14991]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10810, 10811, 10812, 10813]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[8082, 8083, 8085]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2114]](https://paste.centos.org/view/55980537 )
  * :question: run-kiali-ui-tests [#[36163, 36164, 36165, 36166, 36167, 36168, 36169, 36170, 36171, 36172, 36173, 36174, 36175, 36176, 36177, 36178, 36179]](https://paste.centos.org/view/3453571f https://paste.centos.org/view/11109d82 )

**Pull request merged**
