### PR TITLE
Added Metrics tabs checks

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#195](https://paste.fedoraproject.org/paste/k86vPCBkNKbHiXXUQVi7tQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[2144]](https://paste.fedoraproject.org/paste/glcsILvCWqeYZPnZAIW7Aw)
  * :heavy_check_mark: Istio-Upstream [#[888]](https://paste.fedoraproject.org/paste/4inu7K8tqTBCdhf15tbQrw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2814]](https://paste.fedoraproject.org/paste/~rH8zDR4qNrfIxhQFc-q2A)
  * :heavy_check_mark: install-bookinfo [#[1573, 1574]](https://paste.fedoraproject.org/paste/-ywY5~IqEUUBynApbe5epQ)
  * :red_circle: Kiali-on-Openshift [#[1493]](https://paste.fedoraproject.org/paste/-xQLc1lRwttR50f4xctJNQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#198](https://paste.fedoraproject.org/paste/BCQ4HiEP5KxOn7xGvUK4rQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2147]](https://paste.fedoraproject.org/paste/SGrVKCOL5-mIKFRyq9K5Xg)
  * :heavy_check_mark: Istio-Upstream [#[891]](https://paste.fedoraproject.org/paste/KOmp6dxpmF8-ptk45Ifnzw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2821, 2822]](https://paste.fedoraproject.org/paste/Keok~XqKj5GIA-jAnvG~hg)
  * :heavy_check_mark: install-bookinfo [#[1580, 1581]](https://paste.fedoraproject.org/paste/cyJ0S~7MtFsA-KTerO-10g)
  * :heavy_check_mark: Kiali-on-Openshift [#[1497]](https://paste.fedoraproject.org/paste/LS1Mgct3zKJ4RFDtKCfB7w)
  * :question: python-ui-tests-parallel [#[260]](https://paste.fedoraproject.org/paste/Q41nC0nI7WagqVv78wiCcg)
  * :question: run-python-ui-tests [#[3508, 3509, 3510, 3511, 3512, 3513, 3514, 3515, 3516, 3517, 3518]](https://paste.fedoraproject.org/paste/3m8mfk6sZgn9TRn9YZwG6g)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#199](https://paste.fedoraproject.org/paste/xaYl2h2VR8LxYHrKZkxYKw)
  * :question: Istio-and-Kiali-on-Openshift [#[2155]](https://paste.fedoraproject.org/paste/3jMp9IOvjSaBM-CZ-Gc~5Q)
  * :heavy_check_mark: Istio-Upstream [#[895]](https://paste.fedoraproject.org/paste/pfeyf3JEm3NZmi-Q783skA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2833, 2834]](https://paste.fedoraproject.org/paste/pYFj-3TTcmdMlXP-gr2jfQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1509, 1510]](https://paste.fedoraproject.org/paste/cS8YdOMYPPcsd1vftQLLHQ)
  * :heavy_check_mark: install-bookinfo [#[1590, 1591]](https://paste.fedoraproject.org/paste/i5PvZX4-K~qUxUUxROYQeQ)
  * :question: python-ui-tests-parallel [#[262]](https://paste.fedoraproject.org/paste/2~T41qviFaDlGuPlJFJsag)
  * :question: run-python-ui-tests [#[3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3550]](https://paste.fedoraproject.org/paste/crpqMioXeUZ2UL~0VLd-Yg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#200](https://paste.fedoraproject.org/paste/3407oRgiNdHca~9~YWdjBg)
  * :question: Istio-and-Kiali-on-Openshift [#[2160]](https://paste.fedoraproject.org/paste/nXqU2DIWCBPc8Sx6CzaV6A)
  * :heavy_check_mark: Istio-Upstream [#[898]](https://paste.fedoraproject.org/paste/a01QFavbQD9wJyzHYG1AJQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2849, 2850]](https://paste.fedoraproject.org/paste/MiV-bZvaLYlcvyHrV7iKDg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1523, 1524]](https://paste.fedoraproject.org/paste/of0uBTZvPO~1hdL3b4udxw)
  * :heavy_check_mark: install-bookinfo [#[1600, 1601]](https://paste.fedoraproject.org/paste/Qju1Aq5gRpcttu9HcDJBog)
  * :question: python-ui-tests-parallel [#[267]](https://paste.fedoraproject.org/paste/mxvlropCkijsUKAIVdfc2w)
  * :question: run-python-ui-tests [#[3585, 3586, 3587, 3588, 3589, 3590, 3591, 3592, 3593, 3594, 3595]](https://paste.fedoraproject.org/paste/qjoydTPjUMlI0YZafi7P1A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#201](https://paste.fedoraproject.org/paste/fQGAhypnaDMUwivUVn1nLA)
  * :question: Istio-and-Kiali-on-Openshift [#[2161]](https://paste.fedoraproject.org/paste/RTCoq7ZsL0ysTkTERvjRsA)
  * :heavy_check_mark: Istio-Upstream [#[899]](https://paste.fedoraproject.org/paste/GmGpCSSnMf5MFutlXJyukA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2853, 2854]](https://paste.fedoraproject.org/paste/7ak5k92qQKoirQq3NnBzZg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1526, 1527]](https://paste.fedoraproject.org/paste/srfaJy7J9uEs9UkyQsxo7g)
  * :heavy_check_mark: install-bookinfo [#[1603, 1604]](https://paste.fedoraproject.org/paste/rYO1tfqqf-DrtOcL~jytig)
  * :question: python-ui-tests-parallel [#[268]](https://paste.fedoraproject.org/paste/73BuatKlMXdVVguznStG3g)
  * :question: run-python-ui-tests [#[3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606]](https://paste.fedoraproject.org/paste/NjNYsqj2d0J863mpOt3~xA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#202](https://paste.fedoraproject.org/paste/q~lwvVUVXCk4jKdFZ5Dg3g)
  * :question: Istio-and-Kiali-on-Openshift [#[2162]](https://paste.fedoraproject.org/paste/Aq9Rsz9HUo9uYRST~STH9w)
  * :heavy_check_mark: Istio-Upstream [#[900]](https://paste.fedoraproject.org/paste/HZjQBXFeOrFsThQtUFW3RQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2856, 2855]](https://paste.fedoraproject.org/paste/3bsMpmESmC0MQ4hGsk0yjQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1528, 1529]](https://paste.fedoraproject.org/paste/3Sr3kq1JB1FaFtiwbABiwQ)
  * :heavy_check_mark: install-bookinfo [#[1605, 1606]](https://paste.fedoraproject.org/paste/9z9DX4yXRUglV9yjVAfIbw)
  * :question: python-ui-tests-parallel [#[270]](https://paste.fedoraproject.org/paste/Sxl6Iy3fkNyPafVxC11fzw)
  * :question: run-python-ui-tests [#[3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628]](https://paste.fedoraproject.org/paste/UGaJvDjujRrcx0u0f7vTiQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#203](https://paste.fedoraproject.org/paste/J1qSq8jSsCbIwtKK5PI2Fw)
  * :question: Istio-and-Kiali-on-Openshift [#[2164]](https://paste.fedoraproject.org/paste/vV2n7lS4kQwBwhDzV8sQlg)
  * :heavy_check_mark: Istio-Upstream [#[901]](https://paste.fedoraproject.org/paste/4OkvYxJzGrYdEaD759EP5Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2859, 2860]](https://paste.fedoraproject.org/paste/MDVnw3fT4w5bkq9DbRInrg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1532, 1533]](https://paste.fedoraproject.org/paste/5R2DDEYTHXGKnm5jieJg3A)
  * :heavy_check_mark: install-bookinfo [#[1609, 1610]](https://paste.fedoraproject.org/paste/Hoe94r6Tp3knCW6h7J6fzg)
  * :question: python-ui-tests-parallel [#[272]](https://paste.fedoraproject.org/paste/XqtrydGGpA81QELtb7EgLw)
  * :question: run-python-ui-tests [#[3648, 3649, 3650, 3640, 3641, 3642, 3643, 3644, 3645, 3646, 3647]](https://paste.fedoraproject.org/paste/y788snmNVHT6t82scy1PPA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#205](https://paste.fedoraproject.org/paste/V5zA2Uelq-eHXsdaakcqAQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2167]](https://paste.fedoraproject.org/paste/MW8OVKg~6zRUUR491jICXw)
  * :heavy_check_mark: Istio-Upstream [#[903]](https://paste.fedoraproject.org/paste/KO22PuMHjurHY8Y5MYcCuQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2867, 2868]](https://paste.fedoraproject.org/paste/IxKECroIV0EqxvNYMP-u~A)
  * :heavy_check_mark: Kiali-on-Openshift [#[1544, 1543]](https://paste.fedoraproject.org/paste/V~5HOZg8S0eNi9m2Yn31TQ)
  * :heavy_check_mark: install-bookinfo [#[1616, 1615]](https://paste.fedoraproject.org/paste/psJFuePShH5W-wusoXHiaA)
  * :question: python-ui-tests-parallel [#[276]](https://paste.fedoraproject.org/paste/J9yRO9yUkGH75Xr3idVqaA)
  * :question: run-python-ui-tests [#[3684, 3685, 3686, 3687, 3688, 3689, 3690, 3691, 3692, 3693, 3694]](https://paste.fedoraproject.org/paste/myEsaq9HdBEHsFAFw0vH8A)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#206](https://paste.fedoraproject.org/paste/fQezMHksXa-puaqsHJswwQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2168]](https://paste.fedoraproject.org/paste/BxmzmwzPh1BvdmWcGfC58Q)
  * :heavy_check_mark: Istio-Upstream [#[904]](https://paste.fedoraproject.org/paste/rUdN4UN4GoAuAxPRFWG~dA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2869, 2870]](https://paste.fedoraproject.org/paste/pRF7Hhb3z-RuITiu4LYiSQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[1545, 1546]](https://paste.fedoraproject.org/paste/0zZ35mgIiI6AqrcgQpmiuA)
  * :heavy_check_mark: install-bookinfo [#[1617, 1618]](https://paste.fedoraproject.org/paste/hI4849veharlTiGO85~msA)
  * :question: python-ui-tests-parallel [#[277]](https://paste.fedoraproject.org/paste/lQYrBMdoaXlS1Jirf3WYRg)
  * :question: run-python-ui-tests [#[3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705]](https://paste.fedoraproject.org/paste/32neOr9zLXnwzb-0Rv7kkg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#207](https://paste.fedoraproject.org/paste/dSpfJqzogMYuwntThUw0wA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2169]](https://paste.fedoraproject.org/paste/Dplp-S2k5ppZD3wajvwkkA)
  * :heavy_check_mark: Istio-Upstream [#[905]](https://paste.fedoraproject.org/paste/8eoFaJ69-XZ~wyKVLhEKOA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[2872, 2874]](https://paste.fedoraproject.org/paste/Qzceg4KuS~I-FpabVD4cqg)
  * :heavy_check_mark: Kiali-on-Openshift [#[1549, 1550]](https://paste.fedoraproject.org/paste/wUlfnBCTfDRZ9aTVNLZWlw)
  * :heavy_check_mark: install-bookinfo [#[1619, 1620]](https://paste.fedoraproject.org/paste/pHBIavc2xXy2RWUPK6PkBQ)
  * :heavy_check_mark: python-ui-tests-parallel [#[279]](https://paste.fedoraproject.org/paste/TivDmJz7WWA-Q1J4yUW~7Q)
  * :heavy_check_mark: run-python-ui-tests [#[3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727]](https://paste.fedoraproject.org/paste/m6Fi0uNaqtS6cVOIRegE8w)

**Pull request merged**
