### PR TITLE
Fixing failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#667](https://paste.centos.org/view/d4e649f6 )
  * :question: upstream-istio-pipeline [#[838]](https://paste.centos.org/view/dcad8cd2 )
  * :heavy_check_mark: build-kiali [#[3573]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1047]](Log omitted)
  * :heavy_check_mark: install-istio [#[1831]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14048, 14049, 14050, 14045]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[9995, 9996, 9997, 9998]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7376, 7374, 7375]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1974]](https://paste.centos.org/view/efe5cbc1 )
  * :question: run-kiali-ui-tests [#[33664, 33665, 33666, 33667, 33668, 33669, 33670, 33671, 33672, 33673, 33674, 33675, 33676, 33677, 33678, 33679, 33680]](https://paste.centos.org/view/8a0c4f7c https://paste.centos.org/view/06f112e0 https://paste.centos.org/view/3f032d0a )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#668](https://paste.centos.org/view/368e403c )
  * :question: upstream-istio-pipeline [#[841]](https://paste.centos.org/view/c57a1cf3 )
  * :heavy_check_mark: build-kiali [#[3579]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1052]](Log omitted)
  * :heavy_check_mark: install-istio [#[1837]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14088, 14089, 14090, 14087]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10032, 10033, 10030, 10031]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7402, 7403, 7404]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1982]](https://paste.centos.org/view/35ff8772 )
  * :question: run-kiali-ui-tests [#[33826, 33827, 33828, 33829, 33830, 33831, 33832, 33833, 33834, 33835, 33837, 33838, 33839, 33840, 33841, 33842, 33845]](https://paste.centos.org/view/4ae8cf67 )

**Pull request closed without merging**
