### PR TITLE
Fixed failing tests. Adjusted Service Graph filters according to latest changes.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#80](https://paste.fedoraproject.org/paste/571sngoCFFywn1ePxY5Wrg)
  * :red_circle: run-python-ui-tests [#474](https://paste.fedoraproject.org/paste/JWo~C5zioU0cfmrytAdS8Q)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#81](https://paste.fedoraproject.org/paste/y4MAftwg528D~TOShBy8yg)
  * :red_circle: run-python-ui-tests [#476](https://paste.fedoraproject.org/paste/~Co~VTpMdQBHWjAQIatomA)

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#82](https://paste.fedoraproject.org/paste/4mxuH~tC0MR4VwtFcgcyFA)
  * :heavy_check_mark: run-python-ui-tests [#477](https://paste.fedoraproject.org/paste/86jXrHYh-K7mcGBU9rEmVQ)

**Pull request merged**
