### PR TITLE
Refactoring base classes and common methods.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#495](https://paste.centos.org/view/90a1fb66 )
  * :question: upstream-istio-pipeline [#[79]](https://paste.centos.org/view/f4c4dfe8 )
  * :heavy_check_mark: build-kiali [#[1231]](Log omitted)
  * :heavy_check_mark: install-istio [#[118]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4483, 4484, 4485, 4486]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2787, 2788, 2789]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2211, 2212]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1235]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[634]](https://paste.centos.org/view/de00f237 )
  * :question: run-kiali-ui-tests [#[10688, 10689, 10690, 10691, 10675, 10676, 10677, 10678, 10679, 10680, 10681, 10682, 10683, 10684, 10685, 10686, 10687]](https://paste.centos.org/view/400c6e31 https://paste.centos.org/view/f186b1f1 https://paste.centos.org/view/55c22c12 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#496](https://paste.centos.org/view/b6aef216 )
  * :question: upstream-istio-pipeline [#[87]](https://paste.centos.org/view/d438e226 )
  * :heavy_check_mark: build-kiali [#[1265]](Log omitted)
  * :heavy_check_mark: install-istio [#[127]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4576, 4577, 4578, 4571]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2850, 2852, 2853]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2256, 2258]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1264]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[647]](https://paste.centos.org/view/46ed8861 )
  * :question: run-kiali-ui-tests [#[10928, 10916, 10917, 10918, 10919, 10920, 10921, 10896, 10897, 10898, 10899, 10900, 10901, 10902, 10903, 10904, 10905]](https://paste.centos.org/view/7f4834d2 https://paste.centos.org/view/981aefb7 https://paste.centos.org/view/cb0460ab )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#497](https://paste.centos.org/view/d5f3d47d )
  * :question: upstream-istio-pipeline [#[88]](https://paste.centos.org/view/664248a3 )
  * :heavy_check_mark: build-kiali [#[1272]](Log omitted)
  * :heavy_check_mark: install-istio [#[129]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4600, 4601, 4596, 4599]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2864, 2867, 2868]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2265, 2266]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1270]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[650]](https://paste.centos.org/view/e047fdf0 )
  * :question: run-kiali-ui-tests [#[10947, 10948, 10949, 10950, 10951, 10952, 10953, 10954, 10955, 10956, 10957, 10958, 10959, 10960, 10961, 10962, 10963]](https://paste.centos.org/view/e0541b98 https://paste.centos.org/view/21907eea https://paste.centos.org/view/56d32776 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
