### PR TITLE
Fixed failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#584](https://paste.centos.org/view/084b4bb4 )
  * :question: upstream-istio-pipeline [#[507]](https://paste.centos.org/view/28bb0428 )
  * :heavy_check_mark: build-kiali [#[2477]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[395]](Log omitted)
  * :heavy_check_mark: install-istio [#[1066]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8988, 8989, 8990]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6248, 6249, 6247]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4478, 4479]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1352]](https://paste.centos.org/view/a3430752 )
  * :question: run-kiali-ui-tests [#[22848, 22849, 22850, 22851, 22852, 22836, 22837, 22838, 22839, 22840, 22841, 22842, 22843, 22844, 22845, 22846, 22847]](https://paste.centos.org/view/af7dc197 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#585](https://paste.centos.org/view/7a169a05 )
  * :question: upstream-istio-pipeline [#[510]](https://paste.centos.org/view/f10fff19 )
  * :heavy_check_mark: build-kiali [#[2483]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[400]](Log omitted)
  * :heavy_check_mark: install-istio [#[1069]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9005, 9006, 9007]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6259, 6260, 6261]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4484, 4485]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1355]](https://paste.centos.org/view/13bae928 )
  * :question: run-kiali-ui-tests [#[22887, 22888, 22889, 22890, 22891, 22892, 22893, 22894, 22895, 22896, 22897, 22898, 22899, 22900, 22901, 22902, 22903]](https://paste.centos.org/view/fc1d07cc https://paste.centos.org/view/406e5b7e https://paste.centos.org/view/dce5c477 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#586](https://paste.centos.org/view/1015e857 )
  * :question: upstream-istio-pipeline [#[511]](https://paste.centos.org/view/7fa5273d )
  * :heavy_check_mark: build-kiali [#[2485]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[401]](Log omitted)
  * :heavy_check_mark: install-istio [#[1071]](Log omitted)
  * :heavy_check_mark: clean-environment [#[9016, 9017, 9018]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[6266, 6267, 6268]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4488, 4489]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1357]](https://paste.centos.org/view/74d9a7b7 )
  * :question: run-kiali-ui-tests [#[22921, 22922, 22923, 22924, 22925, 22926, 22927, 22928, 22929, 22930, 22931, 22932, 22933, 22934, 22935, 22936, 22937]](https://paste.centos.org/view/7a48aa3a )

**Pull request merged**
