### PR TITLE
Idle status support

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#562](https://paste.centos.org/view/64ba770e )
  * :question: upstream-istio-pipeline [#[436]](https://paste.centos.org/view/cc4ef690 )
  * :heavy_check_mark: build-kiali [#[2306]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[277]](Log omitted)
  * :heavy_check_mark: install-istio [#[950]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8428, 8429, 8430]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5771, 5772, 5773]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4173, 4174]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1259]](https://paste.centos.org/view/205b9e0a )
  * :question: run-kiali-ui-tests [#[21280, 21281, 21282, 21293, 21294, 21295, 21296, 21297, 21298, 21305, 21273, 21274, 21275, 21276, 21277, 21278, 21279]](https://paste.centos.org/view/86325a9f )

**Pull request merged**
