### PR TITLE
Enabled Traces tab test.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#565](https://paste.centos.org/view/14131e73 )
  * :question: upstream-istio-pipeline [#[443]](https://paste.centos.org/view/c39a23ec )
  * :heavy_check_mark: build-kiali [#[2323]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[288]](Log omitted)
  * :heavy_check_mark: install-istio [#[963]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8496, 8497, 8495]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5834, 5835, 5836]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4218, 4219]](Log omitted)
  * :black_circle: run-kiali-ui-tests-parallel [#[1272]](https://paste.centos.org/view/eb559109 )
  * :question: run-kiali-ui-tests [#[21504, 21505, 21506, 21507, 21508, 21509, 21510, 21511, 21495, 21496, 21497, 21498, 21499, 21500, 21501, 21502, 21503]](https://paste.centos.org/view/75ca03eb https://paste.centos.org/view/faff9c63 https://paste.centos.org/view/70355c46 https://paste.centos.org/view/b62a43de )

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#566](https://paste.centos.org/view/ffed1854 )
  * :question: upstream-istio-pipeline [#[444]](https://paste.centos.org/view/c631daf5 )
  * :heavy_check_mark: build-kiali [#[2324]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[289]](Log omitted)
  * :heavy_check_mark: install-istio [#[964]](Log omitted)
  * :heavy_check_mark: clean-environment [#[8500, 8501, 8503]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[5841, 5842, 5838]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[4220, 4222]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1273]](https://paste.centos.org/view/d575507c )
  * :question: run-kiali-ui-tests [#[21512, 21513, 21514, 21515, 21516, 21517, 21518, 21519, 21520, 21521, 21522, 21523, 21524, 21525, 21526, 21527, 21528]](https://paste.centos.org/view/4cdcaefe https://paste.centos.org/view/12615217 )

**Pull request merged**
