### PR TITLE
More logs for failures.

### PR DESCRIPTION
**Pull request by hhovsepy**
Increase sleep time.

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#439](https://paste.fedoraproject.org/paste/ChP7pB-czmgs33b39yMaCw)
  * :red_circle: upstream-pipeline [#[409]](https://paste.fedoraproject.org/paste/sCJZuQamkOXLKfd4fUNjDw)
  * :red_circle: build-kiali [#[669]](https://paste.fedoraproject.org/paste/2g9fXlsE7T4m808I6y-iLw)

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#440](https://paste.fedoraproject.org/paste/GXWOVzX9xi34BjLRpkQwdg)
  * :question: upstream-pipeline [#[410]](https://paste.fedoraproject.org/paste/jlMHGzq71R9eYJIu-JEE7g)
  * :heavy_check_mark: build-kiali [#[673]](https://paste.fedoraproject.org/paste/Qw-otP65AKxQP50GhyuzkA)
  * :heavy_check_mark: install-maistra [#[1190]](https://paste.fedoraproject.org/paste/SYiUiHyl6bSHGPPHmUUPpQ)
  * :heavy_check_mark: clean-environment [#[2635, 2636, 2637, 2638]](https://paste.fedoraproject.org/paste/s-Tdi4tIU~fSFKq3~q9bXg)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[1409, 1410, 1411]](https://paste.fedoraproject.org/paste/AvUm11R3IB4m8zNclGIH5A)
  * :heavy_check_mark: install-bookinfo [#[1329, 1330]](https://paste.fedoraproject.org/paste/xiyQ6R5gXN7qfgMFnU6Apw)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[729]](https://paste.fedoraproject.org/paste/TU0t-gwirySv8mY5Tp-odQ)
  * :question: run-kiali-ui-tests-parallel [#[322]](https://paste.fedoraproject.org/paste/H4dX7eMGhy0DvcsMFYxqVg)
  * :question: run-kiali-ui-tests [#[5386, 5387, 5388, 5389, 5390, 5391, 5392, 5393, 5394, 5395, 5396, 5397, 5398, 5399, 5400, 5401, 5402]](https://paste.fedoraproject.org/paste/OXmIT34ubM81~JFNFQVcwg)

**Comment by hhovsepy** [comment]
Rerun tests in another job, only known issue related failures.

**Pull request merged**
