### PR TITLE
Optimize tests running duration.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#338](https://paste.fedoraproject.org/paste/n5vzZm3G5SYMBm58g0RlxQ)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[3245]](https://paste.fedoraproject.org/paste/Gx3-6qzOyuEcUS97FbNhcA)
  * :heavy_check_mark: Istio-Upstream [#[1908]](https://paste.fedoraproject.org/paste/BQ22BkvI-6eKZ5DCz1naiA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6884]](https://paste.fedoraproject.org/paste/gZXm504gwzMLeSAtSiLCtg)
  * :red_circle: Kiali-on-Openshift [#[4111]](https://paste.fedoraproject.org/paste/MyS0ZA2YfAZ7BLkbZi2QAQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#339](https://paste.fedoraproject.org/paste/Yma9j~zipxbG5kd1VETGeA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[3246]](https://paste.fedoraproject.org/paste/EHj6syyi4JX99zvzEw6Ujw)
  * :heavy_check_mark: Istio-Upstream [#[1909]](https://paste.fedoraproject.org/paste/agX9PblcaebNDlWGkmxuSw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6885]](https://paste.fedoraproject.org/paste/LnIUssKF-GV43sB2DFgPrA)
  * :red_circle: Kiali-on-Openshift [#[4112]](https://paste.fedoraproject.org/paste/OTu-JRwJ-z3VId6v56XhmA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#340](https://paste.fedoraproject.org/paste/cHF~Wwjj1tA6wuJcv9Vz3g)
  * :black_circle: Istio-and-Kiali-on-Openshift [#[3248]](https://paste.fedoraproject.org/paste/lYTaVfyLgkiohzEn9LlRIA)
  * :black_circle: Istio-Upstream [#[1911]](https://paste.fedoraproject.org/paste/kG~n1JLGHZz-sVMxN6Nhrw)
  * :red_circle: Kiali-on-Openshift [#[4116]](https://paste.fedoraproject.org/paste/MKHD81f68eEMHVgebOu8EA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#341](https://paste.fedoraproject.org/paste/~iVypJFhuzMYDcJtvJpjIw)
  * :question: Istio-and-Kiali-on-Openshift [#[3249]](https://paste.fedoraproject.org/paste/BUqKCSwkr6Iz2Zvx92bMHw)
  * :heavy_check_mark: Istio-Upstream [#[1912]](https://paste.fedoraproject.org/paste/ROKmvJUv8BuMXFm-b4JK3Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6888, 6889, 6890, 6887]](https://paste.fedoraproject.org/paste/YJHUW7UJXC6Cs56FyTPolg)
  * :heavy_check_mark: Kiali-on-Openshift [#[4117, 4118]](https://paste.fedoraproject.org/paste/d6LrSQwVw4BEhqNYhLQkxQ)
  * :heavy_check_mark: install-bookinfo [#[3112, 3111]](https://paste.fedoraproject.org/paste/JYc~W7Sgi9OcGaH5AHyjRA)
  * :question: python-ui-tests-parallel [#[637]](https://paste.fedoraproject.org/paste/afOuG4R41NmhJcJGSuZQXg)
  * :question: run-python3-ui-tests [#[3552, 3553, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551]](https://paste.fedoraproject.org/paste/jaCrwZ8r~t~HXN3mmAGspw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#342](https://paste.fedoraproject.org/paste/HUW3UebR66EEP5YXHGuAmg)
  * :question: Istio-and-Kiali-on-Openshift [#[3250]](https://paste.fedoraproject.org/paste/FOhBuSqJSKlxU00WcShILQ)
  * :heavy_check_mark: Istio-Upstream [#[1913]](https://paste.fedoraproject.org/paste/ISgo-wYK3vCryQ~89dwaKA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6891, 6892, 6893, 6894]](https://paste.fedoraproject.org/paste/m-wsi-Jux1lzNQ9SBcDOdA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4120, 4119]](https://paste.fedoraproject.org/paste/ATwWFgMzhk~OZUxz8tRf7A)
  * :heavy_check_mark: install-bookinfo [#[3113, 3114]](https://paste.fedoraproject.org/paste/Cy61j9EaW0FbbGMMCRXwkQ)
  * :question: python-ui-tests-parallel [#[638]](https://paste.fedoraproject.org/paste/6dXP57m4CMCcud-qLfwnPA)
  * :question: run-python3-ui-tests [#[3554, 3555, 3556, 3557, 3558, 3559, 3560, 3561, 3562, 3563, 3564]](https://paste.fedoraproject.org/paste/GuJfqVX0nQU5eRTZ1nNHPg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#343](https://paste.fedoraproject.org/paste/1QWdh5gD-xN5eJZswUwlwQ)
  * :question: Istio-and-Kiali-on-Openshift [#[3260]](https://paste.fedoraproject.org/paste/yIuUTK4u5HNmvVzpjCP6rQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[4150, 4151]](https://paste.fedoraproject.org/paste/FDs~rFJTctvN2bf~v7BxVg)
  * :heavy_check_mark: Istio-Upstream [#[1924]](https://paste.fedoraproject.org/paste/620wzMUTBx77FFxwlpxW0A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6939, 6941, 6942, 6943]](https://paste.fedoraproject.org/paste/1ZFNcY-jbo8fvr1lvM9vEw)
  * :heavy_check_mark: install-bookinfo [#[3126, 3127]](https://paste.fedoraproject.org/paste/6YznhQWsZL4zV706RfxRTA)
  * :question: python-ui-tests-parallel [#[642]](https://paste.fedoraproject.org/paste/35FO84IX1OZb~AOQaOaGDA)
  * :question: run-python3-ui-tests [#[3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608]](https://paste.fedoraproject.org/paste/6peiopnAxZ621qhKCJ9F5Q)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#344](https://paste.fedoraproject.org/paste/Qzj-MCk5rgeFTJUnuhsHiA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[3271]](https://paste.fedoraproject.org/paste/yv6Ji1IdpfQ8DAeWdh0dvw)
  * :heavy_check_mark: Istio-Upstream [#[1939]](https://paste.fedoraproject.org/paste/GegY-0Y9Iq4h2XIFWhz8LA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7004, 7005]](https://paste.fedoraproject.org/paste/tOyfR54JQN9Ecf-qjKfjJA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4185, 4186]](https://paste.fedoraproject.org/paste/BVMaVnp2gNAVCaestKasbw)
  * :red_circle: old-bookinfo [#[3140, 3141]](https://paste.fedoraproject.org/paste/C~op40KDpuLXJ4KycESxyw)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#345](https://paste.fedoraproject.org/paste/3QW8MdZwygWojvN9KwZ7vQ)
  * :question: Istio-and-Kiali-on-Openshift [#[3272]](https://paste.fedoraproject.org/paste/MTgPrBgsizPKQAbemmYvSw)
  * :heavy_check_mark: Istio-Upstream [#[1940]](https://paste.fedoraproject.org/paste/duWNcKtn1yE0PSp0Q1u7tA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7008, 7009, 7010, 7006]](https://paste.fedoraproject.org/paste/BlpnwUzA2nC2fP5VzzjeaQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[4187, 4188]](https://paste.fedoraproject.org/paste/6sXh84SiaAXBtZLaL3ypbA)
  * :heavy_check_mark: old-bookinfo [#[3142, 3143]](https://paste.fedoraproject.org/paste/~NYwBRngrrK~r3xuXONy7w)
  * :question: python-ui-tests-parallel [#[645]](https://paste.fedoraproject.org/paste/EbyDQzCIqOxBgrr3uDxjfg)
  * :question: run-python3-ui-tests [#[3632, 3633, 3634, 3635, 3636, 3637, 3638, 3639, 3640, 3641, 3643]](https://paste.fedoraproject.org/paste/EDI~w9-yZBA4oMjBPTlEig)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#346](https://paste.fedoraproject.org/paste/gqWuAU-H-kqk1s2gSbP-Yg)
  * :question: Istio-and-Kiali-on-Openshift [#[3273]](https://paste.fedoraproject.org/paste/UQTlTeD36kyyguhMmEM50Q)
  * :heavy_check_mark: Istio-Upstream [#[1942]](https://paste.fedoraproject.org/paste/aQ3BD16dw31ETwXbmosKuA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7016, 7017, 7018, 7014]](https://paste.fedoraproject.org/paste/i17vDOBIzsA5ceEdUbJYdg)
  * :heavy_check_mark: Kiali-on-Openshift [#[4190, 4191]](https://paste.fedoraproject.org/paste/IxD-9OuzvwaD-lXnRiDn8Q)
  * :heavy_check_mark: old-bookinfo [#[3144, 3145]](https://paste.fedoraproject.org/paste/B7~~BTqbSXkmepsmBOykrg)
  * :question: python-ui-tests-parallel [#[646]](https://paste.fedoraproject.org/paste/8wXu2IK1AIXJTwfzrhGcHA)
  * :question: run-python3-ui-tests [#[3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3645, 3646, 3647]](https://paste.fedoraproject.org/paste/XkprGNku6-iAyUlmay6ClA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#347](https://paste.fedoraproject.org/paste/7TCrrYFjCbJz14JjiqttPA)
  * :question: Istio-and-Kiali-on-Openshift [#[3276]](https://paste.fedoraproject.org/paste/XZs--rz~vwN6m9pwoHn0Dg)
  * :heavy_check_mark: Istio-Upstream [#[1946]](https://paste.fedoraproject.org/paste/UN9GTg-gBa5Yj91ii1ZUdw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7026, 7027, 7028, 7029]](https://paste.fedoraproject.org/paste/S8-cNDT-9UPB6zpkq--upg)
  * :heavy_check_mark: Kiali-on-Openshift [#[4197, 4198]](https://paste.fedoraproject.org/paste/knYiGo3W-9nCX6uR9SC6cg)
  * :heavy_check_mark: old-bookinfo [#[3148, 3149]](https://paste.fedoraproject.org/paste/DvXSACK0j5dCIRbW04twvg)
  * :question: python-ui-tests-parallel [#[647]](https://paste.fedoraproject.org/paste/8tXRmk0krwmJ8DqSEeLGTQ)
  * :question: run-python3-ui-tests [#[3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666]](https://paste.fedoraproject.org/paste/-D4IMUkaoQ1c2kIPO5vIhw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#348](https://paste.fedoraproject.org/paste/fB5uLCZg3wQahHnCSz3j3g)
  * :question: Istio-and-Kiali-on-Openshift [#[3277]](https://paste.fedoraproject.org/paste/OcvIy4IbL-iS7ESnqT1qhA)
  * :heavy_check_mark: Istio-Upstream [#[1947]](https://paste.fedoraproject.org/paste/pctUhnJoCEZ1ClrquzjJQw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7032, 7033, 7034, 7035]](https://paste.fedoraproject.org/paste/b48iLLxFY860h8usyYoEOA)
  * :heavy_check_mark: Kiali-on-Openshift [#[4200, 4199]](https://paste.fedoraproject.org/paste/MH4xcnjsHU-Z8mCPikkcIw)
  * :heavy_check_mark: old-bookinfo [#[3150, 3151]](https://paste.fedoraproject.org/paste/XmQ1AC3bufpKpDAAQkeNqA)
  * :question: python-ui-tests-parallel [#[648]](https://paste.fedoraproject.org/paste/e~MNaBd9od2XZ5pzBGFUow)
  * :question: run-python3-ui-tests [#[3667, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677]](https://paste.fedoraproject.org/paste/YEoiuKll79YQ9zcSBCrQGg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#349](https://paste.fedoraproject.org/paste/T62HisQVfMgEc4TxcgdFJA)
 :red_circle: PRT Failed, Please Contact QE

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#350](https://paste.fedoraproject.org/paste/ok6yambQoBL5ZJQ-mktClA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[13]](https://paste.fedoraproject.org/paste/xVp2TYoJ4GlgSukpFLWftQ)
  * :heavy_check_mark: Istio-Upstream [#[1959]](https://paste.fedoraproject.org/paste/z0~TUAQ13BmjqAj4qVF-KQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7064, 7065, 7061, 7063]](https://paste.fedoraproject.org/paste/sqLh8nh3bw7Hiv4KuL~4pQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[48, 50]](https://paste.fedoraproject.org/paste/4vqCHATuwho8xo8CPuJOvA)
  * :heavy_check_mark: old-bookinfo [#[3157, 3158]](https://paste.fedoraproject.org/paste/a-e8QxSz2U4IGwj26v6yLg)
  * :heavy_check_mark: python-ui-tests-parallel [#[653]](https://paste.fedoraproject.org/paste/n~2ada1z~zGOxyYFqpICNw)
  * :heavy_check_mark: run-python3-ui-tests [#[3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731]](https://paste.fedoraproject.org/paste/D5Pu8I1WJTFj5EGmKWYHow)

**Pull request merged**
