### PR TITLE
Workload and Application health read from OC.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#671](https://paste.centos.org/view/05dc6281 )
  * :question: upstream-istio-pipeline [#[855]](https://paste.centos.org/view/9924485b )
  * :heavy_check_mark: build-kiali [#[3618]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1077]](Log omitted)
  * :heavy_check_mark: install-istio [#[1863]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14296, 14297, 14294, 14295]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10192, 10193, 10194, 10195]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7536, 7537, 7538]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2010]](https://paste.centos.org/view/9be6f936 )
  * :question: run-kiali-ui-tests [#[34336, 34337, 34338, 34339, 34340, 34324, 34325, 34326, 34327, 34328, 34329, 34330, 34331, 34332, 34333, 34334, 34335]](https://paste.centos.org/view/d2827e43 https://paste.centos.org/view/b48e1947 https://paste.centos.org/view/9c51062e https://paste.centos.org/view/92e3073d )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#672](https://paste.centos.org/view/15b14b5d )
  * :question: upstream-istio-pipeline [#[859]](https://paste.centos.org/view/462abd38 )
  * :heavy_check_mark: build-kiali [#[3624]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1080]](Log omitted)
  * :heavy_check_mark: install-istio [#[1871]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14320, 14317, 14318, 14319]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10224, 10221, 10222, 10223]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7561, 7562, 7563]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2016]](https://paste.centos.org/view/f76129db )
  * :question: run-kiali-ui-tests [#[34432, 34433, 34434, 34435, 34436, 34437, 34438, 34439, 34440, 34441, 34444, 34426, 34427, 34428, 34429, 34430, 34431]](https://paste.centos.org/view/69b7bf47 https://paste.centos.org/view/b9b25c73 https://paste.centos.org/view/c09a6fe6 )

**Pull request merged**
