### PR TITLE
Added Health fiter type

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#179](https://paste.fedoraproject.org/paste/a1-C1XxZ3quO2EjaPg5Xjg)
  * :question: python-ui-tests-parallel [#[174]](https://paste.fedoraproject.org/paste/wf8Pybl4CLxQOKhAJh~g7w)
  * :question: run-python-ui-tests [#[2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576]](https://paste.fedoraproject.org/paste/UZaeiXGYlYTh53ReS6OItA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#180](https://paste.fedoraproject.org/paste/HGiEeiEfDu5v8tkLYVRP8Q)
  * :black_circle: python-ui-tests-parallel [#[176]](https://paste.fedoraproject.org/paste/rAuky~aMIibMAOxlSI1pMA)
  * :black_circle: run-python-ui-tests [#[2592, 2593, 2594, 2595, 2587, 2588, 2589, 2590, 2591]](https://paste.fedoraproject.org/paste/mGE2U2-FUPjVCbPrDVIJOQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#181](https://paste.fedoraproject.org/paste/Zm762HheA2x8XoKXj6uM7g)
  * :question: python-ui-tests-parallel [#[177]](https://paste.fedoraproject.org/paste/XGaio0jnB7eDqL9GfVMrcQ)
  * :question: run-python-ui-tests [#[2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606]](https://paste.fedoraproject.org/paste/ABDXpCiYvmw6vN~sgXJH-A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#182](https://paste.fedoraproject.org/paste/jpzDW-pDsAX5jfZGAl8Tsg)
  * :red_circle: python-ui-tests-parallel [#[178]](https://paste.fedoraproject.org/paste/AR4s8cQO8AQODvuqg3JVqg)
  * :red_circle: run-python-ui-tests [#[2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617]](https://paste.fedoraproject.org/paste/LeQvWKLgwavi6khHBqvdsg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#183](https://paste.fedoraproject.org/paste/Yc2pF-5PXmkoJD~nkPftww)
  * :question: python-ui-tests-parallel [#[179]](https://paste.fedoraproject.org/paste/tBwyq1Uk6Ze7FPbCdeWuow)
  * :question: run-python-ui-tests [#[2624, 2625, 2626, 2627, 2628, 2618, 2619, 2620, 2621, 2622, 2623]](https://paste.fedoraproject.org/paste/Ud37NR6zsxaPPnaUc5Pn0g)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#184](https://paste.fedoraproject.org/paste/QKJ7tMT2Jm25RnMh3E2B7w)
  * :question: python-ui-tests-parallel [#[180]](https://paste.fedoraproject.org/paste/grPG646bJQ-h86532M3yZw)
  * :question: run-python-ui-tests [#[2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639]](https://paste.fedoraproject.org/paste/A37AjFI9Ds5ru6HMPoYQaQ)

**Comment by hhovsepy** [comment]
failures are not related to commit

**Pull request merged**
