### PR TITLE
Fixed Service name

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#352](https://paste.fedoraproject.org/paste/9gTkW4v0ZIxtB~WpEJlPYg)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[39]](https://paste.fedoraproject.org/paste/xQ6HjGE64bTOtvewfDqIfQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[117, 118]](https://paste.fedoraproject.org/paste/dEPhNmRgxMhS2PGjVoHnFQ)
  * :heavy_check_mark: Istio-Upstream [#[1985]](https://paste.fedoraproject.org/paste/h9Mj8yg5eL6c8sq6y6sbaQ)
  * :red_circle: Kiali-Istio-Checker [#[7180, 7181, 7182, 7183]](https://paste.fedoraproject.org/paste/EwyCMtaiX6oc6Opw6S~fhQ)
  * :red_circle: old-bookinfo [#[3192, 3193]](https://paste.fedoraproject.org/paste/tVWiC5Pa4QTZOw5kQNjPgA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#353](https://paste.fedoraproject.org/paste/mli-hp6Jc6tKfciTtMQHUA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[40]](https://paste.fedoraproject.org/paste/LOj1pcuORuzImMkq17KSwA)
  * :heavy_check_mark: Istio-Upstream [#[1986]](https://paste.fedoraproject.org/paste/hNrLyXuATpAmnErbrjF8hA)
  * :red_circle: Kiali-Istio-Checker [#[7184, 7185, 7186, 7187]](https://paste.fedoraproject.org/paste/BkqdWfHLbBzrnyGpTcj1Jg)
  * :heavy_check_mark: Kiali-on-Openshift [#[120, 119]](https://paste.fedoraproject.org/paste/EHlIXAgTP~W3GpQNabC5dw)
  * :red_circle: old-bookinfo [#[3194, 3195]](https://paste.fedoraproject.org/paste/9Wze-qAQEM8vzjFoeSU~lA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#354](https://paste.fedoraproject.org/paste/SAv0VPOULZeZQ6pf3ZpzDA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[42]](https://paste.fedoraproject.org/paste/mj8V8l1v35aOooc2ALB17A)
  * :heavy_check_mark: Istio-Upstream [#[1988]](https://paste.fedoraproject.org/paste/sOjIfaygy6ChX29XD3fubQ)
  * :red_circle: Kiali-Istio-Checker [#[7192, 7193, 7194, 7189]](https://paste.fedoraproject.org/paste/xvMOc7dt8q-dGSrsGfQywA)
  * :heavy_check_mark: Kiali-on-Openshift [#[122, 124]](https://paste.fedoraproject.org/paste/7Ou-RNeIC5826JVXc~cvcA)
  * :red_circle: old-bookinfo [#[3197, 3198]](https://paste.fedoraproject.org/paste/jQOEDS~8Gm20raMw5jl5dg)

**Pull request merged**
