### PR TITLE
Various fixes, test optimalization, added logging

### PR DESCRIPTION
**Pull request by FilipB**

### CODE REVIEW

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#452](https://paste.fedoraproject.org/paste/R7M34HqOzYDFloCxg2aTnA)
  * :red_circle: upstream-pipeline [#[466]](https://paste.fedoraproject.org/paste/eJTvrdIdSIa6j-pnw4F3yg)
  * :heavy_check_mark: build-kiali [#[769]](https://paste.fedoraproject.org/paste/LQV2HqSQaVzeMe0IlHvZyQ)
  * :red_circle: install-maistra [#[1283]](https://paste.fedoraproject.org/paste/~c5svCxL6UaNsgC1hBwkMQ)

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
