### PR TITLE
more potential failures fix

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#509](https://paste.centos.org/view/d2176c84 )
  * :red_circle: upstream-istio-pipeline [#[146]](https://paste.centos.org/view/abcb2d4d )
  * :heavy_check_mark: build-kiali [#[1490]](Log omitted)
  * :heavy_check_mark: install-istio [#[256]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5344, 5340, 5341, 5342]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3421, 3422]](Log omitted)
  * :red_circle: install-bookinfo [#[2627, 2628]](https://paste.centos.org/view/9fdcfed6 )
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1480]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#510](https://paste.centos.org/view/40e81c74 )
  * :question: upstream-istio-pipeline [#[147]](https://paste.centos.org/view/7d528e03 )
  * :heavy_check_mark: build-kiali [#[1492]](Log omitted)
  * :heavy_check_mark: install-istio [#[259]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5355, 5356, 5357, 5358]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3427, 3429, 3430]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2632, 2631]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1483]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[761]](https://paste.centos.org/view/e99b1f6a )
  * :question: run-kiali-ui-tests [#[12835, 12836, 12837, 12838, 12839, 12840, 12841, 12842, 12843, 12844, 12845, 12846, 12847, 12848, 12849, 12850, 12851]](https://paste.centos.org/view/8c717fc2 https://paste.centos.org/view/884c5627 https://paste.centos.org/view/9c114c02 https://paste.centos.org/view/b8fd71f2 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#511](https://paste.centos.org/view/491c673d )
  * :red_circle: upstream-istio-pipeline [#[166]](https://paste.centos.org/view/e965edd6 )
  * :heavy_check_mark: build-kiali [#[1506]](Log omitted)
  * :red_circle: install-istio [#[303]](https://paste.centos.org/view/5e6ea582 )
  * :heavy_check_mark: clean-environment [#[5485]](Log omitted)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#512](https://paste.centos.org/view/7cc3c222 )
  * :question: upstream-istio-pipeline [#[167]](https://paste.centos.org/view/6286de3f )
  * :heavy_check_mark: build-kiali [#[1507]](Log omitted)
  * :heavy_check_mark: install-istio [#[306]](Log omitted)
  * :heavy_check_mark: clean-environment [#[5490, 5491, 5492, 5493]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[3521, 3523, 3524]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2688, 2687]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1518]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[768]](https://paste.centos.org/view/b1745272 )
  * :question: run-kiali-ui-tests [#[12960, 12961, 12962, 12963, 12964, 12965, 12966, 12967, 12968, 12969, 12970, 12954, 12955, 12956, 12957, 12958, 12959]](https://paste.centos.org/view/9ea5a9ee https://paste.centos.org/view/aea47a1a https://paste.centos.org/view/4532c503 )

**Comment by hhovsepy** [comment]
Manual tests run caused 2 failures, fixing them in another PR.

**Pull request merged**
