### PR TITLE
Added new tests for Breadcrumb

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#383](https://paste.fedoraproject.org/paste/UDEsVZIaq7m4whOJikI1gQ)
  * :question: Istio-and-Kiali-on-Openshift [#[186]](https://paste.fedoraproject.org/paste/b48W0dDmy8pHBb3zTnniGQ)
  * :heavy_check_mark: Istio-Upstream [#[2135]](https://paste.fedoraproject.org/paste/R1h4zWQw~wlFSHDKRbU3Lw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7714, 7715]](https://paste.fedoraproject.org/paste/sFCKsuzS1E4J011A1lxMVQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[576, 577]](https://paste.fedoraproject.org/paste/xqcdf-TM~gcUcMEe8u2GaA)
  * :heavy_check_mark: old-bookinfo [#[3342]](https://paste.fedoraproject.org/paste/wXv89AY09iiqgKlJJ5deCg)
  * :question: python-ui-tests-parallel [#[752]](https://paste.fedoraproject.org/paste/o-pgfy6A~zw3qCQlCb0mDQ)
  * :question: run-python3-ui-tests [#[4832, 4833, 4834, 4835, 4836, 4837, 4838, 4839, 4840, 4841, 4831]](https://paste.fedoraproject.org/paste/Z~IarXFXlIauxHbekf0KSQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#388](https://paste.fedoraproject.org/paste/w~cdxiZeulnhaZXqDjJP9g)
  * :question: Istio-and-Kiali-on-Openshift [#[192]](https://paste.fedoraproject.org/paste/Fs3auvVUPFsM-aeu4~4gTw)
  * :heavy_check_mark: Istio-Upstream [#[2139]](https://paste.fedoraproject.org/paste/SQ07Ny0eSSaj45QtMUY44Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7726, 7727]](https://paste.fedoraproject.org/paste/T2Wpb6Q2sJfc2GZt1~JdAw)
  * :heavy_check_mark: Kiali-on-Openshift [#[587, 588]](https://paste.fedoraproject.org/paste/R2rGpr08f-VzOtDK~4MRjQ)
  * :heavy_check_mark: install-bookinfo [#[164, 165]](https://paste.fedoraproject.org/paste/Ae4GRbzWbc6qP6A7vLAUVw)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[45]](https://paste.fedoraproject.org/paste/dZToHqEuZDP86iB9Y7StgA)
  * :heavy_check_mark: clean-environment [#[200, 198, 199]](https://paste.fedoraproject.org/paste/TQOps94mkinhbJPobQmr0A)
  * :question: python-ui-tests-parallel [#[756]](https://paste.fedoraproject.org/paste/h3M99hHje4jYdIPONzR0yA)
  * :question: run-python3-ui-tests [#[4875, 4876, 4877, 4878, 4879, 4880, 4881, 4882, 4883, 4884, 4885]](https://paste.fedoraproject.org/paste/71yIdmY-aIJP4rdg4e4hyQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#389](https://paste.fedoraproject.org/paste/DQnZ~fyACqyxr2JNe0WziA)
  * :question: Istio-and-Kiali-on-Openshift [#[193]](https://paste.fedoraproject.org/paste/LR7Px997S~3OQc4DpEbzzg)
  * :heavy_check_mark: Istio-Upstream [#[2140]](https://paste.fedoraproject.org/paste/04iwyQ4VbSHdQZXUsjpNzw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7728, 7729]](https://paste.fedoraproject.org/paste/q6mzERDjnjgULn4v71kPew)
  * :heavy_check_mark: Kiali-on-Openshift [#[589, 590]](https://paste.fedoraproject.org/paste/GmVdGgRguNCQP3xUzUFTtQ)
  * :heavy_check_mark: install-bookinfo [#[166, 167]](https://paste.fedoraproject.org/paste/n9-yS-ttMyuCxKQS5xFKKQ)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[46]](https://paste.fedoraproject.org/paste/6OuTFnLYGoGkxgY0-WzkIA)
  * :heavy_check_mark: clean-environment [#[204, 205, 206]](https://paste.fedoraproject.org/paste/OBog-7-gMStcAdUivz4t~g)
  * :red_circle: python-ui-tests-parallel [#[757]](https://paste.fedoraproject.org/paste/suT5GsDTxvfPOePhKeYVtg)
  * :red_circle: run-python3-ui-tests [#[4896, 4886, 4887, 4888, 4889, 4890, 4891, 4892, 4893, 4894, 4895]](https://paste.fedoraproject.org/paste/o9dJDMjsjDxOdKiSXPAF2A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#390](https://paste.fedoraproject.org/paste/s4hh13HQCaKn0j5Bb~OYbA)
  * :question: Istio-and-Kiali-on-Openshift [#[194]](https://paste.fedoraproject.org/paste/zsWT1IHYssdENZV5uGoAYQ)
  * :heavy_check_mark: Istio-Upstream [#[2141]](https://paste.fedoraproject.org/paste/uip-nB67Mbge29qzQQTLJQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7731, 7732]](https://paste.fedoraproject.org/paste/98UGXwX7LsDaTv7yWI4GzQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[592, 593]](https://paste.fedoraproject.org/paste/9XSOrvM5Ewm95TIEYd4xMA)
  * :heavy_check_mark: install-bookinfo [#[168, 169]](https://paste.fedoraproject.org/paste/Qh2yEOAqvolaZhZR6Sulyg)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[47]](https://paste.fedoraproject.org/paste/h-F9JjH3yd8~vGMuufWDGg)
  * :heavy_check_mark: clean-environment [#[209, 210, 211]](https://paste.fedoraproject.org/paste/X0P1q9f0Gs5eDWmCsJ3VpQ)
  * :question: python-ui-tests-parallel [#[760]](https://paste.fedoraproject.org/paste/EDOYt932PKv12ko4EA3AAw)
  * :question: run-python3-ui-tests [#[4928, 4929, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927]](https://paste.fedoraproject.org/paste/8XDPN9ynjr0bXByFJL5FQg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#391](https://paste.fedoraproject.org/paste/pKcfj0u9WRMTKGFEhhI~XA)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[201]](https://paste.fedoraproject.org/paste/g7S6wocP-JNjhLUbRHschA)
  * :heavy_check_mark: Istio-Upstream [#[2147]](https://paste.fedoraproject.org/paste/p~H84kFb98ZH4N14alKMaA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7746]](https://paste.fedoraproject.org/paste/lvkLL8Vhml6TZY7IABcjRQ)
  * :red_circle: install-kiali-test-mesh-operator [#[59]](https://paste.fedoraproject.org/paste/5GX8RxY0oApXhRt8dTgAXw)
  * :heavy_check_mark: clean-environment [#[251]](https://paste.fedoraproject.org/paste/ZthU89jBvMV~eY6p0LL6YQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[609]](https://paste.fedoraproject.org/paste/eeBm59QZqhemxIWwnD3u7A)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#392](https://paste.fedoraproject.org/paste/CllnsPeivZz1wO43nuaM2w)
  * :question: Istio-and-Kiali-on-Openshift [#[202]](https://paste.fedoraproject.org/paste/eYXBMSdLGasIGZ7Pb~IUKA)
  * :heavy_check_mark: Istio-Upstream [#[2148]](https://paste.fedoraproject.org/paste/KuIg0fNnqUSV5PjYhSMPjw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7747, 7748]](https://paste.fedoraproject.org/paste/3E82RNFhHZtR7JtXyC8fww)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[60]](https://paste.fedoraproject.org/paste/kgwliFpsFodmZx93QaHcJw)
  * :heavy_check_mark: clean-environment [#[252, 253, 254]](https://paste.fedoraproject.org/paste/1ivsO1F9kHiS8AGMd9WsPw)
  * :heavy_check_mark: Kiali-on-Openshift [#[610, 611]](https://paste.fedoraproject.org/paste/Rg~hndBUtyb4FZNfVVyuwQ)
  * :heavy_check_mark: install-bookinfo [#[184, 185]](https://paste.fedoraproject.org/paste/BkaVRLFXC6n9iElI427VCg)
  * :question: python-ui-tests-parallel [#[763]](https://paste.fedoraproject.org/paste/r-Ucp6mw-rqNOCLRIVjB7w)
  * :question: run-python3-ui-tests [#[4960, 4961, 4962, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959]](https://paste.fedoraproject.org/paste/1HYqBrVI-iXr-Jh~TgkjOw)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#393](https://paste.fedoraproject.org/paste/nbtsg5sS8aQqp0dV~kHNHw)
  * :question: Istio-and-Kiali-on-Openshift [#[203]](https://paste.fedoraproject.org/paste/qOPKGoRN3R8PFxRXWad2ZQ)
  * :heavy_check_mark: Istio-Upstream [#[2149]](https://paste.fedoraproject.org/paste/3rmp96GXmYM1559QBjMh8Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7749, 7750]](https://paste.fedoraproject.org/paste/libDBXAWYTuYOzFoNN3yOQ)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[63]](https://paste.fedoraproject.org/paste/LcKMP~KemqLWje36H0yZYA)
  * :heavy_check_mark: clean-environment [#[259, 260, 261]](https://paste.fedoraproject.org/paste/yXmMwFADHvcpsMGYhkxYeA)
  * :heavy_check_mark: Kiali-on-Openshift [#[612, 613]](https://paste.fedoraproject.org/paste/pFVJPOMEDZeqZJIf0XEGIQ)
  * :heavy_check_mark: install-bookinfo [#[189, 190]](https://paste.fedoraproject.org/paste/6eyMUI0zXcoz5XkmetdYEg)
  * :question: python-ui-tests-parallel [#[764]](https://paste.fedoraproject.org/paste/JQqfdrzenbsZHZ5k0e~Jzg)
  * :question: run-python3-ui-tests [#[4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973]](https://paste.fedoraproject.org/paste/KulCw~fTo1X0nbDXBBxRkg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#394](https://paste.fedoraproject.org/paste/yJi0Tp3o4rSY5F5aPRd5cA)
  * :question: Istio-and-Kiali-on-Openshift [#[204]](https://paste.fedoraproject.org/paste/OtuoBoT247LUF3bSSH0LSw)
  * :heavy_check_mark: Istio-Upstream [#[2150]](https://paste.fedoraproject.org/paste/GYErAnl1EnwTB0yhzDcSFg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[7752, 7751]](https://paste.fedoraproject.org/paste/uj1XLII6wQnHh6iXdgs7Ww)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[64]](https://paste.fedoraproject.org/paste/5Rzmc-JZqC2AKmfAje3g8w)
  * :heavy_check_mark: clean-environment [#[264, 262, 263]](https://paste.fedoraproject.org/paste/wMVO2MikK8fFdbS0uGkvcA)
  * :heavy_check_mark: Kiali-on-Openshift [#[614, 615]](https://paste.fedoraproject.org/paste/Pph2gbNKGBDwDcNehG9OjQ)
  * :heavy_check_mark: install-bookinfo [#[192, 191]](https://paste.fedoraproject.org/paste/qPuY-vQyuQ1Kpbpmf5~AVg)
  * :question: python-ui-tests-parallel [#[765]](https://paste.fedoraproject.org/paste/AXNAJXjfSHAWss~y42dzuA)
  * :question: run-python3-ui-tests [#[4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984]](https://paste.fedoraproject.org/paste/YhIuZj~RVypeh0OB9zta4w)

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
Manual rerun of the job passed, failing tests are on other areas.

**Pull request merged**
