### PR TITLE
Fixed Namespace selector

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#328](https://paste.fedoraproject.org/paste/ZRIZObPOSfdF8vs8xFRJkg)
  * :question: Istio-and-Kiali-on-Openshift [#[3140]](https://paste.fedoraproject.org/paste/w0fexfPrN-ctrcO6TsXVJg)
  * :heavy_check_mark: Istio-Upstream [#[1807]](https://paste.fedoraproject.org/paste/6WRUBv0aqckAjm1O1~s48Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6529, 6530, 6531]](https://paste.fedoraproject.org/paste/CfcSd1GSlpuZljKSycgXVA)
  * :heavy_check_mark: Kiali-on-Openshift [#[3876, 3877]](https://paste.fedoraproject.org/paste/QCKQC83c35gK5jILwHkppA)
  * :heavy_check_mark: install-bookinfo [#[2990, 2991]](https://paste.fedoraproject.org/paste/7LLU8lF8h7vOnLeJ~1Vz3A)
  * :question: python-ui-tests-parallel [#[612]](https://paste.fedoraproject.org/paste/8GVSAzPChMzLV5OeR7y1yA)
  * :question: run-python3-ui-tests [#[3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278]](https://paste.fedoraproject.org/paste/1PtSULJWZhQMqYvPi727Hg)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#329](https://paste.fedoraproject.org/paste/u0Sv0b2h07wE2L9Var2Jjw)
  * :question: Istio-and-Kiali-on-Openshift [#[3146]](https://paste.fedoraproject.org/paste/IVQ3iBW5nb8a4GYWmQNWBQ)
  * :heavy_check_mark: Istio-Upstream [#[1813]](https://paste.fedoraproject.org/paste/axcHGtl6hgtqX5ick6qc0A)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6552, 6549, 6550, 6551]](https://paste.fedoraproject.org/paste/nf4~4chTFe4CFWpDE9y~ew)
  * :heavy_check_mark: Kiali-on-Openshift [#[3889, 3890]](https://paste.fedoraproject.org/paste/foUS3pvOQ9GYon8E0xUIoA)
  * :heavy_check_mark: install-bookinfo [#[2998, 2999]](https://paste.fedoraproject.org/paste/K3fUhz~AGpA997tFVxAjUQ)
  * :question: python-ui-tests-parallel [#[614]](https://paste.fedoraproject.org/paste/~wLmn9NVSar4G0nTLZ4ANg)
  * :question: run-python3-ui-tests [#[3296, 3297, 3298, 3299, 3300, 3290, 3291, 3292, 3293, 3294, 3295]](https://paste.fedoraproject.org/paste/0mD~oS7L3CzJajb5x6wptA)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#330](https://paste.fedoraproject.org/paste/EVtIH2T6VgBavKCeSYx2QA)
  * :question: Istio-and-Kiali-on-Openshift [#[3150]](https://paste.fedoraproject.org/paste/b3NxJXdlV8VclBwjiyJVag)
  * :heavy_check_mark: Istio-Upstream [#[1817]](https://paste.fedoraproject.org/paste/N0sZDV-ZBM0sQv9NvmUoMQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[6568, 6565, 6566, 6567]](https://paste.fedoraproject.org/paste/9ApvHyrHd29Rvrya0d0~fA)
  * :heavy_check_mark: Kiali-on-Openshift [#[3900, 3901]](https://paste.fedoraproject.org/paste/lIfCKaIOcsXpO8jfQPtk2A)
  * :heavy_check_mark: install-bookinfo [#[3003, 3004]](https://paste.fedoraproject.org/paste/A4E4Ddpoc2r7PBuaZQr2Zg)
  * :question: python-ui-tests-parallel [#[616]](https://paste.fedoraproject.org/paste/SXOO5RZVbRbnjAWgChH3ug)
  * :black_circle: run-python3-ui-tests [#[3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322]](https://paste.fedoraproject.org/paste/FXbsnP8Pxc5VMgraQ3e6oQ)

**Comment by hhovsepy** [comment]
Tests passed https://jenkins2.bc.jonqe.lab.eng.bos.redhat.com:8443/job/run-python3-ui-tests/3322/

**Pull request merged**
