### PR TITLE
Fixed Overview and Routing Wizard actions.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#623](https://paste.centos.org/view/f7845e12 )
  * :question: upstream-istio-pipeline [#[674]](https://paste.centos.org/view/b9e6f3b7 )
  * :heavy_check_mark: build-kiali [#[2950]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[670]](Log omitted)
  * :heavy_check_mark: install-istio [#[1457]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10901, 10902, 10903]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7433, 7434, 7435]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5228, 5229]](Log omitted)
  * :red_circle: run-kiali-ui-tests-parallel [#[1600]](https://paste.centos.org/view/d5966b27 )
  * :red_circle: run-kiali-ui-tests [#[27048, 27049, 27050, 27051, 27052, 27053, 27054, 27055, 27056, 27057, 27058, 27059, 27060, 27061, 27062, 27063, 27064]](https://paste.centos.org/view/b2d9ed00 https://paste.centos.org/view/06fcbf76 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#624](Log omitted)
  * :heavy_check_mark: upstream-istio-pipeline [#[675]](Log omitted)
  * :heavy_check_mark: build-kiali [#[2951]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[671]](Log omitted)
  * :heavy_check_mark: install-istio [#[1459]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10907, 10910, 10911]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7440, 7441, 7438]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5234, 5235]](Log omitted)
  * :heavy_check_mark: run-kiali-ui-tests-parallel [#[1601]](Log omitted)
  * :heavy_check_mark: run-kiali-ui-tests [#[27072, 27073, 27074, 27075, 27076, 27077, 27078, 27079, 27080, 27081, 27065, 27066, 27067, 27068, 27069, 27070, 27071]](Log omitted)

**Pull request merged**
