### PR TITLE
Make Browser runnign in Private mode.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#297](https://paste.fedoraproject.org/paste/xNCcb69EaArqAB1LgWrc3Q)
  * :question: Istio-and-Kiali-on-Openshift [#[2901]](https://paste.fedoraproject.org/paste/NxgNmV41d-wULG99q4GPbQ)
  * :heavy_check_mark: Istio-Upstream [#[1572]](https://paste.fedoraproject.org/paste/xI53tu79Eo6E1HuWf8y0RQ)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5752, 5753, 5754, 5755]](https://paste.fedoraproject.org/paste/UOfGT~7lkLFWHEUdSs0OnQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[3397, 3398]](https://paste.fedoraproject.org/paste/V3PMqFUEOr8NWqEA9vKDyA)
  * :heavy_check_mark: install-bookinfo [#[2722, 2723]](https://paste.fedoraproject.org/paste/oLpxq4IneOcqq6KwJZJgRw)
  * :question: python-ui-tests-parallel [#[555]](https://paste.fedoraproject.org/paste/L8IHpsv9SWrKI3O-gGB5FQ)
  * :question: run-python3-ui-tests [#[2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649]](https://paste.fedoraproject.org/paste/H2NeMQ1M3ibS670-s~O0JQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#299](https://paste.fedoraproject.org/paste/CpDO0oZ94cMttqXEVdf~sQ)
  * :question: Istio-and-Kiali-on-Openshift [#[2903]](https://paste.fedoraproject.org/paste/IEEh28kYv-eaywtQtfu8WA)
  * :heavy_check_mark: Istio-Upstream [#[1574]](https://paste.fedoraproject.org/paste/JoXeEW7Fn20GxxLtk0O5EA)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5760, 5763, 5765, 5767]](https://paste.fedoraproject.org/paste/EKljLwRQe14bv6Vl1AKnDw)
  * :heavy_check_mark: Kiali-on-Openshift [#[3401, 3404]](https://paste.fedoraproject.org/paste/DUeGBjdIRIHORyH3iVuPcA)
  * :heavy_check_mark: install-bookinfo [#[2728, 2727]](https://paste.fedoraproject.org/paste/DdAasOebJkrVJplN9QLDEA)
  * :question: python-ui-tests-parallel [#[557]](https://paste.fedoraproject.org/paste/M4JYR14gQ5UdxGW2qJHt1Q)
  * :question: run-python3-ui-tests [#[2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670]](https://paste.fedoraproject.org/paste/ZlVt8NXqWFZUL5t~byQ9mA)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#300](https://paste.fedoraproject.org/paste/rAVvk9v6K5FPtzwn0Y~ZnA)
  * :heavy_check_mark: Istio-and-Kiali-on-Openshift [#[2904]](https://paste.fedoraproject.org/paste/u1VSZeilM3dFqN5kzQMaWw)
  * :heavy_check_mark: Istio-Upstream [#[1575]](https://paste.fedoraproject.org/paste/fCsVFNgz4aWtFR5z7DOu1Q)
  * :heavy_check_mark: Kiali-Istio-Checker [#[5768, 5769, 5770, 5771]](https://paste.fedoraproject.org/paste/x5Q4wtwYlSw0QigiSvp8vg)
  * :heavy_check_mark: Kiali-on-Openshift [#[3405, 3406]](https://paste.fedoraproject.org/paste/g5af88FtsWg3A9UNLFN2Rg)
  * :heavy_check_mark: install-bookinfo [#[2729, 2730]](https://paste.fedoraproject.org/paste/kDCgju6R8cacKzDeML80~g)
  * :heavy_check_mark: python-ui-tests-parallel [#[558]](https://paste.fedoraproject.org/paste/t-eBwjzOpZ8T95LV136W8A)
  * :heavy_check_mark: run-python3-ui-tests [#[2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682]](https://paste.fedoraproject.org/paste/QGep3SzI4rGJMuvXcz4VLg)

**Pull request merged**
