### PR TITLE
Istio Config Details: OC call

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#256](https://paste.fedoraproject.org/paste/Xc2ZkZsEXq5f~RuU8oZ8qg)
  * :question: Istio-and-Kiali-on-Openshift [#[2396]](https://paste.fedoraproject.org/paste/PyHGyDzK9VQfRFfI1XtWFw)
  * :heavy_check_mark: Istio-Upstream [#[1065]](https://paste.fedoraproject.org/paste/odRpwL5UHaGrTzt2K937wg)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3704, 3705, 3706, 3707]](https://paste.fedoraproject.org/paste/LLTeZS1uixjSul3G7-DfdQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[2121, 2122]](https://paste.fedoraproject.org/paste/BO0RWWVjozlqiV5JLihxBQ)
  * :heavy_check_mark: install-bookinfo [#[2001, 2002]](https://paste.fedoraproject.org/paste/W2MyIbP1Bofdr8a7e-RDAA)
  * :question: python-ui-tests-parallel [#[398]](https://paste.fedoraproject.org/paste/7a56Ml-kbUItPLSDzEtsDg)
  * :question: run-python3-ui-tests [#[934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944]](https://paste.fedoraproject.org/paste/3OkwBc4PF7LlgzuDImVGfQ)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#257](https://paste.fedoraproject.org/paste/7U-OoNSDBA8ZSjX8WHkP~A)
  * :red_circle: Istio-and-Kiali-on-Openshift [#[2399]](https://paste.fedoraproject.org/paste/mSlHOCBrXsBoTzB5NgWy8A)
  * :heavy_check_mark: Istio-Upstream [#[1068]](https://paste.fedoraproject.org/paste/fwiWge8lkdDtjQL5LrF5Yw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3716, 3717]](https://paste.fedoraproject.org/paste/fLJMJwcl9KRGl4CVxhMcxA)
  * :heavy_check_mark: Kiali-on-Openshift [#[2129, 2127]](https://paste.fedoraproject.org/paste/ZGGAa1-SrUqZw98dvKq6RQ)
  * :red_circle: install-bookinfo [#[2009, 2010]](https://paste.fedoraproject.org/paste/4S7pOBhrWsc4xdELwNR4Ew)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#258](https://paste.fedoraproject.org/paste/ID9le9EPbk~eWMzq5DKJog)
  * :question: Istio-and-Kiali-on-Openshift [#[2403]](https://paste.fedoraproject.org/paste/298KRwZMBxPSTafZuV8-yg)
  * :heavy_check_mark: Istio-Upstream [#[1071]](https://paste.fedoraproject.org/paste/4QSvTrCCq2qqYZkLfRZsew)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3724, 3725, 3726, 3727]](https://paste.fedoraproject.org/paste/Uu9D1Mplrd-NxIIilUH-RQ)
  * :heavy_check_mark: Kiali-on-Openshift [#[2132, 2133]](https://paste.fedoraproject.org/paste/hhKluvXbf8~rvEniA2F5ag)
  * :heavy_check_mark: install-bookinfo [#[2020, 2021]](https://paste.fedoraproject.org/paste/JynWZJSHzyPRDIWSewhvrw)
  * :question: python-ui-tests-parallel [#[399]](https://paste.fedoraproject.org/paste/8-JA-wyEMu5lrHk5mV~w1w)
  * :question: run-python3-ui-tests [#[945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955]](https://paste.fedoraproject.org/paste/jjLDMS2acoX7kT89aZjg9A)

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#259](https://paste.fedoraproject.org/paste/njEEILEZGZMBWr3bpmOVzw)
  * :question: Istio-and-Kiali-on-Openshift [#[2410]](https://paste.fedoraproject.org/paste/dWO~3kQ5lE5raC88xQwIpg)
  * :heavy_check_mark: Istio-Upstream [#[1078]](https://paste.fedoraproject.org/paste/T-pTfUv2Z4B-oCiQk-r7bw)
  * :heavy_check_mark: Kiali-Istio-Checker [#[3744, 3745, 3746, 3743]](https://paste.fedoraproject.org/paste/EuhAAdBv4~3waMnGbmjzlg)
  * :heavy_check_mark: Kiali-on-Openshift [#[2141, 2142]](https://paste.fedoraproject.org/paste/NMN0irbm67dsFhfu3xsAdA)
  * :heavy_check_mark: install-bookinfo [#[2029, 2030]](https://paste.fedoraproject.org/paste/IYivXvBBXARsk3m8ONlTcg)
  * :question: python-ui-tests-parallel [#[400]](https://paste.fedoraproject.org/paste/x2SL-ZAWcKqeInRsnKRRXw)
  * :question: run-python3-ui-tests [#[960, 961, 962, 963, 964, 965, 966, 956, 957, 958, 959]](https://paste.fedoraproject.org/paste/kBuSkqUkXd9V3MFMmO8y3A)

**Comment by hhovsepy** [comment]
Failing tests are not related to namespaces. Will be fixed in another commit.

**Pull request merged**
