### PR TITLE
New Error Rates applied into automations.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#621](https://paste.centos.org/view/e127ee0b )
  * :question: upstream-istio-pipeline [#[670]](https://paste.centos.org/view/12d80f3a )
  * :heavy_check_mark: build-kiali [#[2930]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[659]](Log omitted)
  * :heavy_check_mark: install-istio [#[1445]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10816, 10817, 10815]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7362, 7363, 7364]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5180, 5181]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1592]](https://paste.centos.org/view/00e6f453 )
  * :question: run-kiali-ui-tests [#[26912, 26913, 26914, 26915, 26916, 26917, 26918, 26919, 26920, 26921, 26922, 26923, 26924, 26925, 26926, 26910, 26911]](https://paste.centos.org/view/e819469f https://paste.centos.org/view/76c19c29 https://paste.centos.org/view/f0044e1e https://paste.centos.org/view/75a43a56 )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#622](https://paste.centos.org/view/9087ec99 )
  * :question: upstream-istio-pipeline [#[672]](https://paste.centos.org/view/e97f6c96 )
  * :heavy_check_mark: build-kiali [#[2936]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[664]](Log omitted)
  * :heavy_check_mark: install-istio [#[1448]](Log omitted)
  * :heavy_check_mark: clean-environment [#[10843, 10844, 10845]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[7386, 7387, 7388]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[5198, 5199]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1596]](https://paste.centos.org/view/477181e4 )
  * :question: run-kiali-ui-tests [#[26976, 26977, 26978, 26979, 26980, 26988, 26989, 26990, 26991, 26992, 26993, 26994, 26971, 26972, 26973, 26974, 26975]](https://paste.centos.org/view/461c857b https://paste.centos.org/view/ea9e50f0 https://paste.centos.org/view/6cec09b9 https://paste.centos.org/view/70f4864e https://paste.centos.org/view/daa72b43 )

**Pull request merged**
