### PR TITLE
Fixed failing test

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#87](https://paste.fedoraproject.org/paste/J2RwqIzAY~VIu6DhSJDHRg)
  * :red_circle: run-python-ui-tests [#509](https://paste.fedoraproject.org/paste/Tl6ZX2lz9qgKWFghBgW5jg)

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-ui-test-pr [#88](https://paste.fedoraproject.org/paste/-5xVhB7S-3Rzl9p00YNP3Q)
  * :red_circle: run-python-ui-tests [#510](https://paste.fedoraproject.org/paste/b9KMifmqp6LTnF6LkJwlUQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#89](https://paste.fedoraproject.org/paste/nVUfFjMtFJTIKb7pHS95AQ)
  * :heavy_check_mark: run-python-ui-tests [#511](https://paste.fedoraproject.org/paste/JJgik-cgxvkH83Ou5i0QLg)

**Pull request merged**
