### PR TITLE
New grouping for UI tests parallel run.

### PR DESCRIPTION
**Pull request by FilipB**
Run 10 groups of UI tests first which are RO and then 6 groups of tests which would collide with first group of tests and then run the last group

### CODE REVIEW

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#408](https://paste.fedoraproject.org/paste/haXOSJjjemoCVEbgBpyxCQ)
  * :red_circle: upstream-pipeline [#[97]](https://paste.fedoraproject.org/paste/qJoo1SKyAOTpywiIWhtWJg)
  * :heavy_check_mark: build-kiali [#[151]](https://paste.fedoraproject.org/paste/TSO8GY2DLHFUDkgpn7shpw)
  * :red_circle: install-maistra [#[621]](https://paste.fedoraproject.org/paste/dR-aDGR65Ec6HGp9CVZXUA)
  * :heavy_check_mark: clean-environment [#[991]](https://paste.fedoraproject.org/paste/yrTIPJfkUUV3O6vG0CYciA)

**Comment by FilipB** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#410](https://paste.fedoraproject.org/paste/xR-tPtYOGss9Al~LyeGY~Q)
  * :question: upstream-pipeline [#[99]](https://paste.fedoraproject.org/paste/38-5EXwzVKSMuvuj~XuC1w)
  * :heavy_check_mark: build-kiali [#[153]](https://paste.fedoraproject.org/paste/8mlHxmNAcKp64Jk5biWLNg)
  * :heavy_check_mark: install-maistra [#[623]](https://paste.fedoraproject.org/paste/LwsXoMhjBHuESYWypn1cXA)
  * :heavy_check_mark: clean-environment [#[993, 995, 996, 997]](https://paste.fedoraproject.org/paste/DVLjT4oYPHkO7s7esKk91Q)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[164, 165, 167]](https://paste.fedoraproject.org/paste/4gG7ub6TGdsblhuOu~vsKw)
  * :heavy_check_mark: install-bookinfo [#[546, 547]](https://paste.fedoraproject.org/paste/sXi2tXzWvIq7gR-oJKgTVA)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[294]](https://paste.fedoraproject.org/paste/Gjj6qi2e82NvMr0uK2jeKg)
  * :question: run-kiali-ui-tests-parallel [#[27]](https://paste.fedoraproject.org/paste/rDpsHtzXllgzIrk8123-Bw)
  * :question: run-kiali-ui-tests [#[355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 375, 376, 377, 378, 379, 380, 381]](https://paste.fedoraproject.org/paste/uASLgJhN5jvm98Pg8Qgp4w)

**Comment by FilipB** [comment]
Expected failures

**Pull request merged**
