### PR TITLE
Fixed failing tests based on latest UI changes.

### PR DESCRIPTION
**Pull request by hhovsepy**
PF4 related changes, more fixes. Added more tests for label filters in Apps, Workloads and Services.

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#525](https://paste.centos.org/view/43102fdf )
  * :question: upstream-istio-pipeline [#[253]](https://paste.centos.org/view/2b16e08d )
  * :heavy_check_mark: build-kiali [#[1779]](Log omitted)
  * :heavy_check_mark: install-istio [#[482]](Log omitted)
  * :heavy_check_mark: clean-environment [#[6832, 6833, 6830, 6831]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4482, 4483, 4484]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3321, 3322]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1887]](Log omitted)
  * :black_circle: run-kiali-ui-tests-parallel [#[948]](https://paste.centos.org/view/907faa28 )
  * :question: run-kiali-ui-tests [#[16000, 16001, 16002, 16003, 16004, 16005, 16006, 15990, 15991, 15992, 15993, 15994, 15995, 15996, 15997, 15998, 15999]](https://paste.centos.org/view/ae04084e https://paste.centos.org/view/e8b06435 https://paste.centos.org/view/77bd590c )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#532](https://paste.centos.org/view/5e1ba0f6 )
  * :question: upstream-istio-pipeline [#[286]](https://paste.centos.org/view/f78333bd )
  * :heavy_check_mark: build-kiali [#[1883]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[29]](Log omitted)
  * :heavy_check_mark: install-istio [#[568]](Log omitted)
  * :heavy_check_mark: clean-environment [#[7128, 7125, 7126, 7127]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4723, 4724, 4725]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3482, 3483]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1997]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[1008]](https://paste.centos.org/view/ccbd9eb4 )
  * :question: run-kiali-ui-tests [#[17024, 17025, 17009, 17010, 17011, 17012, 17013, 17014, 17015, 17016, 17017, 17018, 17019, 17020, 17021, 17022, 17023]](https://paste.centos.org/view/d820ef81 https://paste.centos.org/view/9a5ed6df )

**Pull request merged**
