### PR TITLE
Date tooltip text verification. Fixed failing tests.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#492](https://paste.centos.org/view/134f78e1 )
  * :question: upstream-istio-pipeline [#[56]](https://paste.centos.org/view/f491c6f9 )
  * :heavy_check_mark: build-kiali [#[1135]](Log omitted)
  * :heavy_check_mark: install-istio [#[70]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4099, 4100, 4101, 4094]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2514, 2517, 2518]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2054, 2055]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1143]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[581]](https://paste.centos.org/view/a29d3118 )
  * :question: run-kiali-ui-tests [#[9773, 9774, 9775, 9776, 9777, 9778, 9779, 9780, 9781, 9782, 9783, 9784, 9785, 9786, 9787, 9788, 9789]](https://paste.centos.org/view/57ff26ef https://paste.centos.org/view/0c2772b9 https://paste.centos.org/view/8ee7ab7e )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#493](https://paste.centos.org/view/022f57ec )
  * :question: upstream-istio-pipeline [#[58]](https://paste.centos.org/view/5ac1acd0 )
  * :heavy_check_mark: build-kiali [#[1146]](Log omitted)
  * :heavy_check_mark: install-istio [#[82]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4120, 4121, 4118, 4119]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2536, 2534, 2535]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2064, 2063]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1148]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[584]](https://paste.centos.org/view/5235b7a8 )
  * :question: run-kiali-ui-tests [#[9824, 9825, 9826, 9827, 9828, 9829, 9830, 9831, 9832, 9833, 9834, 9835, 9836, 9837, 9838, 9839, 9840]](https://paste.centos.org/view/f41846f8 https://paste.centos.org/view/073b1935 https://paste.centos.org/view/e659196b )

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#494](https://paste.centos.org/view/a0cf6b16 )
  * :question: upstream-istio-pipeline [#[72]](https://paste.centos.org/view/49a5f546 )
  * :heavy_check_mark: build-kiali [#[1188]](Log omitted)
  * :heavy_check_mark: install-istio [#[104]](Log omitted)
  * :heavy_check_mark: clean-environment [#[4344, 4347, 4342, 4343]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[2689, 2694, 2695]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[2146, 2147]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1196]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[603]](https://paste.centos.org/view/ed60cad4 )
  * :question: run-kiali-ui-tests [#[10147, 10148, 10149, 10150, 10151, 10152, 10153, 10154, 10155, 10156, 10157, 10158, 10159, 10160, 10161, 10162, 10163]](https://paste.centos.org/view/f266295a https://paste.centos.org/view/c1f3c813 )

**Pull request merged**
