### PR TITLE
Added new validation for global sidecars.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#518](https://paste.centos.org/view/239cf736 )
  * :question: upstream-istio-pipeline [#[206]](https://paste.centos.org/view/ab0a57d4 )
  * :heavy_check_mark: build-kiali [#[1632]](Log omitted)
  * :heavy_check_mark: install-istio [#[389]](Log omitted)
  * :heavy_check_mark: clean-environment [#[6168, 6165, 6166, 6167]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[4013, 4014, 4015]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[3021, 3022]](Log omitted)
  * :heavy_check_mark: install-kiali-test-mesh-operator [#[1708]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[846]](https://paste.centos.org/view/c8c02d1e )
  * :question: run-kiali-ui-tests [#[14280, 14281, 14282, 14283, 14284, 14285, 14286, 14287, 14288, 14289, 14290, 14291, 14292, 14293, 14294, 14295, 14296]](https://paste.centos.org/view/02bd0bf0 https://paste.centos.org/view/7a5d993f )

**Comment by hhovsepy** [comment]
kialiqece

**Comment by hhovsepy** [comment]
Newly added test is passing.

**Pull request merged**
