### PR TITLE
Fixed failing tests

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#153](https://paste.fedoraproject.org/paste/TkJaE3OakCZrjxir5R-qww)
  * :question: python-ui-tests-parallel [#[127]](https://paste.fedoraproject.org/paste/COcN4tyxrSGhIfFSA6fELw)
  * :question: run-python-ui-tests [#[2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059]](https://paste.fedoraproject.org/paste/CesrK5tCPDHYcVl1xpqeNA)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#154](https://paste.fedoraproject.org/paste/M0c6zZUeQOvtIiD1nUFXTg)
  * :question: python-ui-tests-parallel [#[128]](https://paste.fedoraproject.org/paste/kZLD4hvm1lFwHswHWYaUIg)
  * :question: run-python-ui-tests [#[2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070]](https://paste.fedoraproject.org/paste/LX4UMlbcHy0lwASCysnblw)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#155](https://paste.fedoraproject.org/paste/-BxJFRuoeenbk6qsFQ6fTw)
  * :question: python-ui-tests-parallel [#[129]](https://paste.fedoraproject.org/paste/aeoTtQmu71mV-RR4e2iWUw)
  * :question: run-python-ui-tests [#[2080, 2081, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079]](https://paste.fedoraproject.org/paste/yt2sz-P-xgiol7L8NP5VWg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#156](https://paste.fedoraproject.org/paste/jU6sO7s2A5f~btNgkEMT8w)
  * :question: python-ui-tests-parallel [#[130]](https://paste.fedoraproject.org/paste/2WReD42Vuk~yjfGXUBnKTQ)
  * :question: run-python-ui-tests [#[2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092]](https://paste.fedoraproject.org/paste/p67JOMAHeUnq2m0Rqi08mg)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#157](https://paste.fedoraproject.org/paste/GPNvES~6BuhKmIPjrJs9WQ)
  * :question: python-ui-tests-parallel [#[131]](https://paste.fedoraproject.org/paste/5rA3tjgVDjlRMUoSBKYKfA)
  * :question: run-python-ui-tests [#[2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103]](https://paste.fedoraproject.org/paste/aIwUPqJePjFpK1pMfKZpHQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#158](https://paste.fedoraproject.org/paste/eFi3KpHNlCoyLGY~9dbiOw)
  * :question: python-ui-tests-parallel [#[134]](https://paste.fedoraproject.org/paste/~8057QrrnkRrb97ztzTmmg)
  * :question: run-python-ui-tests [#[2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136]](https://paste.fedoraproject.org/paste/ASGImcFU8WvZSd8SFNB31A)

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#159](https://paste.fedoraproject.org/paste/DbbnOg0TO2Qv77YycK4Clw)
  * :heavy_check_mark: python-ui-tests-parallel [#[135]](https://paste.fedoraproject.org/paste/nJo5okW6aqmqu99Ionxryg)
  * :heavy_check_mark: run-python-ui-tests [#[2144, 2145, 2146, 2147, 2137, 2138, 2139, 2140, 2141, 2142, 2143]](https://paste.fedoraproject.org/paste/nvedHLeWii2uzun1Zu-6og)

**Pull request merged**
