### PR TITLE
Added Workload Health testing. Some refactorings.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#134](https://paste.fedoraproject.org/paste/~0L1WFoU18D4pmQbl9vnYw)
  * :question: python-ui-tests-parallel [#[89]](https://paste.fedoraproject.org/paste/D9AitBDbI7ld0Wv~6XJo0w)
  * :question: run-python-ui-tests [#[1632, 1633, 1634, 1635, 1636, 1637, 1627, 1628, 1629, 1630, 1631]](https://paste.fedoraproject.org/paste/meI4xlJkOFYWQTW7~HgFTQ)

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#138](https://paste.fedoraproject.org/paste/6cAt22zjGEZe6n4O37ok7A)
  * :question: python-ui-tests-parallel [#[96]](https://paste.fedoraproject.org/paste/ziLGMRGhmFK1DD68nVvdJw)
  * :question: run-python-ui-tests [#[1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713]](https://paste.fedoraproject.org/paste/3~IM68Q9p229Orkhfvq8OQ)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#139](https://paste.fedoraproject.org/paste/i4oGWtoFMZCMdz23ViCU8Q)
  * :question: python-ui-tests-parallel [#[97]](https://paste.fedoraproject.org/paste/udXfOQvkg2Yj3gJuLlDVKA)
  * :question: run-python-ui-tests [#[1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724]](https://paste.fedoraproject.org/paste/6vrwM4coFeEDIOZbZlPKTA)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#140](https://paste.fedoraproject.org/paste/kINzCwPyCw-PTAVTwdZWFA)
  * :question: python-ui-tests-parallel [#[99]](https://paste.fedoraproject.org/paste/-FR0YDUwMBh4NlZfVBkdzg)
  * :question: run-python-ui-tests [#[1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748]](https://paste.fedoraproject.org/paste/leSkyEEYrATCqocRcYCi2A)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#141](https://paste.fedoraproject.org/paste/S4q2sSF2Y55EtqmncbMQcg)
  * :question: python-ui-tests-parallel [#[100]](https://paste.fedoraproject.org/paste/sLFBaVNpY-FE9W2foIUr3Q)
  * :question: run-python-ui-tests [#[1760, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759]](https://paste.fedoraproject.org/paste/B0VKFFLJVhMYb2fFWro2KQ)

**Comment by kialiqeci** [comment]
:question: Jenkins CI: python-ui-test-pr [#142](https://paste.fedoraproject.org/paste/NetnJ6c6gQlY73A~UJM8Vw)
  * :question: python-ui-tests-parallel [#[101]](https://paste.fedoraproject.org/paste/GT1WP4lnGPkWQ-YXgHFkCw)
  * :question: run-python-ui-tests [#[1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771]](https://paste.fedoraproject.org/paste/Y4YR2hiTFhpbYVn-122ogw)

**Comment by hhovsepy** [comment]
failures are random and not related to this fix

**Pull request merged**
