### PR TITLE
Returned back OpenShift client and updated UI changes

### PR DESCRIPTION
**Pull request by jkandasa**
* Returned back OpenShift client and tests
* Update Istio Config page changes

### CODE REVIEW

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#51](https://paste.fedoraproject.org/paste/GfYCIK2kAJ1gTn-hvBio1Q)
  * :heavy_check_mark: run-python-ui-tests [#343](https://paste.fedoraproject.org/paste/OLpAgDtE1vklhLgLcA2Jjw)
--------------

**Comment by jkandasa** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#52](https://paste.fedoraproject.org/paste/DAbcVyJahNXwVcRn9iopzQ)
  * :heavy_check_mark: run-python-ui-tests [#344](https://paste.fedoraproject.org/paste/Iix9WkPsSg9Sn7BN0-KnOQ)
--------------

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: python-ui-test-pr [#53](https://paste.fedoraproject.org/paste/f802nTQXWCWFsA-JbWrUBQ)
  * :heavy_check_mark: run-python-ui-tests [#347](https://paste.fedoraproject.org/paste/sQMyUudjH7dRmAYKvFMc8Q)
--------------

**Pull request merged**
