### PR TITLE
Added new test case for mtls

### PR DESCRIPTION
**Pull request by prachiyadav**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Can one of the admins verify this patch?

**Comment by pbajjuri20** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Jenkins CI: python-ui-test-pr [#676](https://paste.centos.org/view/8d997076 )
  * :question: upstream-istio-pipeline [#[891]](https://paste.centos.org/view/3928795d )
  * :heavy_check_mark: build-kiali [#[3685]](Log omitted)
  * :heavy_check_mark: build-kiali-operator [#[1121]](Log omitted)
  * :heavy_check_mark: install-istio [#[1920]](Log omitted)
  * :heavy_check_mark: clean-environment [#[14635, 14636, 14637, 14638]](Log omitted)
  * :heavy_check_mark: istio-kiali-mesh-checker [#[10505, 10506, 10507, 10508]](Log omitted)
  * :heavy_check_mark: install-bookinfo [#[7820, 7821, 7822]](Log omitted)
  * :question: run-kiali-ui-tests-parallel [#[2059]](https://paste.centos.org/view/fbcf183c )
  * :question: run-kiali-ui-tests [#[35212, 35213, 35214, 35215, 35216, 35217, 35218, 35219, 35220, 35221, 35222, 35223, 35224, 35225, 35226, 35227, 35228]](https://paste.centos.org/view/fc72dd82 https://paste.centos.org/view/5f2a26f8 )

**Review by pbajjuri20 — COMMENTED** [review]
Indentation error at 207 line

**Comment by hhovsepy** [comment]
./kiali_qe/components/enums.py:450:1: W293 blank line contains whitespace
./kiali_qe/components/enums.py:451:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:9:23: W291 trailing whitespace
./kiali_qe/tests/test_overview_page.py:205:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:206:1: W293 blank line contains whitespace
./kiali_qe/tests/test_overview_page.py:207:5: E303 too many blank lines (2)
./kiali_qe/tests/test_overview_page.py:208:1: E999 IndentationError: unexpected unindent

Run flake8 command to make sure code style is correct.

**Comment by hhovsepy** [comment]
@prachiyadav please change 'apply_filters' to 'assert_all_items'

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Pull request merged**
